// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Agent {
    pub id: String,
    pub identity: __sdk::Identity,
    pub status: String,
    pub last_seen: u64,
}

impl __sdk::InModule for Agent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Agent`.
///
/// Provides typed access to columns for query building.
pub struct AgentCols {
    pub id: __sdk::__query_builder::Col<Agent, String>,
    pub identity: __sdk::__query_builder::Col<Agent, __sdk::Identity>,
    pub status: __sdk::__query_builder::Col<Agent, String>,
    pub last_seen: __sdk::__query_builder::Col<Agent, u64>,
}

impl __sdk::__query_builder::HasCols for Agent {
    type Cols = AgentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `Agent`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentIxCols {
    pub id: __sdk::__query_builder::IxCol<Agent, String>,
}

impl __sdk::__query_builder::HasIxCols for Agent {
    type IxCols = AgentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Agent {}
