// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertMessageArgs {
    pub session_id: String,
    pub sender: String,
    pub content: String,
}

impl From<InsertMessageArgs> for super::Reducer {
    fn from(args: InsertMessageArgs) -> Self {
        Self::InsertMessage {
            session_id: args.session_id,
            sender: args.sender,
            content: args.content,
        }
    }
}

impl __sdk::InModule for InsertMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_message {
    /// Request that the remote module invoke the reducer `insert_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_message:insert_message_then`] to run a callback after the reducer completes.
    fn insert_message(
        &self,
        session_id: String,
        sender: String,
        content: String,
    ) -> __sdk::Result<()> {
        self.insert_message_then(session_id, sender, content, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `insert_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_message_then(
        &self,
        session_id: String,
        sender: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_message for super::RemoteReducers {
    fn insert_message_then(
        &self,
        session_id: String,
        sender: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertMessageArgs {
                session_id,
                sender,
                content,
            },
            callback,
        )
    }
}
