// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::session_type::Session;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sessions`.
///
/// Obtain a handle from the [`SessionsTableAccess::sessions`] method on [`super::RemoteTables`],
/// like `ctx.db.sessions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sessions().on_insert(...)`.
pub struct SessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Session>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sessions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SessionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SessionsTableHandle`], which mediates access to the table `sessions`.
    fn sessions(&self) -> SessionsTableHandle<'_>;
}

impl SessionsTableAccess for super::RemoteTables {
    fn sessions(&self) -> SessionsTableHandle<'_> {
        SessionsTableHandle {
            imp: self.imp.get_table::<Session>("sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SessionsInsertCallbackId(__sdk::CallbackId);
pub struct SessionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SessionsTableHandle<'ctx> {
    type Row = Session;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Session> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionsInsertCallbackId {
        SessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionsDeleteCallbackId {
        SessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SessionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SessionsTableHandle<'ctx> {
    type UpdateCallbackId = SessionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SessionsUpdateCallbackId {
        SessionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SessionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sessions`,
/// which allows point queries on the field of the same name
/// via the [`SessionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sessions().id().find(...)`.
pub struct SessionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Session, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SessionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sessions`.
    pub fn id(&self) -> SessionsIdUnique<'ctx> {
        SessionsIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SessionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Session> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Session>("sessions");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Session>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Session>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Session`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sessionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Session`.
    fn sessions(&self) -> __sdk::__query_builder::Table<Session>;
}

impl sessionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sessions(&self) -> __sdk::__query_builder::Table<Session> {
        __sdk::__query_builder::Table::new("sessions")
    }
}
