// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitTaskArgs {
    pub session_id: Option<String>,
    pub objective: String,
}

impl From<SubmitTaskArgs> for super::Reducer {
    fn from(args: SubmitTaskArgs) -> Self {
        Self::SubmitTask {
            session_id: args.session_id,
            objective: args.objective,
        }
    }
}

impl __sdk::InModule for SubmitTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_task {
    /// Request that the remote module invoke the reducer `submit_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_task:submit_task_then`] to run a callback after the reducer completes.
    fn submit_task(&self, session_id: Option<String>, objective: String) -> __sdk::Result<()> {
        self.submit_task_then(session_id, objective, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_task_then(
        &self,
        session_id: Option<String>,
        objective: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_task for super::RemoteReducers {
    fn submit_task_then(
        &self,
        session_id: Option<String>,
        objective: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitTaskArgs {
                session_id,
                objective,
            },
            callback,
        )
    }
}
