// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CaptainFocus {
    pub focus_id: String,
    pub topic: String,
    pub context_json: String,
    pub priority: u8,
    pub created_at: u64,
    pub resolved_at: u64,
}

impl __sdk::InModule for CaptainFocus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CaptainFocus`.
///
/// Provides typed access to columns for query building.
pub struct CaptainFocusCols {
    pub focus_id: __sdk::__query_builder::Col<CaptainFocus, String>,
    pub topic: __sdk::__query_builder::Col<CaptainFocus, String>,
    pub context_json: __sdk::__query_builder::Col<CaptainFocus, String>,
    pub priority: __sdk::__query_builder::Col<CaptainFocus, u8>,
    pub created_at: __sdk::__query_builder::Col<CaptainFocus, u64>,
    pub resolved_at: __sdk::__query_builder::Col<CaptainFocus, u64>,
}

impl __sdk::__query_builder::HasCols for CaptainFocus {
    type Cols = CaptainFocusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CaptainFocusCols {
            focus_id: __sdk::__query_builder::Col::new(table_name, "focus_id"),
            topic: __sdk::__query_builder::Col::new(table_name, "topic"),
            context_json: __sdk::__query_builder::Col::new(table_name, "context_json"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            resolved_at: __sdk::__query_builder::Col::new(table_name, "resolved_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CaptainFocus`.
///
/// Provides typed access to indexed columns for query building.
pub struct CaptainFocusIxCols {
    pub focus_id: __sdk::__query_builder::IxCol<CaptainFocus, String>,
    pub priority: __sdk::__query_builder::IxCol<CaptainFocus, u8>,
}

impl __sdk::__query_builder::HasIxCols for CaptainFocus {
    type IxCols = CaptainFocusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CaptainFocusIxCols {
            focus_id: __sdk::__query_builder::IxCol::new(table_name, "focus_id"),
            priority: __sdk::__query_builder::IxCol::new(table_name, "priority"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CaptainFocus {}
