// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CloseSessionArgs {
    pub session_id: String,
}

impl From<CloseSessionArgs> for super::Reducer {
    fn from(args: CloseSessionArgs) -> Self {
        Self::CloseSession {
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for CloseSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait close_session {
    fn close_session(&self, session_id: String) -> __sdk::Result<()> {
        self.close_session_then(session_id, |_, _| {})
    }

    fn close_session_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl close_session for super::RemoteReducers {
    fn close_session_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CloseSessionArgs { session_id },
            callback,
        )
    }
}
