// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateMissionArgs {
    pub mission_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub status: String,
    pub source_surface: String,
    pub node_id: String,
    pub prompt: String,
    pub intent_class: String,
    pub risk_level: String,
    pub active_step_id: Option<String>,
    pub active_cell_id: Option<String>,
    pub target_tool: Option<String>,
    pub target_model: Option<String>,
    pub summary: Option<String>,
    pub error: Option<String>,
    pub metadata_json: String,
    pub user_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<CreateMissionArgs> for super::Reducer {
    fn from(args: CreateMissionArgs) -> Self {
        Self::CreateMission {
            mission_id: args.mission_id,
            created_at: args.created_at,
            updated_at: args.updated_at,
            status: args.status,
            source_surface: args.source_surface,
            node_id: args.node_id,
            prompt: args.prompt,
            intent_class: args.intent_class,
            risk_level: args.risk_level,
            active_step_id: args.active_step_id,
            active_cell_id: args.active_cell_id,
            target_tool: args.target_tool,
            target_model: args.target_model,
            summary: args.summary,
            error: args.error,
            metadata_json: args.metadata_json,
            user_id: args.user_id,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for CreateMissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_mission`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_mission {
    /// Request that the remote module invoke the reducer `create_mission` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_mission:create_mission_then`] to run a callback after the reducer completes.
    fn create_mission(
        &self,
        mission_id: String,
        created_at: String,
        updated_at: String,
        status: String,
        source_surface: String,
        node_id: String,
        prompt: String,
        intent_class: String,
        risk_level: String,
        active_step_id: Option<String>,
        active_cell_id: Option<String>,
        target_tool: Option<String>,
        target_model: Option<String>,
        summary: Option<String>,
        error: Option<String>,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_mission_then(
            mission_id,
            created_at,
            updated_at,
            status,
            source_surface,
            node_id,
            prompt,
            intent_class,
            risk_level,
            active_step_id,
            active_cell_id,
            target_tool,
            target_model,
            summary,
            error,
            metadata_json,
            user_id,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_mission` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_mission_then(
        &self,
        mission_id: String,
        created_at: String,
        updated_at: String,
        status: String,
        source_surface: String,
        node_id: String,
        prompt: String,
        intent_class: String,
        risk_level: String,
        active_step_id: Option<String>,
        active_cell_id: Option<String>,
        target_tool: Option<String>,
        target_model: Option<String>,
        summary: Option<String>,
        error: Option<String>,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_mission for super::RemoteReducers {
    fn create_mission_then(
        &self,
        mission_id: String,
        created_at: String,
        updated_at: String,
        status: String,
        source_surface: String,
        node_id: String,
        prompt: String,
        intent_class: String,
        risk_level: String,
        active_step_id: Option<String>,
        active_cell_id: Option<String>,
        target_tool: Option<String>,
        target_model: Option<String>,
        summary: Option<String>,
        error: Option<String>,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateMissionArgs {
                mission_id,
                created_at,
                updated_at,
                status,
                source_surface,
                node_id,
                prompt,
                intent_class,
                risk_level,
                active_step_id,
                active_cell_id,
                target_tool,
                target_model,
                summary,
                error,
                metadata_json,
                user_id,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
