// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::discord_interaction_type::DiscordInteraction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `discord_interactions`.
///
/// Obtain a handle from the [`DiscordInteractionsTableAccess::discord_interactions`] method on [`super::RemoteTables`],
/// like `ctx.db.discord_interactions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.discord_interactions().on_insert(...)`.
pub struct DiscordInteractionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<DiscordInteraction>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `discord_interactions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DiscordInteractionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DiscordInteractionsTableHandle`], which mediates access to the table `discord_interactions`.
    fn discord_interactions(&self) -> DiscordInteractionsTableHandle<'_>;
}

impl DiscordInteractionsTableAccess for super::RemoteTables {
    fn discord_interactions(&self) -> DiscordInteractionsTableHandle<'_> {
        DiscordInteractionsTableHandle {
            imp: self
                .imp
                .get_table::<DiscordInteraction>("discord_interactions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DiscordInteractionsInsertCallbackId(__sdk::CallbackId);
pub struct DiscordInteractionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DiscordInteractionsTableHandle<'ctx> {
    type Row = DiscordInteraction;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DiscordInteraction> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DiscordInteractionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DiscordInteractionsInsertCallbackId {
        DiscordInteractionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DiscordInteractionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DiscordInteractionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DiscordInteractionsDeleteCallbackId {
        DiscordInteractionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DiscordInteractionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DiscordInteractionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DiscordInteractionsTableHandle<'ctx> {
    type UpdateCallbackId = DiscordInteractionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DiscordInteractionsUpdateCallbackId {
        DiscordInteractionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DiscordInteractionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `discord_interactions`,
/// which allows point queries on the field of the same name
/// via the [`DiscordInteractionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.discord_interactions().id().find(...)`.
pub struct DiscordInteractionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DiscordInteraction, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DiscordInteractionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `discord_interactions`.
    pub fn id(&self) -> DiscordInteractionsIdUnique<'ctx> {
        DiscordInteractionsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DiscordInteractionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DiscordInteraction> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DiscordInteraction>("discord_interactions");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DiscordInteraction>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DiscordInteraction>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DiscordInteraction`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait discord_interactionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DiscordInteraction`.
    fn discord_interactions(&self) -> __sdk::__query_builder::Table<DiscordInteraction>;
}

impl discord_interactionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn discord_interactions(&self) -> __sdk::__query_builder::Table<DiscordInteraction> {
        __sdk::__query_builder::Table::new("discord_interactions")
    }
}
