// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::execution_memory_type::ExecutionMemory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `execution_memory`.
///
/// Obtain a handle from the [`ExecutionMemoryTableAccess::execution_memory`] method on [`super::RemoteTables`],
/// like `ctx.db.execution_memory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.execution_memory().on_insert(...)`.
pub struct ExecutionMemoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<ExecutionMemory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `execution_memory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExecutionMemoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ExecutionMemoryTableHandle`], which mediates access to the table `execution_memory`.
    fn execution_memory(&self) -> ExecutionMemoryTableHandle<'_>;
}

impl ExecutionMemoryTableAccess for super::RemoteTables {
    fn execution_memory(&self) -> ExecutionMemoryTableHandle<'_> {
        ExecutionMemoryTableHandle {
            imp: self.imp.get_table::<ExecutionMemory>("execution_memory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ExecutionMemoryInsertCallbackId(__sdk::CallbackId);
pub struct ExecutionMemoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExecutionMemoryTableHandle<'ctx> {
    type Row = ExecutionMemory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ExecutionMemory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ExecutionMemoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExecutionMemoryInsertCallbackId {
        ExecutionMemoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExecutionMemoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ExecutionMemoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExecutionMemoryDeleteCallbackId {
        ExecutionMemoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ExecutionMemoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ExecutionMemoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExecutionMemoryTableHandle<'ctx> {
    type UpdateCallbackId = ExecutionMemoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ExecutionMemoryUpdateCallbackId {
        ExecutionMemoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ExecutionMemoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `execution_memory`,
/// which allows point queries on the field of the same name
/// via the [`ExecutionMemoryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.execution_memory().id().find(...)`.
pub struct ExecutionMemoryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ExecutionMemory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExecutionMemoryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `execution_memory`.
    pub fn id(&self) -> ExecutionMemoryIdUnique<'ctx> {
        ExecutionMemoryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ExecutionMemoryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ExecutionMemory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ExecutionMemory>("execution_memory");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ExecutionMemory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ExecutionMemory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ExecutionMemory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait execution_memoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ExecutionMemory`.
    fn execution_memory(&self) -> __sdk::__query_builder::Table<ExecutionMemory>;
}

impl execution_memoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn execution_memory(&self) -> __sdk::__query_builder::Table<ExecutionMemory> {
        __sdk::__query_builder::Table::new("execution_memory")
    }
}
