// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExecutionMemory {
    pub id: u64,
    pub task_dispatch_id: String,
    pub model_used: String,
    pub outcome: String,
    pub duration_ms: u64,
    pub error_summary: Option<String>,
    pub feedback_score: Option<f64>,
    pub created_at: String,
    pub lease_id: Option<String>,
}

impl __sdk::InModule for ExecutionMemory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ExecutionMemory`.
///
/// Provides typed access to columns for query building.
pub struct ExecutionMemoryCols {
    pub id: __sdk::__query_builder::Col<ExecutionMemory, u64>,
    pub task_dispatch_id: __sdk::__query_builder::Col<ExecutionMemory, String>,
    pub model_used: __sdk::__query_builder::Col<ExecutionMemory, String>,
    pub outcome: __sdk::__query_builder::Col<ExecutionMemory, String>,
    pub duration_ms: __sdk::__query_builder::Col<ExecutionMemory, u64>,
    pub error_summary: __sdk::__query_builder::Col<ExecutionMemory, Option<String>>,
    pub feedback_score: __sdk::__query_builder::Col<ExecutionMemory, Option<f64>>,
    pub created_at: __sdk::__query_builder::Col<ExecutionMemory, String>,
    pub lease_id: __sdk::__query_builder::Col<ExecutionMemory, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ExecutionMemory {
    type Cols = ExecutionMemoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ExecutionMemoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            task_dispatch_id: __sdk::__query_builder::Col::new(table_name, "task_dispatch_id"),
            model_used: __sdk::__query_builder::Col::new(table_name, "model_used"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            duration_ms: __sdk::__query_builder::Col::new(table_name, "duration_ms"),
            error_summary: __sdk::__query_builder::Col::new(table_name, "error_summary"),
            feedback_score: __sdk::__query_builder::Col::new(table_name, "feedback_score"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ExecutionMemory`.
///
/// Provides typed access to indexed columns for query building.
pub struct ExecutionMemoryIxCols {
    pub id: __sdk::__query_builder::IxCol<ExecutionMemory, u64>,
    pub lease_id: __sdk::__query_builder::IxCol<ExecutionMemory, Option<String>>,
    pub task_dispatch_id: __sdk::__query_builder::IxCol<ExecutionMemory, String>,
}

impl __sdk::__query_builder::HasIxCols for ExecutionMemory {
    type IxCols = ExecutionMemoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ExecutionMemoryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            task_dispatch_id: __sdk::__query_builder::IxCol::new(table_name, "task_dispatch_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ExecutionMemory {}
