// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertCaptainMessageArgs {
    pub message_id: String,
    pub session_id: String,
    pub role: String,
    pub content: String,
    pub timestamp: u64,
    pub source: String,
}

impl From<InsertCaptainMessageArgs> for super::Reducer {
    fn from(args: InsertCaptainMessageArgs) -> Self {
        Self::InsertCaptainMessage {
            message_id: args.message_id,
            session_id: args.session_id,
            role: args.role,
            content: args.content,
            timestamp: args.timestamp,
            source: args.source,
        }
    }
}

impl __sdk::InModule for InsertCaptainMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_captain_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_captain_message {
    /// Request that the remote module invoke the reducer `insert_captain_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_captain_message:insert_captain_message_then`] to run a callback after the reducer completes.
    fn insert_captain_message(
        &self,
        message_id: String,
        session_id: String,
        role: String,
        content: String,
        timestamp: u64,
        source: String,
    ) -> __sdk::Result<()> {
        self.insert_captain_message_then(
            message_id,
            session_id,
            role,
            content,
            timestamp,
            source,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `insert_captain_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_captain_message_then(
        &self,
        message_id: String,
        session_id: String,
        role: String,
        content: String,
        timestamp: u64,
        source: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_captain_message for super::RemoteReducers {
    fn insert_captain_message_then(
        &self,
        message_id: String,
        session_id: String,
        role: String,
        content: String,
        timestamp: u64,
        source: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertCaptainMessageArgs {
                message_id,
                session_id,
                role,
                content,
                timestamp,
                source,
            },
            callback,
        )
    }
}
