// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::liveness_state_type::LivenessState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `liveness_state`.
///
/// Obtain a handle from the [`LivenessStateTableAccess::liveness_state`] method on [`super::RemoteTables`],
/// like `ctx.db.liveness_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.liveness_state().on_insert(...)`.
pub struct LivenessStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<LivenessState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `liveness_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LivenessStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LivenessStateTableHandle`], which mediates access to the table `liveness_state`.
    fn liveness_state(&self) -> LivenessStateTableHandle<'_>;
}

impl LivenessStateTableAccess for super::RemoteTables {
    fn liveness_state(&self) -> LivenessStateTableHandle<'_> {
        LivenessStateTableHandle {
            imp: self.imp.get_table::<LivenessState>("liveness_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LivenessStateInsertCallbackId(__sdk::CallbackId);
pub struct LivenessStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LivenessStateTableHandle<'ctx> {
    type Row = LivenessState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LivenessState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LivenessStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LivenessStateInsertCallbackId {
        LivenessStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LivenessStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LivenessStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LivenessStateDeleteCallbackId {
        LivenessStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LivenessStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LivenessStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LivenessStateTableHandle<'ctx> {
    type UpdateCallbackId = LivenessStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LivenessStateUpdateCallbackId {
        LivenessStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LivenessStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `liveness_state`,
/// which allows point queries on the field of the same name
/// via the [`LivenessStateKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.liveness_state().key().find(...)`.
pub struct LivenessStateKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LivenessState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LivenessStateTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `liveness_state`.
    pub fn key(&self) -> LivenessStateKeyUnique<'ctx> {
        LivenessStateKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LivenessStateKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LivenessState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LivenessState>("liveness_state");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LivenessState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LivenessState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LivenessState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait liveness_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LivenessState`.
    fn liveness_state(&self) -> __sdk::__query_builder::Table<LivenessState>;
}

impl liveness_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn liveness_state(&self) -> __sdk::__query_builder::Table<LivenessState> {
        __sdk::__query_builder::Table::new("liveness_state")
    }
}
