// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mission_step_record_type::MissionStepRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mission_steps`.
///
/// Obtain a handle from the [`MissionStepsTableAccess::mission_steps`] method on [`super::RemoteTables`],
/// like `ctx.db.mission_steps()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mission_steps().on_insert(...)`.
pub struct MissionStepsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MissionStepRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mission_steps`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MissionStepsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MissionStepsTableHandle`], which mediates access to the table `mission_steps`.
    fn mission_steps(&self) -> MissionStepsTableHandle<'_>;
}

impl MissionStepsTableAccess for super::RemoteTables {
    fn mission_steps(&self) -> MissionStepsTableHandle<'_> {
        MissionStepsTableHandle {
            imp: self.imp.get_table::<MissionStepRecord>("mission_steps"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MissionStepsInsertCallbackId(__sdk::CallbackId);
pub struct MissionStepsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MissionStepsTableHandle<'ctx> {
    type Row = MissionStepRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MissionStepRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MissionStepsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MissionStepsInsertCallbackId {
        MissionStepsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MissionStepsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MissionStepsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MissionStepsDeleteCallbackId {
        MissionStepsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MissionStepsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MissionStepsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MissionStepsTableHandle<'ctx> {
    type UpdateCallbackId = MissionStepsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MissionStepsUpdateCallbackId {
        MissionStepsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MissionStepsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `step_id` unique index on the table `mission_steps`,
/// which allows point queries on the field of the same name
/// via the [`MissionStepsStepIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mission_steps().step_id().find(...)`.
pub struct MissionStepsStepIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MissionStepRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MissionStepsTableHandle<'ctx> {
    /// Get a handle on the `step_id` unique index on the table `mission_steps`.
    pub fn step_id(&self) -> MissionStepsStepIdUnique<'ctx> {
        MissionStepsStepIdUnique {
            imp: self.imp.get_unique_constraint::<String>("step_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MissionStepsStepIdUnique<'ctx> {
    /// Find the subscribed row whose `step_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MissionStepRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MissionStepRecord>("mission_steps");
    _table.add_unique_constraint::<String>("step_id", |row| &row.step_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MissionStepRecord>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MissionStepRecord>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MissionStepRecord`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait mission_stepsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MissionStepRecord`.
    fn mission_steps(&self) -> __sdk::__query_builder::Table<MissionStepRecord>;
}

impl mission_stepsQueryTableAccess for __sdk::QueryTableAccessor {
    fn mission_steps(&self) -> __sdk::__query_builder::Table<MissionStepRecord> {
        __sdk::__query_builder::Table::new("mission_steps")
    }
}
