// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::node_registry_entry_type::NodeRegistryEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `node_registry`.
///
/// Obtain a handle from the [`NodeRegistryTableAccess::node_registry`] method on [`super::RemoteTables`],
/// like `ctx.db.node_registry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_registry().on_insert(...)`.
pub struct NodeRegistryTableHandle<'ctx> {
    imp: __sdk::TableHandle<NodeRegistryEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `node_registry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NodeRegistryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NodeRegistryTableHandle`], which mediates access to the table `node_registry`.
    fn node_registry(&self) -> NodeRegistryTableHandle<'_>;
}

impl NodeRegistryTableAccess for super::RemoteTables {
    fn node_registry(&self) -> NodeRegistryTableHandle<'_> {
        NodeRegistryTableHandle {
            imp: self.imp.get_table::<NodeRegistryEntry>("node_registry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NodeRegistryInsertCallbackId(__sdk::CallbackId);
pub struct NodeRegistryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NodeRegistryTableHandle<'ctx> {
    type Row = NodeRegistryEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeRegistryEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NodeRegistryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeRegistryInsertCallbackId {
        NodeRegistryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeRegistryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NodeRegistryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeRegistryDeleteCallbackId {
        NodeRegistryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeRegistryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NodeRegistryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NodeRegistryTableHandle<'ctx> {
    type UpdateCallbackId = NodeRegistryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeRegistryUpdateCallbackId {
        NodeRegistryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeRegistryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `node_id` unique index on the table `node_registry`,
/// which allows point queries on the field of the same name
/// via the [`NodeRegistryNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_registry().node_id().find(...)`.
pub struct NodeRegistryNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NodeRegistryEntry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NodeRegistryTableHandle<'ctx> {
    /// Get a handle on the `node_id` unique index on the table `node_registry`.
    pub fn node_id(&self) -> NodeRegistryNodeIdUnique<'ctx> {
        NodeRegistryNodeIdUnique {
            imp: self.imp.get_unique_constraint::<String>("node_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NodeRegistryNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `node_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<NodeRegistryEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NodeRegistryEntry>("node_registry");
    _table.add_unique_constraint::<String>("node_id", |row| &row.node_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NodeRegistryEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NodeRegistryEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NodeRegistryEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait node_registryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NodeRegistryEntry`.
    fn node_registry(&self) -> __sdk::__query_builder::Table<NodeRegistryEntry>;
}

impl node_registryQueryTableAccess for __sdk::QueryTableAccessor {
    fn node_registry(&self) -> __sdk::__query_builder::Table<NodeRegistryEntry> {
        __sdk::__query_builder::Table::new("node_registry")
    }
}
