// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NodeRegistryEntry {
    pub node_id: String,
    pub hostname: String,
    pub platform: String,
    pub capabilities_json: String,
    pub last_heartbeat: Option<String>,
    pub status: String,
}

impl __sdk::InModule for NodeRegistryEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NodeRegistryEntry`.
///
/// Provides typed access to columns for query building.
pub struct NodeRegistryEntryCols {
    pub node_id: __sdk::__query_builder::Col<NodeRegistryEntry, String>,
    pub hostname: __sdk::__query_builder::Col<NodeRegistryEntry, String>,
    pub platform: __sdk::__query_builder::Col<NodeRegistryEntry, String>,
    pub capabilities_json: __sdk::__query_builder::Col<NodeRegistryEntry, String>,
    pub last_heartbeat: __sdk::__query_builder::Col<NodeRegistryEntry, Option<String>>,
    pub status: __sdk::__query_builder::Col<NodeRegistryEntry, String>,
}

impl __sdk::__query_builder::HasCols for NodeRegistryEntry {
    type Cols = NodeRegistryEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NodeRegistryEntryCols {
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            hostname: __sdk::__query_builder::Col::new(table_name, "hostname"),
            platform: __sdk::__query_builder::Col::new(table_name, "platform"),
            capabilities_json: __sdk::__query_builder::Col::new(table_name, "capabilities_json"),
            last_heartbeat: __sdk::__query_builder::Col::new(table_name, "last_heartbeat"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
        }
    }
}

/// Indexed column accessor struct for the table `NodeRegistryEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct NodeRegistryEntryIxCols {
    pub node_id: __sdk::__query_builder::IxCol<NodeRegistryEntry, String>,
}

impl __sdk::__query_builder::HasIxCols for NodeRegistryEntry {
    type IxCols = NodeRegistryEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NodeRegistryEntryIxCols {
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NodeRegistryEntry {}
