// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Pod {
    pub pod_id: String,
    pub host_identity: String,
    pub provider: String,
    pub runtime_capabilities: Vec<String>,
    pub trust_tier: String,
    pub privacy_floor: String,
    pub liveness: String,
    pub leaseable: bool,
    pub registered_at: String,
    pub last_heartbeat: String,
}

impl __sdk::InModule for Pod {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Pod`.
///
/// Provides typed access to columns for query building.
pub struct PodCols {
    pub pod_id: __sdk::__query_builder::Col<Pod, String>,
    pub host_identity: __sdk::__query_builder::Col<Pod, String>,
    pub provider: __sdk::__query_builder::Col<Pod, String>,
    pub runtime_capabilities: __sdk::__query_builder::Col<Pod, Vec<String>>,
    pub trust_tier: __sdk::__query_builder::Col<Pod, String>,
    pub privacy_floor: __sdk::__query_builder::Col<Pod, String>,
    pub liveness: __sdk::__query_builder::Col<Pod, String>,
    pub leaseable: __sdk::__query_builder::Col<Pod, bool>,
    pub registered_at: __sdk::__query_builder::Col<Pod, String>,
    pub last_heartbeat: __sdk::__query_builder::Col<Pod, String>,
}

impl __sdk::__query_builder::HasCols for Pod {
    type Cols = PodCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PodCols {
            pod_id: __sdk::__query_builder::Col::new(table_name, "pod_id"),
            host_identity: __sdk::__query_builder::Col::new(table_name, "host_identity"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            runtime_capabilities: __sdk::__query_builder::Col::new(
                table_name,
                "runtime_capabilities",
            ),
            trust_tier: __sdk::__query_builder::Col::new(table_name, "trust_tier"),
            privacy_floor: __sdk::__query_builder::Col::new(table_name, "privacy_floor"),
            liveness: __sdk::__query_builder::Col::new(table_name, "liveness"),
            leaseable: __sdk::__query_builder::Col::new(table_name, "leaseable"),
            registered_at: __sdk::__query_builder::Col::new(table_name, "registered_at"),
            last_heartbeat: __sdk::__query_builder::Col::new(table_name, "last_heartbeat"),
        }
    }
}

/// Indexed column accessor struct for the table `Pod`.
///
/// Provides typed access to indexed columns for query building.
pub struct PodIxCols {
    pub liveness: __sdk::__query_builder::IxCol<Pod, String>,
    pub pod_id: __sdk::__query_builder::IxCol<Pod, String>,
}

impl __sdk::__query_builder::HasIxCols for Pod {
    type IxCols = PodIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PodIxCols {
            liveness: __sdk::__query_builder::IxCol::new(table_name, "liveness"),
            pod_id: __sdk::__query_builder::IxCol::new(table_name, "pod_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Pod {}
