// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordRunArgs {
    pub run_id: String,
    pub user_id: String,
    pub proposal_id: String,
    pub lease_id: String,
    pub started_at: String,
    pub ended_at: String,
    pub status: String,
    pub chain_result_json: String,
    pub signals_json: String,
    pub artifact_index_json: String,
    pub node_id: String,
    pub replay_receipt_json: String,
    pub mode: String,
    pub model_id: String,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub tokens_total: i64,
    pub cost: f64,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<RecordRunArgs> for super::Reducer {
    fn from(args: RecordRunArgs) -> Self {
        Self::RecordRun {
            run_id: args.run_id,
            user_id: args.user_id,
            proposal_id: args.proposal_id,
            lease_id: args.lease_id,
            started_at: args.started_at,
            ended_at: args.ended_at,
            status: args.status,
            chain_result_json: args.chain_result_json,
            signals_json: args.signals_json,
            artifact_index_json: args.artifact_index_json,
            node_id: args.node_id,
            replay_receipt_json: args.replay_receipt_json,
            mode: args.mode,
            model_id: args.model_id,
            tokens_input: args.tokens_input,
            tokens_output: args.tokens_output,
            tokens_total: args.tokens_total,
            cost: args.cost,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for RecordRunArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_run`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_run {
    /// Request that the remote module invoke the reducer `record_run` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_run:record_run_then`] to run a callback after the reducer completes.
    fn record_run(
        &self,
        run_id: String,
        user_id: String,
        proposal_id: String,
        lease_id: String,
        started_at: String,
        ended_at: String,
        status: String,
        chain_result_json: String,
        signals_json: String,
        artifact_index_json: String,
        node_id: String,
        replay_receipt_json: String,
        mode: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        cost: f64,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.record_run_then(
            run_id,
            user_id,
            proposal_id,
            lease_id,
            started_at,
            ended_at,
            status,
            chain_result_json,
            signals_json,
            artifact_index_json,
            node_id,
            replay_receipt_json,
            mode,
            model_id,
            tokens_input,
            tokens_output,
            tokens_total,
            cost,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_run` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_run_then(
        &self,
        run_id: String,
        user_id: String,
        proposal_id: String,
        lease_id: String,
        started_at: String,
        ended_at: String,
        status: String,
        chain_result_json: String,
        signals_json: String,
        artifact_index_json: String,
        node_id: String,
        replay_receipt_json: String,
        mode: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        cost: f64,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_run for super::RemoteReducers {
    fn record_run_then(
        &self,
        run_id: String,
        user_id: String,
        proposal_id: String,
        lease_id: String,
        started_at: String,
        ended_at: String,
        status: String,
        chain_result_json: String,
        signals_json: String,
        artifact_index_json: String,
        node_id: String,
        replay_receipt_json: String,
        mode: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        cost: f64,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordRunArgs {
                run_id,
                user_id,
                proposal_id,
                lease_id,
                started_at,
                ended_at,
                status,
                chain_result_json,
                signals_json,
                artifact_index_json,
                node_id,
                replay_receipt_json,
                mode,
                model_id,
                tokens_input,
                tokens_output,
                tokens_total,
                cost,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
