// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordBillingEventArgs {
    pub user_id: String,
    pub event_type: String,
    pub provider_id: String,
    pub model_id: String,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub estimated_cost_usd: f64,
    pub credential_id: Option<String>,
    pub mission_id: Option<String>,
    pub run_id: Option<String>,
}

impl From<RecordBillingEventArgs> for super::Reducer {
    fn from(args: RecordBillingEventArgs) -> Self {
        Self::RecordBillingEvent {
            user_id: args.user_id,
            event_type: args.event_type,
            provider_id: args.provider_id,
            model_id: args.model_id,
            tokens_input: args.tokens_input,
            tokens_output: args.tokens_output,
            estimated_cost_usd: args.estimated_cost_usd,
            credential_id: args.credential_id,
            mission_id: args.mission_id,
            run_id: args.run_id,
        }
    }
}

impl __sdk::InModule for RecordBillingEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_billing_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_billing_event {
    /// Request that the remote module invoke the reducer `record_billing_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_billing_event:record_billing_event_then`] to run a callback after the reducer completes.
    fn record_billing_event(
        &self,
        user_id: String,
        event_type: String,
        provider_id: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        estimated_cost_usd: f64,
        credential_id: Option<String>,
        mission_id: Option<String>,
        run_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.record_billing_event_then(
            user_id,
            event_type,
            provider_id,
            model_id,
            tokens_input,
            tokens_output,
            estimated_cost_usd,
            credential_id,
            mission_id,
            run_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_billing_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_billing_event_then(
        &self,
        user_id: String,
        event_type: String,
        provider_id: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        estimated_cost_usd: f64,
        credential_id: Option<String>,
        mission_id: Option<String>,
        run_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_billing_event for super::RemoteReducers {
    fn record_billing_event_then(
        &self,
        user_id: String,
        event_type: String,
        provider_id: String,
        model_id: String,
        tokens_input: i64,
        tokens_output: i64,
        estimated_cost_usd: f64,
        credential_id: Option<String>,
        mission_id: Option<String>,
        run_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordBillingEventArgs {
                user_id,
                event_type,
                provider_id,
                model_id,
                tokens_input,
                tokens_output,
                estimated_cost_usd,
                credential_id,
                mission_id,
                run_id,
            },
            callback,
        )
    }
}
