// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeCapabilityLeaseArgs {
    pub lease_id: String,
    pub revoked_at: String,
    pub revocation_reason: Option<String>,
}

impl From<RevokeCapabilityLeaseArgs> for super::Reducer {
    fn from(args: RevokeCapabilityLeaseArgs) -> Self {
        Self::RevokeCapabilityLease {
            lease_id: args.lease_id,
            revoked_at: args.revoked_at,
            revocation_reason: args.revocation_reason,
        }
    }
}

impl __sdk::InModule for RevokeCapabilityLeaseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_capability_lease`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_capability_lease {
    /// Request that the remote module invoke the reducer `revoke_capability_lease` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revoke_capability_lease:revoke_capability_lease_then`] to run a callback after the reducer completes.
    fn revoke_capability_lease(
        &self,
        lease_id: String,
        revoked_at: String,
        revocation_reason: Option<String>,
    ) -> __sdk::Result<()> {
        self.revoke_capability_lease_then(lease_id, revoked_at, revocation_reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_capability_lease` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_capability_lease_then(
        &self,
        lease_id: String,
        revoked_at: String,
        revocation_reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_capability_lease for super::RemoteReducers {
    fn revoke_capability_lease_then(
        &self,
        lease_id: String,
        revoked_at: String,
        revocation_reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RevokeCapabilityLeaseArgs {
                lease_id,
                revoked_at,
                revocation_reason,
            },
            callback,
        )
    }
}
