// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::run_record_type::RunRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `runs`.
///
/// Obtain a handle from the [`RunsTableAccess::runs`] method on [`super::RemoteTables`],
/// like `ctx.db.runs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.runs().on_insert(...)`.
pub struct RunsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RunRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `runs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RunsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RunsTableHandle`], which mediates access to the table `runs`.
    fn runs(&self) -> RunsTableHandle<'_>;
}

impl RunsTableAccess for super::RemoteTables {
    fn runs(&self) -> RunsTableHandle<'_> {
        RunsTableHandle {
            imp: self.imp.get_table::<RunRecord>("runs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RunsInsertCallbackId(__sdk::CallbackId);
pub struct RunsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RunsTableHandle<'ctx> {
    type Row = RunRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RunRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RunsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RunsInsertCallbackId {
        RunsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RunsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RunsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RunsDeleteCallbackId {
        RunsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RunsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RunsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RunsTableHandle<'ctx> {
    type UpdateCallbackId = RunsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RunsUpdateCallbackId {
        RunsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RunsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `run_id` unique index on the table `runs`,
/// which allows point queries on the field of the same name
/// via the [`RunsRunIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.runs().run_id().find(...)`.
pub struct RunsRunIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RunRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RunsTableHandle<'ctx> {
    /// Get a handle on the `run_id` unique index on the table `runs`.
    pub fn run_id(&self) -> RunsRunIdUnique<'ctx> {
        RunsRunIdUnique {
            imp: self.imp.get_unique_constraint::<String>("run_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RunsRunIdUnique<'ctx> {
    /// Find the subscribed row whose `run_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RunRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RunRecord>("runs");
    _table.add_unique_constraint::<String>("run_id", |row| &row.run_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RunRecord>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RunRecord>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RunRecord`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait runsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RunRecord`.
    fn runs(&self) -> __sdk::__query_builder::Table<RunRecord>;
}

impl runsQueryTableAccess for __sdk::QueryTableAccessor {
    fn runs(&self) -> __sdk::__query_builder::Table<RunRecord> {
        __sdk::__query_builder::Table::new("runs")
    }
}
