// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::session_record::SessionRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct SessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SessionRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait SessionsTableAccess {
    #[allow(non_snake_case)]
    fn sessions(&self) -> SessionsTableHandle<'_>;
}

impl SessionsTableAccess for super::RemoteTables {
    fn sessions(&self) -> SessionsTableHandle<'_> {
        SessionsTableHandle {
            imp: self.imp.get_table::<SessionRecord>("sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SessionsInsertCallbackId(__sdk::CallbackId);
pub struct SessionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SessionsTableHandle<'ctx> {
    type Row = SessionRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SessionRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionsInsertCallbackId {
        SessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionsDeleteCallbackId {
        SessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SessionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SessionsTableHandle<'ctx> {
    type UpdateCallbackId = SessionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SessionsUpdateCallbackId {
        SessionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SessionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct SessionsSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SessionRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SessionsTableHandle<'ctx> {
    pub fn session_id(&self) -> SessionsSessionIdUnique<'ctx> {
        SessionsSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SessionsSessionIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<SessionRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SessionRecord>("sessions");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}
