// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::organization_task_type::OrganizationTask;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tenant_task_view`.
///
/// Obtain a handle from the [`TenantTaskViewTableAccess::tenant_task_view`] method on [`super::RemoteTables`],
/// like `ctx.db.tenant_task_view()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tenant_task_view().on_insert(...)`.
pub struct TenantTaskViewTableHandle<'ctx> {
    imp: __sdk::TableHandle<OrganizationTask>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tenant_task_view`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TenantTaskViewTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TenantTaskViewTableHandle`], which mediates access to the table `tenant_task_view`.
    fn tenant_task_view(&self) -> TenantTaskViewTableHandle<'_>;
}

impl TenantTaskViewTableAccess for super::RemoteTables {
    fn tenant_task_view(&self) -> TenantTaskViewTableHandle<'_> {
        TenantTaskViewTableHandle {
            imp: self.imp.get_table::<OrganizationTask>("tenant_task_view"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TenantTaskViewInsertCallbackId(__sdk::CallbackId);
pub struct TenantTaskViewDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TenantTaskViewTableHandle<'ctx> {
    type Row = OrganizationTask;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OrganizationTask> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TenantTaskViewInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TenantTaskViewInsertCallbackId {
        TenantTaskViewInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TenantTaskViewInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TenantTaskViewDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TenantTaskViewDeleteCallbackId {
        TenantTaskViewDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TenantTaskViewDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OrganizationTask>("tenant_task_view");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OrganizationTask>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OrganizationTask>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OrganizationTask`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tenant_task_viewQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OrganizationTask`.
    fn tenant_task_view(&self) -> __sdk::__query_builder::Table<OrganizationTask>;
}

impl tenant_task_viewQueryTableAccess for __sdk::QueryTableAccessor {
    fn tenant_task_view(&self) -> __sdk::__query_builder::Table<OrganizationTask> {
        __sdk::__query_builder::Table::new("tenant_task_view")
    }
}
