// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertAgentRegistryArgs {
    pub cell_id: String,
    pub display_name: String,
    pub model_preference: Option<String>,
    pub tools_allowed_json: String,
    pub sandbox_mode: String,
    pub active: bool,
}

impl From<UpsertAgentRegistryArgs> for super::Reducer {
    fn from(args: UpsertAgentRegistryArgs) -> Self {
        Self::UpsertAgentRegistry {
            cell_id: args.cell_id,
            display_name: args.display_name,
            model_preference: args.model_preference,
            tools_allowed_json: args.tools_allowed_json,
            sandbox_mode: args.sandbox_mode,
            active: args.active,
        }
    }
}

impl __sdk::InModule for UpsertAgentRegistryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_agent_registry`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_agent_registry {
    /// Request that the remote module invoke the reducer `upsert_agent_registry` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_agent_registry:upsert_agent_registry_then`] to run a callback after the reducer completes.
    fn upsert_agent_registry(
        &self,
        cell_id: String,
        display_name: String,
        model_preference: Option<String>,
        tools_allowed_json: String,
        sandbox_mode: String,
        active: bool,
    ) -> __sdk::Result<()> {
        self.upsert_agent_registry_then(
            cell_id,
            display_name,
            model_preference,
            tools_allowed_json,
            sandbox_mode,
            active,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_agent_registry` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_agent_registry_then(
        &self,
        cell_id: String,
        display_name: String,
        model_preference: Option<String>,
        tools_allowed_json: String,
        sandbox_mode: String,
        active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_agent_registry for super::RemoteReducers {
    fn upsert_agent_registry_then(
        &self,
        cell_id: String,
        display_name: String,
        model_preference: Option<String>,
        tools_allowed_json: String,
        sandbox_mode: String,
        active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertAgentRegistryArgs {
                cell_id,
                display_name,
                model_preference,
                tools_allowed_json,
                sandbox_mode,
                active,
            },
            callback,
        )
    }
}
