[workspace]
members = [
    "apps/heiwa_core",
    "apps/heiwa_hub/spacetimedb",
    "apps/heiwa_shell",
    "crates/heiwa_session",
    "crates/heiwa_repl",
    "crates/heiwa_provider",
    "crates/heiwa_install",
    "crates/heiwa_loop",
    "crates/heiwa_stdb",
    "crates/heiwa_protocol",
    "packages/heiwa_bindings/rust",
]
resolver = "2"
