// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  decisionId: __t.string().primaryKey().name("decision_id"),
  requestId: __t.string().name("request_id"),
  proposalId: __t.string().name("proposal_id"),
  actorType: __t.string().name("actor_type"),
  actorId: __t.string().name("actor_id"),
  decision: __t.string(),
  reason: __t.option(__t.string()),
  createdAt: __t.string().name("created_at"),
  metadataJson: __t.string().name("metadata_json"),
});
