// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  proposalId: __t.string(),
  assignedNodeId: __t.string(),
  assignmentExpiresAt: __t.string(),
  hubSignature: __t.string(),
  proposalHash: __t.string(),
  attemptCount: __t.i64(),
  eligibilitySnapshot: __t.option(__t.string()),
};
