// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  eventType: __t.string().name("event_type"),
  providerId: __t.string().name("provider_id"),
  modelId: __t.string().name("model_id"),
  tokensInput: __t.i64().name("tokens_input"),
  tokensOutput: __t.i64().name("tokens_output"),
  estimatedCostUsd: __t.f64().name("estimated_cost_usd"),
  credentialId: __t.option(__t.string()).name("credential_id"),
  missionId: __t.option(__t.string()).name("mission_id"),
  runId: __t.option(__t.string()).name("run_id"),
  createdAt: __t.string().name("created_at"),
});
