// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  leaseId: __t.string().primaryKey().name("lease_id"),
  proposalId: __t.string().name("proposal_id"),
  runId: __t.option(__t.string()).name("run_id"),
  holderKind: __t.string().name("holder_kind"),
  holderId: __t.string().name("holder_id"),
  toolScopeJson: __t.string().name("tool_scope_json"),
  networkScopeJson: __t.string().name("network_scope_json"),
  filesystemScopeJson: __t.string().name("filesystem_scope_json"),
  secretScopeJson: __t.string().name("secret_scope_json"),
  privilegeTier: __t.string().name("privilege_tier"),
  status: __t.string(),
  issuedAt: __t.string().name("issued_at"),
  renewedAt: __t.option(__t.string()).name("renewed_at"),
  expiresAt: __t.string().name("expires_at"),
  revokedAt: __t.option(__t.string()).name("revoked_at"),
  revocationReason: __t.option(__t.string()).name("revocation_reason"),
  hubSignature: __t.string().name("hub_signature"),
  parentLeaseId: __t.option(__t.string()).name("parent_lease_id"),
  failurePolicy: __t.option(__t.string()).name("failure_policy"),
  chainState: __t.option(__t.string()).name("chain_state"),
  routingLockJson: __t.option(__t.string()).name("routing_lock_json"),
  ownerId: __t.option(__t.string()).name("owner_id"),
  principalId: __t.option(__t.string()).name("principal_id"),
});
