// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  directiveType: __t.string().name("directive_type"),
  payloadJson: __t.string().name("payload_json"),
  priority: __t.u8(),
  status: __t.string(),
  createdAt: __t.string().name("created_at"),
  executedAt: __t.option(__t.string()).name("executed_at"),
});
