// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  summaryId: __t.string().primaryKey().name("summary_id"),
  summaryType: __t.string().name("summary_type"),
  content: __t.string(),
  messageRangeStart: __t.u64().name("message_range_start"),
  messageRangeEnd: __t.u64().name("message_range_end"),
  messagesCompressed: __t.u32().name("messages_compressed"),
  createdAt: __t.u64().name("created_at"),
});
