// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cellRunId: __t.string().primaryKey().name("cell_run_id"),
  userId: __t.string().name("user_id"),
  missionId: __t.string().name("mission_id"),
  stepId: __t.option(__t.string()).name("step_id"),
  status: __t.string(),
  cellId: __t.string().name("cell_id"),
  cellRole: __t.string().name("cell_role"),
  provider: __t.string(),
  model: __t.string(),
  rateGroup: __t.string().name("rate_group"),
  tool: __t.string(),
  startedAt: __t.string().name("started_at"),
  endedAt: __t.option(__t.string()).name("ended_at"),
  tokensInput: __t.i64().name("tokens_input"),
  tokensOutput: __t.i64().name("tokens_output"),
  tokensTotal: __t.i64().name("tokens_total"),
  outputSummary: __t.option(__t.string()).name("output_summary"),
});
