// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  missionId: __t.string(),
  userId: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
  status: __t.string(),
  sourceSurface: __t.string(),
  nodeId: __t.string(),
  prompt: __t.string(),
  intentClass: __t.string(),
  riskLevel: __t.string(),
  activeStepId: __t.option(__t.string()),
  activeCellId: __t.option(__t.string()),
  targetTool: __t.option(__t.string()),
  targetModel: __t.option(__t.string()),
  summary: __t.option(__t.string()),
  error: __t.option(__t.string()),
  metadataJson: __t.string(),
};
