// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  decisionId: __t.string().name("decision_id"),
  requestId: __t.string().name("request_id"),
  failureMode: __t.string().name("failure_mode"),
  stage: __t.string(),
  detailsJson: __t.string().name("details_json"),
  recovered: __t.bool(),
  createdAtMs: __t.u64().name("created_at_ms"),
});
