// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddApprovalRequestReducer from "./add_approval_request_reducer";
import AddProposalReducer from "./add_proposal_reducer";
import AppendEventReducer from "./append_event_reducer";
import AppendMissionStepReducer from "./append_mission_step_reducer";
import ApproveProposalReducer from "./approve_proposal_reducer";
import ArchiveBattlefieldReducer from "./archive_battlefield_reducer";
import AssignProposalReducer from "./assign_proposal_reducer";
import AttachDrexDecisionToRouteReducer from "./attach_drex_decision_to_route_reducer";
import ClaimProposalReducer from "./claim_proposal_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CompleteMissionReducer from "./complete_mission_reducer";
import CreateMissionReducer from "./create_mission_reducer";
import CreateTaskDispatchReducer from "./create_task_dispatch_reducer";
import CreateUserReducer from "./create_user_reducer";
import ExpireProposalReducer from "./expire_proposal_reducer";
import FailMissionReducer from "./fail_mission_reducer";
import FinishCellRunReducer from "./finish_cell_run_reducer";
import InsertCaptainDirectiveReducer from "./insert_captain_directive_reducer";
import InsertCaptainMessageReducer from "./insert_captain_message_reducer";
import InsertCaptainSummaryReducer from "./insert_captain_summary_reducer";
import InsertExecutionMemoryReducer from "./insert_execution_memory_reducer";
import InsertKnowledgeEmbeddingReducer from "./insert_knowledge_embedding_reducer";
import IssueCapabilityLeaseReducer from "./issue_capability_lease_reducer";
import LinkOauthIdentityReducer from "./link_oauth_identity_reducer";
import MarkMessagesCompressedReducer from "./mark_messages_compressed_reducer";
import PauseMissionReducer from "./pause_mission_reducer";
import PruneCaptainMessagesReducer from "./prune_captain_messages_reducer";
import PruneExecutionMemoryReducer from "./prune_execution_memory_reducer";
import PruneKnowledgeEmbeddingsReducer from "./prune_knowledge_embeddings_reducer";
import QueueProposalReducer from "./queue_proposal_reducer";
import RecordApprovalDecisionReducer from "./record_approval_decision_reducer";
import RecordBillingEventReducer from "./record_billing_event_reducer";
import RecordConsentReducer from "./record_consent_reducer";
import RecordDrexDecisionReducer from "./record_drex_decision_reducer";
import RecordDrexFailureReducer from "./record_drex_failure_reducer";
import RecordInteractionReducer from "./record_interaction_reducer";
import RecordProposalHeartbeatReducer from "./record_proposal_heartbeat_reducer";
import RecordRouteDecisionReducer from "./record_route_decision_reducer";
import RecordRunReducer from "./record_run_reducer";
import RegisterArtifactReducer from "./register_artifact_reducer";
import RegisterDiscordChannelReducer from "./register_discord_channel_reducer";
import RejectProposalReducer from "./reject_proposal_reducer";
import RenewCapabilityLeaseReducer from "./renew_capability_lease_reducer";
import RequeueProposalReducer from "./requeue_proposal_reducer";
import ResolveCaptainFocusReducer from "./resolve_captain_focus_reducer";
import ResumeMissionReducer from "./resume_mission_reducer";
import RevokeCapabilityChainReducer from "./revoke_capability_chain_reducer";
import RevokeCapabilityLeaseReducer from "./revoke_capability_lease_reducer";
import RevokeProviderCredentialReducer from "./revoke_provider_credential_reducer";
import SetNodeStatusReducer from "./set_node_status_reducer";
import StartCellRunReducer from "./start_cell_run_reducer";
import StoreProviderCredentialReducer from "./store_provider_credential_reducer";
import UpdateModelTierStatsReducer from "./update_model_tier_stats_reducer";
import UpdatePodHeartbeatReducer from "./update_pod_heartbeat_reducer";
import UpdateTaskDispatchStatusReducer from "./update_task_dispatch_status_reducer";
import UpdateUserSeenReducer from "./update_user_seen_reducer";
import UpsertAgentRegistryReducer from "./upsert_agent_registry_reducer";
import UpsertBattlefieldReducer from "./upsert_battlefield_reducer";
import UpsertCaptainFocusReducer from "./upsert_captain_focus_reducer";
import UpsertDiscordUserReducer from "./upsert_discord_user_reducer";
import UpsertGpuSlotReducer from "./upsert_gpu_slot_reducer";
import UpsertLivenessStateReducer from "./upsert_liveness_state_reducer";
import UpsertModelTierReducer from "./upsert_model_tier_reducer";
import UpsertNodeHeartbeatReducer from "./upsert_node_heartbeat_reducer";
import UpsertNodeRegistryReducer from "./upsert_node_registry_reducer";
import UpsertPodReducer from "./upsert_pod_reducer";
import UpsertProviderAccountStatusReducer from "./upsert_provider_account_status_reducer";
import UpsertRateGroupStateReducer from "./upsert_rate_group_state_reducer";
import WriteSessionSummaryReducer from "./write_session_summary_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentRegistryRow from "./agent_registry_table";
import ApprovalDecisionsRow from "./approval_decisions_table";
import ApprovalRequestsRow from "./approval_requests_table";
import ArtifactsRow from "./artifacts_table";
import BattlefieldsRow from "./battlefields_table";
import BillingEventsRow from "./billing_events_table";
import CapabilityLeasesRow from "./capability_leases_table";
import CaptainDirectivesRow from "./captain_directives_table";
import CaptainFocusRow from "./captain_focus_table";
import CaptainMessagesRow from "./captain_messages_table";
import CaptainSummariesRow from "./captain_summaries_table";
import CellRunsRow from "./cell_runs_table";
import DiscordChannelsRow from "./discord_channels_table";
import DiscordInteractionsRow from "./discord_interactions_table";
import DiscordUsersRow from "./discord_users_table";
import DrexDecisionsRow from "./drex_decisions_table";
import DrexFailuresRow from "./drex_failures_table";
import EventsRow from "./events_table";
import ExecutionMemoryRow from "./execution_memory_table";
import GpuSlotsRow from "./gpu_slots_table";
import KnowledgeEmbeddingsRow from "./knowledge_embeddings_table";
import LivenessStateRow from "./liveness_state_table";
import MissionStepsRow from "./mission_steps_table";
import MissionsRow from "./missions_table";
import ModelTiersRow from "./model_tiers_table";
import NodeRegistryRow from "./node_registry_table";
import NodesRow from "./nodes_table";
import OauthIdentitiesRow from "./oauth_identities_table";
import PodsRow from "./pods_table";
import ProposalConsentsRow from "./proposal_consents_table";
import ProposalsRow from "./proposals_table";
import ProviderAccountsRow from "./provider_accounts_table";
import ProviderCredentialsRow from "./provider_credentials_table";
import RateGroupStateRow from "./rate_group_state_table";
import RouteDecisionsRow from "./route_decisions_table";
import RunsRow from "./runs_table";
import SessionSummariesRow from "./session_summaries_table";
import TaskDispatchesRow from "./task_dispatches_table";
import TenantTaskViewRow from "./tenant_task_view_table";
import UsersRow from "./users_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent_registry: __table({
    name: 'agent_registry',
    indexes: [
      { name: 'cell_id', algorithm: 'btree', columns: [
        'cellId',
      ] },
    ],
    constraints: [
      { name: 'agent_registry_cell_id_key', constraint: 'unique', columns: ['cellId'] },
    ],
  }, AgentRegistryRow),
  approval_decisions: __table({
    name: 'approval_decisions',
    indexes: [
      { name: 'decision_id', algorithm: 'btree', columns: [
        'decisionId',
      ] },
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
    ],
    constraints: [
      { name: 'approval_decisions_decision_id_key', constraint: 'unique', columns: ['decisionId'] },
    ],
  }, ApprovalDecisionsRow),
  approval_requests: __table({
    name: 'approval_requests',
    indexes: [
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'approval_requests_request_id_key', constraint: 'unique', columns: ['requestId'] },
    ],
  }, ApprovalRequestsRow),
  artifacts: __table({
    name: 'artifacts',
    indexes: [
      { name: 'artifact_id', algorithm: 'btree', columns: [
        'artifactId',
      ] },
      { name: 'artifact_type', algorithm: 'btree', columns: [
        'artifactType',
      ] },
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'lease_id', algorithm: 'btree', columns: [
        'leaseId',
      ] },
      { name: 'mission_id', algorithm: 'btree', columns: [
        'missionId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'run_id', algorithm: 'btree', columns: [
        'runId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'artifacts_artifact_id_key', constraint: 'unique', columns: ['artifactId'] },
    ],
  }, ArtifactsRow),
  battlefields: __table({
    name: 'battlefields',
    indexes: [
      { name: 'battlefield_id', algorithm: 'btree', columns: [
        'battlefieldId',
      ] },
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'last_active_at', algorithm: 'btree', columns: [
        'lastActiveAt',
      ] },
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'battlefields_battlefield_id_key', constraint: 'unique', columns: ['battlefieldId'] },
    ],
  }, BattlefieldsRow),
  billing_events: __table({
    name: 'billing_events',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'event_type', algorithm: 'btree', columns: [
        'eventType',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'billing_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BillingEventsRow),
  capability_leases: __table({
    name: 'capability_leases',
    indexes: [
      { name: 'chain_state', algorithm: 'btree', columns: [
        'chainState',
      ] },
      { name: 'expires_at', algorithm: 'btree', columns: [
        'expiresAt',
      ] },
      { name: 'holder_id', algorithm: 'btree', columns: [
        'holderId',
      ] },
      { name: 'lease_id', algorithm: 'btree', columns: [
        'leaseId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'parent_lease_id', algorithm: 'btree', columns: [
        'parentLeaseId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'capability_leases_lease_id_key', constraint: 'unique', columns: ['leaseId'] },
    ],
  }, CapabilityLeasesRow),
  captain_directives: __table({
    name: 'captain_directives',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'captain_directives_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CaptainDirectivesRow),
  captain_focus: __table({
    name: 'captain_focus',
    indexes: [
      { name: 'focus_id', algorithm: 'btree', columns: [
        'focusId',
      ] },
      { name: 'priority', algorithm: 'btree', columns: [
        'priority',
      ] },
    ],
    constraints: [
      { name: 'captain_focus_focus_id_key', constraint: 'unique', columns: ['focusId'] },
    ],
  }, CaptainFocusRow),
  captain_messages: __table({
    name: 'captain_messages',
    indexes: [
      { name: 'message_id', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
      { name: 'timestamp', algorithm: 'btree', columns: [
        'timestamp',
      ] },
    ],
    constraints: [
      { name: 'captain_messages_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, CaptainMessagesRow),
  captain_summaries: __table({
    name: 'captain_summaries',
    indexes: [
      { name: 'summary_id', algorithm: 'btree', columns: [
        'summaryId',
      ] },
      { name: 'summary_type', algorithm: 'btree', columns: [
        'summaryType',
      ] },
    ],
    constraints: [
      { name: 'captain_summaries_summary_id_key', constraint: 'unique', columns: ['summaryId'] },
    ],
  }, CaptainSummariesRow),
  cell_runs: __table({
    name: 'cell_runs',
    indexes: [
      { name: 'cell_run_id', algorithm: 'btree', columns: [
        'cellRunId',
      ] },
      { name: 'mission_id', algorithm: 'btree', columns: [
        'missionId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'cell_runs_cell_run_id_key', constraint: 'unique', columns: ['cellRunId'] },
    ],
  }, CellRunsRow),
  discord_channels: __table({
    name: 'discord_channels',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'purpose', algorithm: 'btree', columns: [
        'purpose',
      ] },
    ],
    constraints: [
      { name: 'discord_channels_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, DiscordChannelsRow),
  discord_interactions: __table({
    name: 'discord_interactions',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'discord_interactions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DiscordInteractionsRow),
  discord_users: __table({
    name: 'discord_users',
    indexes: [
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'discord_users_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, DiscordUsersRow),
  drex_decisions: __table({
    name: 'drex_decisions',
    indexes: [
      { name: 'active_tier', algorithm: 'btree', columns: [
        'activeTier',
      ] },
      { name: 'created_at_ms', algorithm: 'btree', columns: [
        'createdAtMs',
      ] },
      { name: 'decision_id', algorithm: 'btree', columns: [
        'decisionId',
      ] },
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
      { name: 'task_id', algorithm: 'btree', columns: [
        'taskId',
      ] },
    ],
    constraints: [
      { name: 'drex_decisions_decision_id_key', constraint: 'unique', columns: ['decisionId'] },
    ],
  }, DrexDecisionsRow),
  drex_failures: __table({
    name: 'drex_failures',
    indexes: [
      { name: 'created_at_ms', algorithm: 'btree', columns: [
        'createdAtMs',
      ] },
      { name: 'decision_id', algorithm: 'btree', columns: [
        'decisionId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
    ],
    constraints: [
      { name: 'drex_failures_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DrexFailuresRow),
  events: __table({
    name: 'events',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'event_id', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'event_type', algorithm: 'btree', columns: [
        'eventType',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
    ],
    constraints: [
      { name: 'events_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, EventsRow),
  execution_memory: __table({
    name: 'execution_memory',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'lease_id', algorithm: 'btree', columns: [
        'leaseId',
      ] },
      { name: 'task_dispatch_id', algorithm: 'btree', columns: [
        'taskDispatchId',
      ] },
    ],
    constraints: [
      { name: 'execution_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExecutionMemoryRow),
  gpu_slots: __table({
    name: 'gpu_slots',
    indexes: [
      { name: 'pod_id', algorithm: 'btree', columns: [
        'podId',
      ] },
      { name: 'slot_id', algorithm: 'btree', columns: [
        'slotId',
      ] },
    ],
    constraints: [
      { name: 'gpu_slots_slot_id_key', constraint: 'unique', columns: ['slotId'] },
    ],
  }, GpuSlotsRow),
  knowledge_embeddings: __table({
    name: 'knowledge_embeddings',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'knowledge_embeddings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KnowledgeEmbeddingsRow),
  liveness_state: __table({
    name: 'liveness_state',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
      { name: 'last_changed_at', algorithm: 'btree', columns: [
        'lastChangedAt',
      ] },
    ],
    constraints: [
      { name: 'liveness_state_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, LivenessStateRow),
  mission_steps: __table({
    name: 'mission_steps',
    indexes: [
      { name: 'mission_id', algorithm: 'btree', columns: [
        'missionId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'step_id', algorithm: 'btree', columns: [
        'stepId',
      ] },
    ],
    constraints: [
      { name: 'mission_steps_step_id_key', constraint: 'unique', columns: ['stepId'] },
    ],
  }, MissionStepsRow),
  missions: __table({
    name: 'missions',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'mission_id', algorithm: 'btree', columns: [
        'missionId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'updated_at', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'missions_mission_id_key', constraint: 'unique', columns: ['missionId'] },
    ],
  }, MissionsRow),
  model_tiers: __table({
    name: 'model_tiers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'model_id', algorithm: 'btree', columns: [
        'modelId',
      ] },
    ],
    constraints: [
      { name: 'model_tiers_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'model_tiers_model_id_key', constraint: 'unique', columns: ['modelId'] },
    ],
  }, ModelTiersRow),
  node_registry: __table({
    name: 'node_registry',
    indexes: [
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
    ],
    constraints: [
      { name: 'node_registry_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeRegistryRow),
  nodes: __table({
    name: 'nodes',
    indexes: [
      { name: 'last_seen_at', algorithm: 'btree', columns: [
        'lastSeenAt',
      ] },
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'nodes_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodesRow),
  oauth_identities: __table({
    name: 'oauth_identities',
    indexes: [
      { name: 'identity_id', algorithm: 'btree', columns: [
        'identityId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'oauth_identities_identity_id_key', constraint: 'unique', columns: ['identityId'] },
    ],
  }, OauthIdentitiesRow),
  pods: __table({
    name: 'pods',
    indexes: [
      { name: 'liveness', algorithm: 'btree', columns: [
        'liveness',
      ] },
      { name: 'pod_id', algorithm: 'btree', columns: [
        'podId',
      ] },
    ],
    constraints: [
      { name: 'pods_pod_id_key', constraint: 'unique', columns: ['podId'] },
    ],
  }, PodsRow),
  proposal_consents: __table({
    name: 'proposal_consents',
    indexes: [
      { name: 'consent_id', algorithm: 'btree', columns: [
        'consentId',
      ] },
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
    ],
    constraints: [
      { name: 'proposal_consents_consent_id_key', constraint: 'unique', columns: ['consentId'] },
    ],
  }, ProposalConsentsRow),
  proposals: __table({
    name: 'proposals',
    indexes: [
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'proposals_proposal_id_key', constraint: 'unique', columns: ['proposalId'] },
    ],
  }, ProposalsRow),
  provider_accounts: __table({
    name: 'provider_accounts',
    indexes: [
      { name: 'account_id', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'provider_id', algorithm: 'btree', columns: [
        'providerId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'updated_at', algorithm: 'btree', columns: [
        'updatedAt',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'provider_accounts_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, ProviderAccountsRow),
  provider_credentials: __table({
    name: 'provider_credentials',
    indexes: [
      { name: 'credential_id', algorithm: 'btree', columns: [
        'credentialId',
      ] },
      { name: 'provider_id', algorithm: 'btree', columns: [
        'providerId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'provider_credentials_credential_id_key', constraint: 'unique', columns: ['credentialId'] },
    ],
  }, ProviderCredentialsRow),
  rate_group_state: __table({
    name: 'rate_group_state',
    indexes: [
      { name: 'rate_group', algorithm: 'btree', columns: [
        'rateGroup',
      ] },
    ],
    constraints: [
      { name: 'rate_group_state_rate_group_key', constraint: 'unique', columns: ['rateGroup'] },
    ],
  }, RateGroupStateRow),
  route_decisions: __table({
    name: 'route_decisions',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'drex_decision_id', algorithm: 'btree', columns: [
        'drexDecisionId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
      { name: 'task_id', algorithm: 'btree', columns: [
        'taskId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'route_decisions_request_id_key', constraint: 'unique', columns: ['requestId'] },
    ],
  }, RouteDecisionsRow),
  runs: __table({
    name: 'runs',
    indexes: [
      { name: 'ended_at', algorithm: 'btree', columns: [
        'endedAt',
      ] },
      { name: 'lease_id', algorithm: 'btree', columns: [
        'leaseId',
      ] },
      { name: 'model_id', algorithm: 'btree', columns: [
        'modelId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'proposal_id', algorithm: 'btree', columns: [
        'proposalId',
      ] },
      { name: 'run_id', algorithm: 'btree', columns: [
        'runId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'runs_run_id_key', constraint: 'unique', columns: ['runId'] },
    ],
  }, RunsRow),
  session_summaries: __table({
    name: 'session_summaries',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'node_id', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { name: 'owner_id', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'principal_id', algorithm: 'btree', columns: [
        'principalId',
      ] },
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
      { name: 'summary_id', algorithm: 'btree', columns: [
        'summaryId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'session_summaries_summary_id_key', constraint: 'unique', columns: ['summaryId'] },
    ],
  }, SessionSummariesRow),
  task_dispatches: __table({
    name: 'task_dispatches',
    indexes: [
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'task_id', algorithm: 'btree', columns: [
        'taskId',
      ] },
    ],
    constraints: [
      { name: 'task_dispatches_task_id_key', constraint: 'unique', columns: ['taskId'] },
    ],
  }, TaskDispatchesRow),
  users: __table({
    name: 'users',
    indexes: [
      { name: 'last_seen_at', algorithm: 'btree', columns: [
        'lastSeenAt',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'users_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UsersRow),
  tenant_task_view: __table({
    name: 'tenant_task_view',
    indexes: [
    ],
    constraints: [
    ],
  }, TenantTaskViewRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_approval_request", AddApprovalRequestReducer),
  __reducerSchema("add_proposal", AddProposalReducer),
  __reducerSchema("append_event", AppendEventReducer),
  __reducerSchema("append_mission_step", AppendMissionStepReducer),
  __reducerSchema("approve_proposal", ApproveProposalReducer),
  __reducerSchema("archive_battlefield", ArchiveBattlefieldReducer),
  __reducerSchema("assign_proposal", AssignProposalReducer),
  __reducerSchema("attach_drex_decision_to_route", AttachDrexDecisionToRouteReducer),
  __reducerSchema("claim_proposal", ClaimProposalReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("complete_mission", CompleteMissionReducer),
  __reducerSchema("create_mission", CreateMissionReducer),
  __reducerSchema("create_task_dispatch", CreateTaskDispatchReducer),
  __reducerSchema("create_user", CreateUserReducer),
  __reducerSchema("expire_proposal", ExpireProposalReducer),
  __reducerSchema("fail_mission", FailMissionReducer),
  __reducerSchema("finish_cell_run", FinishCellRunReducer),
  __reducerSchema("insert_captain_directive", InsertCaptainDirectiveReducer),
  __reducerSchema("insert_captain_message", InsertCaptainMessageReducer),
  __reducerSchema("insert_captain_summary", InsertCaptainSummaryReducer),
  __reducerSchema("insert_execution_memory", InsertExecutionMemoryReducer),
  __reducerSchema("insert_knowledge_embedding", InsertKnowledgeEmbeddingReducer),
  __reducerSchema("issue_capability_lease", IssueCapabilityLeaseReducer),
  __reducerSchema("link_oauth_identity", LinkOauthIdentityReducer),
  __reducerSchema("mark_messages_compressed", MarkMessagesCompressedReducer),
  __reducerSchema("pause_mission", PauseMissionReducer),
  __reducerSchema("prune_captain_messages", PruneCaptainMessagesReducer),
  __reducerSchema("prune_execution_memory", PruneExecutionMemoryReducer),
  __reducerSchema("prune_knowledge_embeddings", PruneKnowledgeEmbeddingsReducer),
  __reducerSchema("queue_proposal", QueueProposalReducer),
  __reducerSchema("record_approval_decision", RecordApprovalDecisionReducer),
  __reducerSchema("record_billing_event", RecordBillingEventReducer),
  __reducerSchema("record_consent", RecordConsentReducer),
  __reducerSchema("record_drex_decision", RecordDrexDecisionReducer),
  __reducerSchema("record_drex_failure", RecordDrexFailureReducer),
  __reducerSchema("record_interaction", RecordInteractionReducer),
  __reducerSchema("record_proposal_heartbeat", RecordProposalHeartbeatReducer),
  __reducerSchema("record_route_decision", RecordRouteDecisionReducer),
  __reducerSchema("record_run", RecordRunReducer),
  __reducerSchema("register_artifact", RegisterArtifactReducer),
  __reducerSchema("register_discord_channel", RegisterDiscordChannelReducer),
  __reducerSchema("reject_proposal", RejectProposalReducer),
  __reducerSchema("renew_capability_lease", RenewCapabilityLeaseReducer),
  __reducerSchema("requeue_proposal", RequeueProposalReducer),
  __reducerSchema("resolve_captain_focus", ResolveCaptainFocusReducer),
  __reducerSchema("resume_mission", ResumeMissionReducer),
  __reducerSchema("revoke_capability_chain", RevokeCapabilityChainReducer),
  __reducerSchema("revoke_capability_lease", RevokeCapabilityLeaseReducer),
  __reducerSchema("revoke_provider_credential", RevokeProviderCredentialReducer),
  __reducerSchema("set_node_status", SetNodeStatusReducer),
  __reducerSchema("start_cell_run", StartCellRunReducer),
  __reducerSchema("store_provider_credential", StoreProviderCredentialReducer),
  __reducerSchema("update_model_tier_stats", UpdateModelTierStatsReducer),
  __reducerSchema("update_pod_heartbeat", UpdatePodHeartbeatReducer),
  __reducerSchema("update_task_dispatch_status", UpdateTaskDispatchStatusReducer),
  __reducerSchema("update_user_seen", UpdateUserSeenReducer),
  __reducerSchema("upsert_agent_registry", UpsertAgentRegistryReducer),
  __reducerSchema("upsert_battlefield", UpsertBattlefieldReducer),
  __reducerSchema("upsert_captain_focus", UpsertCaptainFocusReducer),
  __reducerSchema("upsert_discord_user", UpsertDiscordUserReducer),
  __reducerSchema("upsert_gpu_slot", UpsertGpuSlotReducer),
  __reducerSchema("upsert_liveness_state", UpsertLivenessStateReducer),
  __reducerSchema("upsert_model_tier", UpsertModelTierReducer),
  __reducerSchema("upsert_node_heartbeat", UpsertNodeHeartbeatReducer),
  __reducerSchema("upsert_node_registry", UpsertNodeRegistryReducer),
  __reducerSchema("upsert_pod", UpsertPodReducer),
  __reducerSchema("upsert_provider_account_status", UpsertProviderAccountStatusReducer),
  __reducerSchema("upsert_rate_group_state", UpsertRateGroupStateReducer),
  __reducerSchema("write_session_summary", WriteSessionSummaryReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

