// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  identityId: __t.string(),
  userId: __t.string(),
  provider: __t.string(),
  providerUserId: __t.string(),
  username: __t.string(),
  accessTokenEnc: __t.string(),
  refreshTokenEnc: __t.option(__t.string()),
  tokenExpiresAt: __t.option(__t.string()),
  scopesJson: __t.string(),
};
