// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.string().primaryKey().name("node_id"),
  hostname: __t.string(),
  platform: __t.string(),
  capabilitiesJson: __t.string().name("capabilities_json"),
  lastHeartbeat: __t.option(__t.string()).name("last_heartbeat"),
  status: __t.string(),
});
