// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identityId: __t.string().primaryKey().name("identity_id"),
  userId: __t.string().name("user_id"),
  provider: __t.string(),
  providerUserId: __t.string().name("provider_user_id"),
  username: __t.string(),
  accessTokenEnc: __t.string().name("access_token_enc"),
  refreshTokenEnc: __t.option(__t.string()).name("refresh_token_enc"),
  tokenExpiresAt: __t.option(__t.string()).name("token_expires_at"),
  scopesJson: __t.string().name("scopes_json"),
  createdAt: __t.string().name("created_at"),
  updatedAt: __t.string().name("updated_at"),
});
