// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  podId: __t.string().primaryKey().name("pod_id"),
  hostIdentity: __t.string().name("host_identity"),
  provider: __t.string(),
  runtimeCapabilities: __t.array(__t.string()).name("runtime_capabilities"),
  trustTier: __t.string().name("trust_tier"),
  privacyFloor: __t.string().name("privacy_floor"),
  gpuInventory: __t.array(__t.string()).name("gpu_inventory"),
  liveness: __t.string(),
  leaseable: __t.bool(),
  registeredAt: __t.string().name("registered_at"),
  lastHeartbeat: __t.string().name("last_heartbeat"),
});
