// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accountId: __t.string().primaryKey().name("account_id"),
  providerId: __t.string().name("provider_id"),
  nodeId: __t.string().name("node_id"),
  authKind: __t.string().name("auth_kind"),
  localHandleRef: __t.string().name("local_handle_ref"),
  status: __t.string(),
  displayName: __t.option(__t.string()).name("display_name"),
  defaultModel: __t.option(__t.string()).name("default_model"),
  rateGroup: __t.string().name("rate_group"),
  availableModelsJson: __t.string().name("available_models_json"),
  lastValidatedAt: __t.option(__t.string()).name("last_validated_at"),
  lastError: __t.option(__t.string()).name("last_error"),
  updatedAt: __t.string().name("updated_at"),
  userId: __t.option(__t.string()).name("user_id"),
});
