// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  runId: __t.string(),
  proposalId: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
  status: __t.string(),
  chainResultJson: __t.string(),
  signalsJson: __t.string(),
  artifactIndexJson: __t.string(),
  nodeId: __t.string(),
  replayReceiptJson: __t.string(),
  mode: __t.string(),
  modelId: __t.string(),
  tokensInput: __t.i64(),
  tokensOutput: __t.i64(),
  tokensTotal: __t.i64(),
  cost: __t.f64(),
};
