// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  failureId: __t.string(),
  runId: __t.string(),
  leaseId: __t.string(),
  sessionId: __t.string(),
  failureCode: __t.string(),
  failureMessage: __t.string(),
  failureType: __t.string(),
  retryable: __t.bool(),
  detailsJson: __t.string(),
};
