// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  artifactId: __t.string(),
  leaseId: __t.option(__t.string()),
  userId: __t.string(),
  missionId: __t.string(),
  cellRunId: __t.option(__t.string()),
  artifactType: __t.string(),
  title: __t.string(),
  uri: __t.option(__t.string()),
  path: __t.option(__t.string()),
  contentJson: __t.string(),
  createdAt: __t.string(),
};
