// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  userId: __t.string().name("user_id"),
  proposalId: __t.string().name("proposal_id"),
  leaseId: __t.string().name("lease_id"),
  startedAt: __t.string().name("started_at"),
  endedAt: __t.string().name("ended_at"),
  status: __t.string(),
  chainResultJson: __t.string().name("chain_result_json"),
  signalsJson: __t.string().name("signals_json"),
  artifactIndexJson: __t.string().name("artifact_index_json"),
  nodeId: __t.string().name("node_id"),
  replayReceiptJson: __t.string().name("replay_receipt_json"),
  mode: __t.string(),
  modelId: __t.string().name("model_id"),
  tokensInput: __t.i64().name("tokens_input"),
  tokensOutput: __t.i64().name("tokens_output"),
  tokensTotal: __t.i64().name("tokens_total"),
  cost: __t.f64(),
});
