// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  summaryId: __t.string().primaryKey().name("summary_id"),
  sessionId: __t.string().name("session_id"),
  nodeId: __t.string().name("node_id"),
  createdAt: __t.string().name("created_at"),
  summaryText: __t.string().name("summary_text"),
  metadataJson: __t.string().name("metadata_json"),
  userId: __t.option(__t.string()).name("user_id"),
  ownerId: __t.option(__t.string()).name("owner_id"),
  principalId: __t.option(__t.string()).name("principal_id"),
});
