// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  cellRunId: __t.string(),
  userId: __t.string(),
  missionId: __t.string(),
  stepId: __t.option(__t.string()),
  status: __t.string(),
  cellId: __t.string(),
  cellRole: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  rateGroup: __t.string(),
  tool: __t.string(),
  startedAt: __t.string(),
  tokensInput: __t.i64(),
  tokensOutput: __t.i64(),
  tokensTotal: __t.i64(),
  outputSummary: __t.option(__t.string()),
};
