// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  taskId: __t.string().primaryKey().name("task_id"),
  parentTaskId: __t.option(__t.string()).name("parent_task_id"),
  intentClass: __t.string().name("intent_class"),
  riskLevel: __t.string().name("risk_level"),
  assignedModel: __t.string().name("assigned_model"),
  effortKnob: __t.string().name("effort_knob"),
  assignedCell: __t.string().name("assigned_cell"),
  budgetMaxTurns: __t.u8().name("budget_max_turns"),
  budgetMaxSeconds: __t.u32().name("budget_max_seconds"),
  fallbackModel: __t.string().name("fallback_model"),
  sandboxMode: __t.string().name("sandbox_mode"),
  toolsAllowedJson: __t.string().name("tools_allowed_json"),
  contextFilesJson: __t.string().name("context_files_json"),
  status: __t.string(),
  resultSummary: __t.string().name("result_summary"),
  tokensUsed: __t.u32().name("tokens_used"),
  latencyMs: __t.u64().name("latency_ms"),
  createdAt: __t.string().name("created_at"),
  completedAt: __t.string().name("completed_at"),
});
