// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DiscordChannel = __t.object("DiscordChannel", {
  channelId: __t.u64(),
  name: __t.string(),
  purpose: __t.string(),
  metadataJson: __t.string(),
});
export type DiscordChannel = __Infer<typeof DiscordChannel>;

export const DiscordInteraction = __t.object("DiscordInteraction", {
  id: __t.u64(),
  userId: __t.u64(),
  channelId: __t.u64(),
  intentClass: __t.string(),
  timestamp: __t.u64(),
});
export type DiscordInteraction = __Infer<typeof DiscordInteraction>;

export const DiscordUser = __t.object("DiscordUser", {
  userId: __t.u64(),
  username: __t.string(),
  trustScore: __t.f32(),
  lastSeenAt: __t.u64(),
});
export type DiscordUser = __Infer<typeof DiscordUser>;

export const LivenessState = __t.object("LivenessState", {
  key: __t.string(),
  lastState: __t.string(),
  lastChangedAt: __t.string(),
});
export type LivenessState = __Infer<typeof LivenessState>;

export const NodeStatus = __t.object("NodeStatus", {
  nodeId: __t.string(),
  lastHeartbeatAt: __t.string(),
  firstSeenAt: __t.string(),
  lastSeenAt: __t.string(),
  status: __t.string(),
  metaJson: __t.string(),
  capabilitiesJson: __t.string(),
  agentVersion: __t.string(),
  tagsJson: __t.string(),
  maxConcurrency: __t.i64(),
});
export type NodeStatus = __Infer<typeof NodeStatus>;

export const OrganizationTask = __t.object("OrganizationTask", {
  id: __t.u64(),
  tenantId: __t.identity(),
  payload: __t.string(),
  status: __t.string(),
  assignedWorker: __t.option(__t.string()),
});
export type OrganizationTask = __Infer<typeof OrganizationTask>;

export const RouteDecision = __t.object("RouteDecision", {
  requestId: __t.string(),
  taskId: __t.string(),
  envelopeVersion: __t.string(),
  rawText: __t.string(),
  sourceSurface: __t.string(),
  intentClass: __t.string(),
  riskLevel: __t.string(),
  privacyLevel: __t.string(),
  computeClass: __t.i64(),
  assignedWorker: __t.string(),
  targetTool: __t.string(),
  targetModel: __t.string(),
  targetRuntime: __t.string(),
  targetTier: __t.string(),
  requiresApproval: __t.bool(),
  rationale: __t.string(),
  confidence: __t.f64(),
  gatewayTransport: __t.string(),
  createdAt: __t.string(),
});
export type RouteDecision = __Infer<typeof RouteDecision>;

export const RunRecord = __t.object("RunRecord", {
  runId: __t.string(),
  proposalId: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
  status: __t.string(),
  chainResultJson: __t.string(),
  signalsJson: __t.string(),
  artifactIndexJson: __t.string(),
  nodeId: __t.string(),
  replayReceiptJson: __t.string(),
  mode: __t.string(),
  modelId: __t.string(),
  tokensInput: __t.i64(),
  tokensOutput: __t.i64(),
  tokensTotal: __t.i64(),
  cost: __t.f64(),
});
export type RunRecord = __Infer<typeof RunRecord>;

