// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  nodeId: __t.string(),
  instanceId: __t.string(),
  runtime: __t.string(),
  runtimeVersion: __t.string(),
  workerVersion: __t.string(),
  protocol: __t.string(),
  capabilitiesJson: __t.string(),
  metadataJson: __t.string(),
  maxConcurrency: __t.i64(),
  activeTasks: __t.u32(),
  status: __t.string(),
  load: __t.f64(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
  expiresAt: __t.string(),
  lastSeenAt: __t.string(),
  closedAt: __t.option(__t.string()),
  currentTaskId: __t.option(__t.string()),
  leaseId: __t.option(__t.string()),
};
