// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  modelId: __t.string(),
  providerModelId: __t.string(),
  provider: __t.string(),
  rateGroup: __t.string(),
  capabilityClass: __t.u8(),
  effortKnob: __t.string(),
  effortLevel: __t.u8(),
  costPerTurn: __t.f64(),
  maxContextTokens: __t.u32(),
  strengthsJson: __t.string(),
  vramRequirementMb: __t.u32(),
  quantizationType: __t.string(),
  kvCacheStrategy: __t.string(),
  enabled: __t.bool(),
};
