// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  accountId: __t.string(),
  providerId: __t.string(),
  nodeId: __t.string(),
  authKind: __t.string(),
  localHandleRef: __t.string(),
  status: __t.string(),
  displayName: __t.option(__t.string()),
  defaultModel: __t.option(__t.string()),
  rateGroup: __t.string(),
  availableModelsJson: __t.string(),
  lastValidatedAt: __t.option(__t.string()),
  lastError: __t.option(__t.string()),
  updatedAt: __t.string(),
  userId: __t.option(__t.string()),
};
