// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  displayName: __t.string().name("display_name"),
  email: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  status: __t.string(),
  tier: __t.string(),
  createdAt: __t.string().name("created_at"),
  lastSeenAt: __t.string().name("last_seen_at"),
  metadataJson: __t.string().name("metadata_json"),
});
