// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddProposalArgs {
    pub proposal_id: String,
    pub created_at: String,
    pub status: String,
    pub fingerprint: Option<String>,
    pub payload: String,
    pub payload_raw: Option<String>,
    pub mode: String,
    pub execution_targeting: Option<String>,
    pub assigned_node_id: Option<String>,
    pub hub_signature: Option<String>,
    pub assignment_expires_at: Option<String>,
    pub attempt_count: i64,
    pub proposal_hash: Option<String>,
    pub approved_at: Option<String>,
    pub expires_at: Option<String>,
    pub eligibility_snapshot: Option<String>,
    pub user_id: Option<String>,
}

impl From<AddProposalArgs> for super::Reducer {
    fn from(args: AddProposalArgs) -> Self {
        Self::AddProposal {
            proposal_id: args.proposal_id,
            created_at: args.created_at,
            status: args.status,
            fingerprint: args.fingerprint,
            payload: args.payload,
            payload_raw: args.payload_raw,
            mode: args.mode,
            execution_targeting: args.execution_targeting,
            assigned_node_id: args.assigned_node_id,
            hub_signature: args.hub_signature,
            assignment_expires_at: args.assignment_expires_at,
            attempt_count: args.attempt_count,
            proposal_hash: args.proposal_hash,
            approved_at: args.approved_at,
            expires_at: args.expires_at,
            eligibility_snapshot: args.eligibility_snapshot,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for AddProposalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_proposal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_proposal {
    /// Request that the remote module invoke the reducer `add_proposal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_proposal:add_proposal_then`] to run a callback after the reducer completes.
    fn add_proposal(
        &self,
        proposal_id: String,
        created_at: String,
        status: String,
        fingerprint: Option<String>,
        payload: String,
        payload_raw: Option<String>,
        mode: String,
        execution_targeting: Option<String>,
        assigned_node_id: Option<String>,
        hub_signature: Option<String>,
        assignment_expires_at: Option<String>,
        attempt_count: i64,
        proposal_hash: Option<String>,
        approved_at: Option<String>,
        expires_at: Option<String>,
        eligibility_snapshot: Option<String>,
        user_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.add_proposal_then(
            proposal_id,
            created_at,
            status,
            fingerprint,
            payload,
            payload_raw,
            mode,
            execution_targeting,
            assigned_node_id,
            hub_signature,
            assignment_expires_at,
            attempt_count,
            proposal_hash,
            approved_at,
            expires_at,
            eligibility_snapshot,
            user_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `add_proposal` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_proposal_then(
        &self,
        proposal_id: String,
        created_at: String,
        status: String,
        fingerprint: Option<String>,
        payload: String,
        payload_raw: Option<String>,
        mode: String,
        execution_targeting: Option<String>,
        assigned_node_id: Option<String>,
        hub_signature: Option<String>,
        assignment_expires_at: Option<String>,
        attempt_count: i64,
        proposal_hash: Option<String>,
        approved_at: Option<String>,
        expires_at: Option<String>,
        eligibility_snapshot: Option<String>,
        user_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_proposal for super::RemoteReducers {
    fn add_proposal_then(
        &self,
        proposal_id: String,
        created_at: String,
        status: String,
        fingerprint: Option<String>,
        payload: String,
        payload_raw: Option<String>,
        mode: String,
        execution_targeting: Option<String>,
        assigned_node_id: Option<String>,
        hub_signature: Option<String>,
        assignment_expires_at: Option<String>,
        attempt_count: i64,
        proposal_hash: Option<String>,
        approved_at: Option<String>,
        expires_at: Option<String>,
        eligibility_snapshot: Option<String>,
        user_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddProposalArgs {
                proposal_id,
                created_at,
                status,
                fingerprint,
                payload,
                payload_raw,
                mode,
                execution_targeting,
                assigned_node_id,
                hub_signature,
                assignment_expires_at,
                attempt_count,
                proposal_hash,
                approved_at,
                expires_at,
                eligibility_snapshot,
                user_id,
            },
            callback,
        )
    }
}
