// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendMissionStepArgs {
    pub step_id: String,
    pub mission_id: String,
    pub position: i64,
    pub status: String,
    pub step_kind: String,
    pub cell_role: String,
    pub title: String,
    pub detail: Option<String>,
    pub input_json: String,
    pub output_json: String,
    pub created_at: String,
    pub updated_at: String,
}

impl From<AppendMissionStepArgs> for super::Reducer {
    fn from(args: AppendMissionStepArgs) -> Self {
        Self::AppendMissionStep {
            step_id: args.step_id,
            mission_id: args.mission_id,
            position: args.position,
            status: args.status,
            step_kind: args.step_kind,
            cell_role: args.cell_role,
            title: args.title,
            detail: args.detail,
            input_json: args.input_json,
            output_json: args.output_json,
            created_at: args.created_at,
            updated_at: args.updated_at,
        }
    }
}

impl __sdk::InModule for AppendMissionStepArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_mission_step`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_mission_step {
    /// Request that the remote module invoke the reducer `append_mission_step` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_mission_step:append_mission_step_then`] to run a callback after the reducer completes.
    fn append_mission_step(
        &self,
        step_id: String,
        mission_id: String,
        position: i64,
        status: String,
        step_kind: String,
        cell_role: String,
        title: String,
        detail: Option<String>,
        input_json: String,
        output_json: String,
        created_at: String,
        updated_at: String,
    ) -> __sdk::Result<()> {
        self.append_mission_step_then(
            step_id,
            mission_id,
            position,
            status,
            step_kind,
            cell_role,
            title,
            detail,
            input_json,
            output_json,
            created_at,
            updated_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `append_mission_step` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_mission_step_then(
        &self,
        step_id: String,
        mission_id: String,
        position: i64,
        status: String,
        step_kind: String,
        cell_role: String,
        title: String,
        detail: Option<String>,
        input_json: String,
        output_json: String,
        created_at: String,
        updated_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_mission_step for super::RemoteReducers {
    fn append_mission_step_then(
        &self,
        step_id: String,
        mission_id: String,
        position: i64,
        status: String,
        step_kind: String,
        cell_role: String,
        title: String,
        detail: Option<String>,
        input_json: String,
        output_json: String,
        created_at: String,
        updated_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendMissionStepArgs {
                step_id,
                mission_id,
                position,
                status,
                step_kind,
                cell_role,
                title,
                detail,
                input_json,
                output_json,
                created_at,
                updated_at,
            },
            callback,
        )
    }
}
