// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::approval_request_type::ApprovalRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `approval_requests`.
///
/// Obtain a handle from the [`ApprovalRequestsTableAccess::approval_requests`] method on [`super::RemoteTables`],
/// like `ctx.db.approval_requests()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.approval_requests().on_insert(...)`.
pub struct ApprovalRequestsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ApprovalRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `approval_requests`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ApprovalRequestsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ApprovalRequestsTableHandle`], which mediates access to the table `approval_requests`.
    fn approval_requests(&self) -> ApprovalRequestsTableHandle<'_>;
}

impl ApprovalRequestsTableAccess for super::RemoteTables {
    fn approval_requests(&self) -> ApprovalRequestsTableHandle<'_> {
        ApprovalRequestsTableHandle {
            imp: self.imp.get_table::<ApprovalRequest>("approval_requests"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ApprovalRequestsInsertCallbackId(__sdk::CallbackId);
pub struct ApprovalRequestsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ApprovalRequestsTableHandle<'ctx> {
    type Row = ApprovalRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ApprovalRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ApprovalRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ApprovalRequestsInsertCallbackId {
        ApprovalRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ApprovalRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ApprovalRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ApprovalRequestsDeleteCallbackId {
        ApprovalRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ApprovalRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ApprovalRequestsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ApprovalRequestsTableHandle<'ctx> {
    type UpdateCallbackId = ApprovalRequestsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ApprovalRequestsUpdateCallbackId {
        ApprovalRequestsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ApprovalRequestsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `request_id` unique index on the table `approval_requests`,
/// which allows point queries on the field of the same name
/// via the [`ApprovalRequestsRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.approval_requests().request_id().find(...)`.
pub struct ApprovalRequestsRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ApprovalRequest, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ApprovalRequestsTableHandle<'ctx> {
    /// Get a handle on the `request_id` unique index on the table `approval_requests`.
    pub fn request_id(&self) -> ApprovalRequestsRequestIdUnique<'ctx> {
        ApprovalRequestsRequestIdUnique {
            imp: self.imp.get_unique_constraint::<String>("request_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ApprovalRequestsRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `request_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ApprovalRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ApprovalRequest>("approval_requests");
    _table.add_unique_constraint::<String>("request_id", |row| &row.request_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ApprovalRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ApprovalRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ApprovalRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait approval_requestsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ApprovalRequest`.
    fn approval_requests(&self) -> __sdk::__query_builder::Table<ApprovalRequest>;
}

impl approval_requestsQueryTableAccess for __sdk::QueryTableAccessor {
    fn approval_requests(&self) -> __sdk::__query_builder::Table<ApprovalRequest> {
        __sdk::__query_builder::Table::new("approval_requests")
    }
}
