// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApprovalDecision {
    pub decision_id: String,
    pub request_id: String,
    pub proposal_id: String,
    pub actor_type: String,
    pub actor_id: String,
    pub decision: String,
    pub reason: Option<String>,
    pub created_at: String,
    pub metadata_json: String,
}

impl __sdk::InModule for ApprovalDecision {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApprovalDecision`.
///
/// Provides typed access to columns for query building.
pub struct ApprovalDecisionCols {
    pub decision_id: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub request_id: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub proposal_id: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub actor_type: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub actor_id: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub decision: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub reason: __sdk::__query_builder::Col<ApprovalDecision, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<ApprovalDecision, String>,
    pub metadata_json: __sdk::__query_builder::Col<ApprovalDecision, String>,
}

impl __sdk::__query_builder::HasCols for ApprovalDecision {
    type Cols = ApprovalDecisionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApprovalDecisionCols {
            decision_id: __sdk::__query_builder::Col::new(table_name, "decision_id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            proposal_id: __sdk::__query_builder::Col::new(table_name, "proposal_id"),
            actor_type: __sdk::__query_builder::Col::new(table_name, "actor_type"),
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            decision: __sdk::__query_builder::Col::new(table_name, "decision"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            metadata_json: __sdk::__query_builder::Col::new(table_name, "metadata_json"),
        }
    }
}

/// Indexed column accessor struct for the table `ApprovalDecision`.
///
/// Provides typed access to indexed columns for query building.
pub struct ApprovalDecisionIxCols {
    pub decision_id: __sdk::__query_builder::IxCol<ApprovalDecision, String>,
    pub proposal_id: __sdk::__query_builder::IxCol<ApprovalDecision, String>,
    pub request_id: __sdk::__query_builder::IxCol<ApprovalDecision, String>,
}

impl __sdk::__query_builder::HasIxCols for ApprovalDecision {
    type IxCols = ApprovalDecisionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ApprovalDecisionIxCols {
            decision_id: __sdk::__query_builder::IxCol::new(table_name, "decision_id"),
            proposal_id: __sdk::__query_builder::IxCol::new(table_name, "proposal_id"),
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ApprovalDecision {}
