// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ArtifactRecord {
    pub artifact_id: String,
    pub mission_id: String,
    pub run_id: Option<String>,
    pub cell_run_id: Option<String>,
    pub artifact_type: String,
    pub title: String,
    pub uri: Option<String>,
    pub path: Option<String>,
    pub content_json: String,
    pub created_at: String,
    pub lease_id: Option<String>,
    pub user_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl __sdk::InModule for ArtifactRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ArtifactRecord`.
///
/// Provides typed access to columns for query building.
pub struct ArtifactRecordCols {
    pub artifact_id: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub mission_id: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub run_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub cell_run_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub artifact_type: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub title: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub uri: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub path: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub content_json: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub created_at: __sdk::__query_builder::Col<ArtifactRecord, String>,
    pub lease_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub user_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub owner_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::Col<ArtifactRecord, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ArtifactRecord {
    type Cols = ArtifactRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ArtifactRecordCols {
            artifact_id: __sdk::__query_builder::Col::new(table_name, "artifact_id"),
            mission_id: __sdk::__query_builder::Col::new(table_name, "mission_id"),
            run_id: __sdk::__query_builder::Col::new(table_name, "run_id"),
            cell_run_id: __sdk::__query_builder::Col::new(table_name, "cell_run_id"),
            artifact_type: __sdk::__query_builder::Col::new(table_name, "artifact_type"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            uri: __sdk::__query_builder::Col::new(table_name, "uri"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            content_json: __sdk::__query_builder::Col::new(table_name, "content_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::Col::new(table_name, "principal_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ArtifactRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct ArtifactRecordIxCols {
    pub artifact_id: __sdk::__query_builder::IxCol<ArtifactRecord, String>,
    pub artifact_type: __sdk::__query_builder::IxCol<ArtifactRecord, String>,
    pub created_at: __sdk::__query_builder::IxCol<ArtifactRecord, String>,
    pub lease_id: __sdk::__query_builder::IxCol<ArtifactRecord, Option<String>>,
    pub mission_id: __sdk::__query_builder::IxCol<ArtifactRecord, String>,
    pub owner_id: __sdk::__query_builder::IxCol<ArtifactRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::IxCol<ArtifactRecord, Option<String>>,
    pub run_id: __sdk::__query_builder::IxCol<ArtifactRecord, Option<String>>,
    pub user_id: __sdk::__query_builder::IxCol<ArtifactRecord, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for ArtifactRecord {
    type IxCols = ArtifactRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ArtifactRecordIxCols {
            artifact_id: __sdk::__query_builder::IxCol::new(table_name, "artifact_id"),
            artifact_type: __sdk::__query_builder::IxCol::new(table_name, "artifact_type"),
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            mission_id: __sdk::__query_builder::IxCol::new(table_name, "mission_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::IxCol::new(table_name, "principal_id"),
            run_id: __sdk::__query_builder::IxCol::new(table_name, "run_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ArtifactRecord {}
