// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BattlefieldRecord {
    pub battlefield_id: String,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
    pub name: String,
    pub repo_url: Option<String>,
    pub root_path: Option<String>,
    pub node_id: Option<String>,
    pub status: String,
    pub created_at: String,
    pub last_active_at: String,
}

impl __sdk::InModule for BattlefieldRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BattlefieldRecord`.
///
/// Provides typed access to columns for query building.
pub struct BattlefieldRecordCols {
    pub battlefield_id: __sdk::__query_builder::Col<BattlefieldRecord, String>,
    pub owner_id: __sdk::__query_builder::Col<BattlefieldRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::Col<BattlefieldRecord, Option<String>>,
    pub name: __sdk::__query_builder::Col<BattlefieldRecord, String>,
    pub repo_url: __sdk::__query_builder::Col<BattlefieldRecord, Option<String>>,
    pub root_path: __sdk::__query_builder::Col<BattlefieldRecord, Option<String>>,
    pub node_id: __sdk::__query_builder::Col<BattlefieldRecord, Option<String>>,
    pub status: __sdk::__query_builder::Col<BattlefieldRecord, String>,
    pub created_at: __sdk::__query_builder::Col<BattlefieldRecord, String>,
    pub last_active_at: __sdk::__query_builder::Col<BattlefieldRecord, String>,
}

impl __sdk::__query_builder::HasCols for BattlefieldRecord {
    type Cols = BattlefieldRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BattlefieldRecordCols {
            battlefield_id: __sdk::__query_builder::Col::new(table_name, "battlefield_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::Col::new(table_name, "principal_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            repo_url: __sdk::__query_builder::Col::new(table_name, "repo_url"),
            root_path: __sdk::__query_builder::Col::new(table_name, "root_path"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_active_at: __sdk::__query_builder::Col::new(table_name, "last_active_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BattlefieldRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct BattlefieldRecordIxCols {
    pub battlefield_id: __sdk::__query_builder::IxCol<BattlefieldRecord, String>,
    pub created_at: __sdk::__query_builder::IxCol<BattlefieldRecord, String>,
    pub last_active_at: __sdk::__query_builder::IxCol<BattlefieldRecord, String>,
    pub node_id: __sdk::__query_builder::IxCol<BattlefieldRecord, Option<String>>,
    pub owner_id: __sdk::__query_builder::IxCol<BattlefieldRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::IxCol<BattlefieldRecord, Option<String>>,
    pub status: __sdk::__query_builder::IxCol<BattlefieldRecord, String>,
}

impl __sdk::__query_builder::HasIxCols for BattlefieldRecord {
    type IxCols = BattlefieldRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BattlefieldRecordIxCols {
            battlefield_id: __sdk::__query_builder::IxCol::new(table_name, "battlefield_id"),
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            last_active_at: __sdk::__query_builder::IxCol::new(table_name, "last_active_at"),
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::IxCol::new(table_name, "principal_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BattlefieldRecord {}
