// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BeliefEvidenceLink {
    pub link_id: String,
    pub belief_id: String,
    pub source_id: Option<String>,
    pub page_id: Option<String>,
    pub run_id: Option<String>,
    pub link_type: String,
    pub weight: f64,
    pub created_at: String,
}

impl __sdk::InModule for BeliefEvidenceLink {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BeliefEvidenceLink`.
///
/// Provides typed access to columns for query building.
pub struct BeliefEvidenceLinkCols {
    pub link_id: __sdk::__query_builder::Col<BeliefEvidenceLink, String>,
    pub belief_id: __sdk::__query_builder::Col<BeliefEvidenceLink, String>,
    pub source_id: __sdk::__query_builder::Col<BeliefEvidenceLink, Option<String>>,
    pub page_id: __sdk::__query_builder::Col<BeliefEvidenceLink, Option<String>>,
    pub run_id: __sdk::__query_builder::Col<BeliefEvidenceLink, Option<String>>,
    pub link_type: __sdk::__query_builder::Col<BeliefEvidenceLink, String>,
    pub weight: __sdk::__query_builder::Col<BeliefEvidenceLink, f64>,
    pub created_at: __sdk::__query_builder::Col<BeliefEvidenceLink, String>,
}

impl __sdk::__query_builder::HasCols for BeliefEvidenceLink {
    type Cols = BeliefEvidenceLinkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BeliefEvidenceLinkCols {
            link_id: __sdk::__query_builder::Col::new(table_name, "link_id"),
            belief_id: __sdk::__query_builder::Col::new(table_name, "belief_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            page_id: __sdk::__query_builder::Col::new(table_name, "page_id"),
            run_id: __sdk::__query_builder::Col::new(table_name, "run_id"),
            link_type: __sdk::__query_builder::Col::new(table_name, "link_type"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BeliefEvidenceLink`.
///
/// Provides typed access to indexed columns for query building.
pub struct BeliefEvidenceLinkIxCols {
    pub belief_id: __sdk::__query_builder::IxCol<BeliefEvidenceLink, String>,
    pub link_id: __sdk::__query_builder::IxCol<BeliefEvidenceLink, String>,
    pub link_type: __sdk::__query_builder::IxCol<BeliefEvidenceLink, String>,
    pub page_id: __sdk::__query_builder::IxCol<BeliefEvidenceLink, Option<String>>,
    pub source_id: __sdk::__query_builder::IxCol<BeliefEvidenceLink, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for BeliefEvidenceLink {
    type IxCols = BeliefEvidenceLinkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BeliefEvidenceLinkIxCols {
            belief_id: __sdk::__query_builder::IxCol::new(table_name, "belief_id"),
            link_id: __sdk::__query_builder::IxCol::new(table_name, "link_id"),
            link_type: __sdk::__query_builder::IxCol::new(table_name, "link_type"),
            page_id: __sdk::__query_builder::IxCol::new(table_name, "page_id"),
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BeliefEvidenceLink {}
