// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::belief_type::Belief;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `beliefs`.
///
/// Obtain a handle from the [`BeliefsTableAccess::beliefs`] method on [`super::RemoteTables`],
/// like `ctx.db.beliefs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.beliefs().on_insert(...)`.
pub struct BeliefsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Belief>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `beliefs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BeliefsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BeliefsTableHandle`], which mediates access to the table `beliefs`.
    fn beliefs(&self) -> BeliefsTableHandle<'_>;
}

impl BeliefsTableAccess for super::RemoteTables {
    fn beliefs(&self) -> BeliefsTableHandle<'_> {
        BeliefsTableHandle {
            imp: self.imp.get_table::<Belief>("beliefs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BeliefsInsertCallbackId(__sdk::CallbackId);
pub struct BeliefsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BeliefsTableHandle<'ctx> {
    type Row = Belief;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Belief> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BeliefsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BeliefsInsertCallbackId {
        BeliefsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BeliefsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BeliefsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BeliefsDeleteCallbackId {
        BeliefsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BeliefsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BeliefsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BeliefsTableHandle<'ctx> {
    type UpdateCallbackId = BeliefsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BeliefsUpdateCallbackId {
        BeliefsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BeliefsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `belief_id` unique index on the table `beliefs`,
/// which allows point queries on the field of the same name
/// via the [`BeliefsBeliefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.beliefs().belief_id().find(...)`.
pub struct BeliefsBeliefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Belief, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BeliefsTableHandle<'ctx> {
    /// Get a handle on the `belief_id` unique index on the table `beliefs`.
    pub fn belief_id(&self) -> BeliefsBeliefIdUnique<'ctx> {
        BeliefsBeliefIdUnique {
            imp: self.imp.get_unique_constraint::<String>("belief_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BeliefsBeliefIdUnique<'ctx> {
    /// Find the subscribed row whose `belief_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Belief> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Belief>("beliefs");
    _table.add_unique_constraint::<String>("belief_id", |row| &row.belief_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Belief>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Belief>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Belief`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait beliefsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Belief`.
    fn beliefs(&self) -> __sdk::__query_builder::Table<Belief>;
}

impl beliefsQueryTableAccess for __sdk::QueryTableAccessor {
    fn beliefs(&self) -> __sdk::__query_builder::Table<Belief> {
        __sdk::__query_builder::Table::new("beliefs")
    }
}
