// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::captain_directive_type::CaptainDirective;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `captain_directives`.
///
/// Obtain a handle from the [`CaptainDirectivesTableAccess::captain_directives`] method on [`super::RemoteTables`],
/// like `ctx.db.captain_directives()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.captain_directives().on_insert(...)`.
pub struct CaptainDirectivesTableHandle<'ctx> {
    imp: __sdk::TableHandle<CaptainDirective>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `captain_directives`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CaptainDirectivesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CaptainDirectivesTableHandle`], which mediates access to the table `captain_directives`.
    fn captain_directives(&self) -> CaptainDirectivesTableHandle<'_>;
}

impl CaptainDirectivesTableAccess for super::RemoteTables {
    fn captain_directives(&self) -> CaptainDirectivesTableHandle<'_> {
        CaptainDirectivesTableHandle {
            imp: self.imp.get_table::<CaptainDirective>("captain_directives"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CaptainDirectivesInsertCallbackId(__sdk::CallbackId);
pub struct CaptainDirectivesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CaptainDirectivesTableHandle<'ctx> {
    type Row = CaptainDirective;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CaptainDirective> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CaptainDirectivesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CaptainDirectivesInsertCallbackId {
        CaptainDirectivesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CaptainDirectivesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CaptainDirectivesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CaptainDirectivesDeleteCallbackId {
        CaptainDirectivesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CaptainDirectivesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CaptainDirectivesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CaptainDirectivesTableHandle<'ctx> {
    type UpdateCallbackId = CaptainDirectivesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CaptainDirectivesUpdateCallbackId {
        CaptainDirectivesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CaptainDirectivesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `captain_directives`,
/// which allows point queries on the field of the same name
/// via the [`CaptainDirectivesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.captain_directives().id().find(...)`.
pub struct CaptainDirectivesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CaptainDirective, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CaptainDirectivesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `captain_directives`.
    pub fn id(&self) -> CaptainDirectivesIdUnique<'ctx> {
        CaptainDirectivesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CaptainDirectivesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CaptainDirective> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CaptainDirective>("captain_directives");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CaptainDirective>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CaptainDirective>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CaptainDirective`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait captain_directivesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CaptainDirective`.
    fn captain_directives(&self) -> __sdk::__query_builder::Table<CaptainDirective>;
}

impl captain_directivesQueryTableAccess for __sdk::QueryTableAccessor {
    fn captain_directives(&self) -> __sdk::__query_builder::Table<CaptainDirective> {
        __sdk::__query_builder::Table::new("captain_directives")
    }
}
