// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cell_run_record_type::CellRunRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cell_runs`.
///
/// Obtain a handle from the [`CellRunsTableAccess::cell_runs`] method on [`super::RemoteTables`],
/// like `ctx.db.cell_runs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell_runs().on_insert(...)`.
pub struct CellRunsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CellRunRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cell_runs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CellRunsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CellRunsTableHandle`], which mediates access to the table `cell_runs`.
    fn cell_runs(&self) -> CellRunsTableHandle<'_>;
}

impl CellRunsTableAccess for super::RemoteTables {
    fn cell_runs(&self) -> CellRunsTableHandle<'_> {
        CellRunsTableHandle {
            imp: self.imp.get_table::<CellRunRecord>("cell_runs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CellRunsInsertCallbackId(__sdk::CallbackId);
pub struct CellRunsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CellRunsTableHandle<'ctx> {
    type Row = CellRunRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CellRunRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CellRunsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellRunsInsertCallbackId {
        CellRunsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CellRunsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CellRunsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellRunsDeleteCallbackId {
        CellRunsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CellRunsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CellRunsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CellRunsTableHandle<'ctx> {
    type UpdateCallbackId = CellRunsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CellRunsUpdateCallbackId {
        CellRunsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CellRunsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `cell_run_id` unique index on the table `cell_runs`,
/// which allows point queries on the field of the same name
/// via the [`CellRunsCellRunIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell_runs().cell_run_id().find(...)`.
pub struct CellRunsCellRunIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CellRunRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CellRunsTableHandle<'ctx> {
    /// Get a handle on the `cell_run_id` unique index on the table `cell_runs`.
    pub fn cell_run_id(&self) -> CellRunsCellRunIdUnique<'ctx> {
        CellRunsCellRunIdUnique {
            imp: self.imp.get_unique_constraint::<String>("cell_run_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CellRunsCellRunIdUnique<'ctx> {
    /// Find the subscribed row whose `cell_run_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CellRunRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CellRunRecord>("cell_runs");
    _table.add_unique_constraint::<String>("cell_run_id", |row| &row.cell_run_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CellRunRecord>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CellRunRecord>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CellRunRecord`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cell_runsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CellRunRecord`.
    fn cell_runs(&self) -> __sdk::__query_builder::Table<CellRunRecord>;
}

impl cell_runsQueryTableAccess for __sdk::QueryTableAccessor {
    fn cell_runs(&self) -> __sdk::__query_builder::Table<CellRunRecord> {
        __sdk::__query_builder::Table::new("cell_runs")
    }
}
