// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimBeliefVerificationArgs {
    pub schedule_id: String,
    pub run_id: String,
}

impl From<ClaimBeliefVerificationArgs> for super::Reducer {
    fn from(args: ClaimBeliefVerificationArgs) -> Self {
        Self::ClaimBeliefVerification {
            schedule_id: args.schedule_id,
            run_id: args.run_id,
        }
    }
}

impl __sdk::InModule for ClaimBeliefVerificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_belief_verification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_belief_verification {
    /// Request that the remote module invoke the reducer `claim_belief_verification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_belief_verification:claim_belief_verification_then`] to run a callback after the reducer completes.
    fn claim_belief_verification(&self, schedule_id: String, run_id: String) -> __sdk::Result<()> {
        self.claim_belief_verification_then(schedule_id, run_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_belief_verification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_belief_verification_then(
        &self,
        schedule_id: String,
        run_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_belief_verification for super::RemoteReducers {
    fn claim_belief_verification_then(
        &self,
        schedule_id: String,
        run_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimBeliefVerificationArgs {
                schedule_id,
                run_id,
            },
            callback,
        )
    }
}
