// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CompleteBeliefVerificationArgs {
    pub schedule_id: String,
}

impl From<CompleteBeliefVerificationArgs> for super::Reducer {
    fn from(args: CompleteBeliefVerificationArgs) -> Self {
        Self::CompleteBeliefVerification {
            schedule_id: args.schedule_id,
        }
    }
}

impl __sdk::InModule for CompleteBeliefVerificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `complete_belief_verification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait complete_belief_verification {
    /// Request that the remote module invoke the reducer `complete_belief_verification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`complete_belief_verification:complete_belief_verification_then`] to run a callback after the reducer completes.
    fn complete_belief_verification(&self, schedule_id: String) -> __sdk::Result<()> {
        self.complete_belief_verification_then(schedule_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `complete_belief_verification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn complete_belief_verification_then(
        &self,
        schedule_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl complete_belief_verification for super::RemoteReducers {
    fn complete_belief_verification_then(
        &self,
        schedule_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CompleteBeliefVerificationArgs { schedule_id }, callback)
    }
}
