// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CompleteLoopSessionArgs {
    pub loop_id: String,
    pub status: String,
    pub termination_reason: String,
}

impl From<CompleteLoopSessionArgs> for super::Reducer {
    fn from(args: CompleteLoopSessionArgs) -> Self {
        Self::CompleteLoopSession {
            loop_id: args.loop_id,
            status: args.status,
            termination_reason: args.termination_reason,
        }
    }
}

impl __sdk::InModule for CompleteLoopSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait complete_loop_session {
    fn complete_loop_session(
        &self,
        loop_id: String,
        status: String,
        termination_reason: String,
    ) -> __sdk::Result<()> {
        self.complete_loop_session_then(loop_id, status, termination_reason, |_, _| {})
    }

    fn complete_loop_session_then(
        &self,
        loop_id: String,
        status: String,
        termination_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl complete_loop_session for super::RemoteReducers {
    fn complete_loop_session_then(
        &self,
        loop_id: String,
        status: String,
        termination_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CompleteLoopSessionArgs {
                loop_id,
                status,
                termination_reason,
            },
            callback,
        )
    }
}
