// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTreasuryArgs {
    pub treasury_id: String,
    pub scope: String,
    pub provider: String,
    pub account_ref: String,
    pub budget_window_kind: String,
    pub max_requests: i64,
    pub max_tokens_in: i64,
    pub max_tokens_out: i64,
    pub max_cost_millicents: i64,
    pub reserve_fraction: f64,
    pub reserve_policy: String,
    pub degraded_mode_threshold: f64,
}

impl From<CreateTreasuryArgs> for super::Reducer {
    fn from(args: CreateTreasuryArgs) -> Self {
        Self::CreateTreasury {
            treasury_id: args.treasury_id,
            scope: args.scope,
            provider: args.provider,
            account_ref: args.account_ref,
            budget_window_kind: args.budget_window_kind,
            max_requests: args.max_requests,
            max_tokens_in: args.max_tokens_in,
            max_tokens_out: args.max_tokens_out,
            max_cost_millicents: args.max_cost_millicents,
            reserve_fraction: args.reserve_fraction,
            reserve_policy: args.reserve_policy,
            degraded_mode_threshold: args.degraded_mode_threshold,
        }
    }
}

impl __sdk::InModule for CreateTreasuryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_treasury`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_treasury {
    /// Request that the remote module invoke the reducer `create_treasury` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_treasury:create_treasury_then`] to run a callback after the reducer completes.
    fn create_treasury(
        &self,
        treasury_id: String,
        scope: String,
        provider: String,
        account_ref: String,
        budget_window_kind: String,
        max_requests: i64,
        max_tokens_in: i64,
        max_tokens_out: i64,
        max_cost_millicents: i64,
        reserve_fraction: f64,
        reserve_policy: String,
        degraded_mode_threshold: f64,
    ) -> __sdk::Result<()> {
        self.create_treasury_then(
            treasury_id,
            scope,
            provider,
            account_ref,
            budget_window_kind,
            max_requests,
            max_tokens_in,
            max_tokens_out,
            max_cost_millicents,
            reserve_fraction,
            reserve_policy,
            degraded_mode_threshold,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_treasury` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_treasury_then(
        &self,
        treasury_id: String,
        scope: String,
        provider: String,
        account_ref: String,
        budget_window_kind: String,
        max_requests: i64,
        max_tokens_in: i64,
        max_tokens_out: i64,
        max_cost_millicents: i64,
        reserve_fraction: f64,
        reserve_policy: String,
        degraded_mode_threshold: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_treasury for super::RemoteReducers {
    fn create_treasury_then(
        &self,
        treasury_id: String,
        scope: String,
        provider: String,
        account_ref: String,
        budget_window_kind: String,
        max_requests: i64,
        max_tokens_in: i64,
        max_tokens_out: i64,
        max_cost_millicents: i64,
        reserve_fraction: f64,
        reserve_policy: String,
        degraded_mode_threshold: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateTreasuryArgs {
                treasury_id,
                scope,
                provider,
                account_ref,
                budget_window_kind,
                max_requests,
                max_tokens_in,
                max_tokens_out,
                max_cost_millicents,
                reserve_fraction,
                reserve_policy,
                degraded_mode_threshold,
            },
            callback,
        )
    }
}
