// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreatePageArgs {
    pub page_id: String,
    pub namespace: String,
    pub title: String,
    pub slug: String,
    pub body_markdown: String,
    pub summary: String,
    pub topic_keys_json: String,
    pub source_set_hash: String,
    pub owner_scope: String,
    pub generated_by_run_id: Option<String>,
}

impl From<CreatePageArgs> for super::Reducer {
    fn from(args: CreatePageArgs) -> Self {
        Self::CreatePage {
            page_id: args.page_id,
            namespace: args.namespace,
            title: args.title,
            slug: args.slug,
            body_markdown: args.body_markdown,
            summary: args.summary,
            topic_keys_json: args.topic_keys_json,
            source_set_hash: args.source_set_hash,
            owner_scope: args.owner_scope,
            generated_by_run_id: args.generated_by_run_id,
        }
    }
}

impl __sdk::InModule for CreatePageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_page`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_page {
    /// Request that the remote module invoke the reducer `create_page` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_page:create_page_then`] to run a callback after the reducer completes.
    fn create_page(
        &self,
        page_id: String,
        namespace: String,
        title: String,
        slug: String,
        body_markdown: String,
        summary: String,
        topic_keys_json: String,
        source_set_hash: String,
        owner_scope: String,
        generated_by_run_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_page_then(
            page_id,
            namespace,
            title,
            slug,
            body_markdown,
            summary,
            topic_keys_json,
            source_set_hash,
            owner_scope,
            generated_by_run_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_page` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_page_then(
        &self,
        page_id: String,
        namespace: String,
        title: String,
        slug: String,
        body_markdown: String,
        summary: String,
        topic_keys_json: String,
        source_set_hash: String,
        owner_scope: String,
        generated_by_run_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_page for super::RemoteReducers {
    fn create_page_then(
        &self,
        page_id: String,
        namespace: String,
        title: String,
        slug: String,
        body_markdown: String,
        summary: String,
        topic_keys_json: String,
        source_set_hash: String,
        owner_scope: String,
        generated_by_run_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreatePageArgs {
                page_id,
                namespace,
                title,
                slug,
                body_markdown,
                summary,
                topic_keys_json,
                source_set_hash,
                owner_scope,
                generated_by_run_id,
            },
            callback,
        )
    }
}
