// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::device_type::Device;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct DevicesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Device>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait DevicesTableAccess {
    #[allow(non_snake_case)]
    fn devices(&self) -> DevicesTableHandle<'_>;
}

impl DevicesTableAccess for super::RemoteTables {
    fn devices(&self) -> DevicesTableHandle<'_> {
        DevicesTableHandle {
            imp: self.imp.get_table::<Device>("devices"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeviceInsertCallbackId(__sdk::CallbackId);
pub struct DeviceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DevicesTableHandle<'ctx> {
    type Row = Device;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Device> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeviceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeviceInsertCallbackId {
        DeviceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeviceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeviceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeviceDeleteCallbackId {
        DeviceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeviceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DeviceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DevicesTableHandle<'ctx> {
    type UpdateCallbackId = DeviceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeviceUpdateCallbackId {
        DeviceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeviceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct DeviceDeviceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Device, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DevicesTableHandle<'ctx> {
    pub fn device_id(&self) -> DeviceDeviceIdUnique<'ctx> {
        DeviceDeviceIdUnique {
            imp: self.imp.get_unique_constraint::<String>("device_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeviceDeviceIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<Device> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Device>("devices");
    _table.add_unique_constraint::<String>("device_id", |row| &row.device_id);
}

pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Device>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Device>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
