// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventRecord {
    pub event_id: String,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
    pub session_id: Option<String>,
    pub mission_id: Option<String>,
    pub battlefield_id: Option<String>,
    pub event_type: String,
    pub payload_json: String,
    pub created_at: String,
}

impl __sdk::InModule for EventRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EventRecord`.
///
/// Provides typed access to columns for query building.
pub struct EventRecordCols {
    pub event_id: __sdk::__query_builder::Col<EventRecord, String>,
    pub owner_id: __sdk::__query_builder::Col<EventRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::Col<EventRecord, Option<String>>,
    pub session_id: __sdk::__query_builder::Col<EventRecord, Option<String>>,
    pub mission_id: __sdk::__query_builder::Col<EventRecord, Option<String>>,
    pub battlefield_id: __sdk::__query_builder::Col<EventRecord, Option<String>>,
    pub event_type: __sdk::__query_builder::Col<EventRecord, String>,
    pub payload_json: __sdk::__query_builder::Col<EventRecord, String>,
    pub created_at: __sdk::__query_builder::Col<EventRecord, String>,
}

impl __sdk::__query_builder::HasCols for EventRecord {
    type Cols = EventRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventRecordCols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::Col::new(table_name, "principal_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            mission_id: __sdk::__query_builder::Col::new(table_name, "mission_id"),
            battlefield_id: __sdk::__query_builder::Col::new(table_name, "battlefield_id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            payload_json: __sdk::__query_builder::Col::new(table_name, "payload_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `EventRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventRecordIxCols {
    pub created_at: __sdk::__query_builder::IxCol<EventRecord, String>,
    pub event_id: __sdk::__query_builder::IxCol<EventRecord, String>,
    pub event_type: __sdk::__query_builder::IxCol<EventRecord, String>,
    pub owner_id: __sdk::__query_builder::IxCol<EventRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::IxCol<EventRecord, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for EventRecord {
    type IxCols = EventRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventRecordIxCols {
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            event_type: __sdk::__query_builder::IxCol::new(table_name, "event_type"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::IxCol::new(table_name, "principal_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventRecord {}
