// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssueCapabilityLeaseArgs {
    pub lease_id: String,
    pub proposal_id: String,
    pub run_id: Option<String>,
    pub parent_lease_id: Option<String>,
    pub holder_kind: String,
    pub holder_id: String,
    pub tool_scope_json: String,
    pub network_scope_json: String,
    pub filesystem_scope_json: String,
    pub secret_scope_json: String,
    pub privilege_tier: String,
    pub failure_policy: String,
    pub chain_state: String,
    pub routing_lock_json: Option<String>,
    pub status: String,
    pub issued_at: String,
    pub expires_at: String,
    pub hub_signature: String,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<IssueCapabilityLeaseArgs> for super::Reducer {
    fn from(args: IssueCapabilityLeaseArgs) -> Self {
        Self::IssueCapabilityLease {
            lease_id: args.lease_id,
            proposal_id: args.proposal_id,
            run_id: args.run_id,
            parent_lease_id: args.parent_lease_id,
            holder_kind: args.holder_kind,
            holder_id: args.holder_id,
            tool_scope_json: args.tool_scope_json,
            network_scope_json: args.network_scope_json,
            filesystem_scope_json: args.filesystem_scope_json,
            secret_scope_json: args.secret_scope_json,
            privilege_tier: args.privilege_tier,
            failure_policy: args.failure_policy,
            chain_state: args.chain_state,
            routing_lock_json: args.routing_lock_json,
            status: args.status,
            issued_at: args.issued_at,
            expires_at: args.expires_at,
            hub_signature: args.hub_signature,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for IssueCapabilityLeaseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_capability_lease`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_capability_lease {
    /// Request that the remote module invoke the reducer `issue_capability_lease` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_capability_lease:issue_capability_lease_then`] to run a callback after the reducer completes.
    fn issue_capability_lease(
        &self,
        lease_id: String,
        proposal_id: String,
        run_id: Option<String>,
        parent_lease_id: Option<String>,
        holder_kind: String,
        holder_id: String,
        tool_scope_json: String,
        network_scope_json: String,
        filesystem_scope_json: String,
        secret_scope_json: String,
        privilege_tier: String,
        failure_policy: String,
        chain_state: String,
        routing_lock_json: Option<String>,
        status: String,
        issued_at: String,
        expires_at: String,
        hub_signature: String,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.issue_capability_lease_then(
            lease_id,
            proposal_id,
            run_id,
            parent_lease_id,
            holder_kind,
            holder_id,
            tool_scope_json,
            network_scope_json,
            filesystem_scope_json,
            secret_scope_json,
            privilege_tier,
            failure_policy,
            chain_state,
            routing_lock_json,
            status,
            issued_at,
            expires_at,
            hub_signature,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `issue_capability_lease` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_capability_lease_then(
        &self,
        lease_id: String,
        proposal_id: String,
        run_id: Option<String>,
        parent_lease_id: Option<String>,
        holder_kind: String,
        holder_id: String,
        tool_scope_json: String,
        network_scope_json: String,
        filesystem_scope_json: String,
        secret_scope_json: String,
        privilege_tier: String,
        failure_policy: String,
        chain_state: String,
        routing_lock_json: Option<String>,
        status: String,
        issued_at: String,
        expires_at: String,
        hub_signature: String,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_capability_lease for super::RemoteReducers {
    fn issue_capability_lease_then(
        &self,
        lease_id: String,
        proposal_id: String,
        run_id: Option<String>,
        parent_lease_id: Option<String>,
        holder_kind: String,
        holder_id: String,
        tool_scope_json: String,
        network_scope_json: String,
        filesystem_scope_json: String,
        secret_scope_json: String,
        privilege_tier: String,
        failure_policy: String,
        chain_state: String,
        routing_lock_json: Option<String>,
        status: String,
        issued_at: String,
        expires_at: String,
        hub_signature: String,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IssueCapabilityLeaseArgs {
                lease_id,
                proposal_id,
                run_id,
                parent_lease_id,
                holder_kind,
                holder_id,
                tool_scope_json,
                network_scope_json,
                filesystem_scope_json,
                secret_scope_json,
                privilege_tier,
                failure_policy,
                chain_state,
                routing_lock_json,
                status,
                issued_at,
                expires_at,
                hub_signature,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
