// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Lease {
    pub lease_id: String,
    pub task_id: String,
    pub session_id: String,
    pub node_id: String,
    pub capability: String,
    pub status: String,
    pub issued_at: String,
    pub updated_at: String,
    pub expires_at: String,
    pub acked_at: Option<String>,
    pub completed_at: Option<String>,
    pub failure_code: Option<String>,
    pub reason: Option<String>,
}

impl __sdk::InModule for Lease {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Lease`.
///
/// Provides typed access to columns for query building.
pub struct LeaseCols {
    pub lease_id: __sdk::__query_builder::Col<Lease, String>,
    pub task_id: __sdk::__query_builder::Col<Lease, String>,
    pub session_id: __sdk::__query_builder::Col<Lease, String>,
    pub node_id: __sdk::__query_builder::Col<Lease, String>,
    pub capability: __sdk::__query_builder::Col<Lease, String>,
    pub status: __sdk::__query_builder::Col<Lease, String>,
    pub issued_at: __sdk::__query_builder::Col<Lease, String>,
    pub updated_at: __sdk::__query_builder::Col<Lease, String>,
    pub expires_at: __sdk::__query_builder::Col<Lease, String>,
    pub acked_at: __sdk::__query_builder::Col<Lease, Option<String>>,
    pub completed_at: __sdk::__query_builder::Col<Lease, Option<String>>,
    pub failure_code: __sdk::__query_builder::Col<Lease, Option<String>>,
    pub reason: __sdk::__query_builder::Col<Lease, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Lease {
    type Cols = LeaseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LeaseCols {
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            capability: __sdk::__query_builder::Col::new(table_name, "capability"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            issued_at: __sdk::__query_builder::Col::new(table_name, "issued_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            acked_at: __sdk::__query_builder::Col::new(table_name, "acked_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
            failure_code: __sdk::__query_builder::Col::new(table_name, "failure_code"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
        }
    }
}

/// Indexed column accessor struct for the table `Lease`.
///
/// Provides typed access to indexed columns for query building.
pub struct LeaseIxCols {
    pub acked_at: __sdk::__query_builder::IxCol<Lease, Option<String>>,
    pub capability: __sdk::__query_builder::IxCol<Lease, String>,
    pub completed_at: __sdk::__query_builder::IxCol<Lease, Option<String>>,
    pub expires_at: __sdk::__query_builder::IxCol<Lease, String>,
    pub lease_id: __sdk::__query_builder::IxCol<Lease, String>,
    pub node_id: __sdk::__query_builder::IxCol<Lease, String>,
    pub session_id: __sdk::__query_builder::IxCol<Lease, String>,
    pub status: __sdk::__query_builder::IxCol<Lease, String>,
    pub task_id: __sdk::__query_builder::IxCol<Lease, String>,
}

impl __sdk::__query_builder::HasIxCols for Lease {
    type IxCols = LeaseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LeaseIxCols {
            acked_at: __sdk::__query_builder::IxCol::new(table_name, "acked_at"),
            capability: __sdk::__query_builder::IxCol::new(table_name, "capability"),
            completed_at: __sdk::__query_builder::IxCol::new(table_name, "completed_at"),
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            task_id: __sdk::__query_builder::IxCol::new(table_name, "task_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Lease {}
