// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::loop_session_type::LoopSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `loop_sessions`.
///
/// Obtain a handle from the [`LoopSessionsTableAccess::loop_sessions`] method on [`super::RemoteTables`],
/// like `ctx.db.loop_sessions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loop_sessions().on_insert(...)`.
pub struct LoopSessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LoopSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `loop_sessions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LoopSessionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LoopSessionsTableHandle`], which mediates access to the table `loop_sessions`.
    fn loop_sessions(&self) -> LoopSessionsTableHandle<'_>;
}

impl LoopSessionsTableAccess for super::RemoteTables {
    fn loop_sessions(&self) -> LoopSessionsTableHandle<'_> {
        LoopSessionsTableHandle {
            imp: self.imp.get_table::<LoopSession>("loop_sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LoopSessionsInsertCallbackId(__sdk::CallbackId);
pub struct LoopSessionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LoopSessionsTableHandle<'ctx> {
    type Row = LoopSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LoopSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LoopSessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopSessionsInsertCallbackId {
        LoopSessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LoopSessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LoopSessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopSessionsDeleteCallbackId {
        LoopSessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LoopSessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LoopSessionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LoopSessionsTableHandle<'ctx> {
    type UpdateCallbackId = LoopSessionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LoopSessionsUpdateCallbackId {
        LoopSessionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LoopSessionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `loop_id` unique index on the table `loop_sessions`,
/// which allows point queries on the field of the same name
/// via the [`LoopSessionsLoopIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loop_sessions().loop_id().find(...)`.
pub struct LoopSessionsLoopIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LoopSession, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LoopSessionsTableHandle<'ctx> {
    /// Get a handle on the `loop_id` unique index on the table `loop_sessions`.
    pub fn loop_id(&self) -> LoopSessionsLoopIdUnique<'ctx> {
        LoopSessionsLoopIdUnique {
            imp: self.imp.get_unique_constraint::<String>("loop_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LoopSessionsLoopIdUnique<'ctx> {
    /// Find the subscribed row whose `loop_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LoopSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LoopSession>("loop_sessions");
    _table.add_unique_constraint::<String>("loop_id", |row| &row.loop_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LoopSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LoopSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LoopSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait loop_sessionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LoopSession`.
    fn loop_sessions(&self) -> __sdk::__query_builder::Table<LoopSession>;
}

impl loop_sessionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn loop_sessions(&self) -> __sdk::__query_builder::Table<LoopSession> {
        __sdk::__query_builder::Table::new("loop_sessions")
    }
}
