// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::loop_session_type::LoopSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct LoopSessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LoopSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait LoopSessionsTableAccess {
    #[allow(non_snake_case)]
    fn loop_sessions(&self) -> LoopSessionsTableHandle<'_>;
}

impl LoopSessionsTableAccess for super::RemoteTables {
    fn loop_sessions(&self) -> LoopSessionsTableHandle<'_> {
        LoopSessionsTableHandle {
            imp: self.imp.get_table::<LoopSession>("loop_sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LoopSessionInsertCallbackId(__sdk::CallbackId);
pub struct LoopSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LoopSessionsTableHandle<'ctx> {
    type Row = LoopSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LoopSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LoopSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopSessionInsertCallbackId {
        LoopSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LoopSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LoopSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopSessionDeleteCallbackId {
        LoopSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LoopSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LoopSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LoopSessionsTableHandle<'ctx> {
    type UpdateCallbackId = LoopSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LoopSessionUpdateCallbackId {
        LoopSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LoopSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct LoopSessionLoopIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LoopSession, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LoopSessionsTableHandle<'ctx> {
    pub fn loop_id(&self) -> LoopSessionLoopIdUnique<'ctx> {
        LoopSessionLoopIdUnique {
            imp: self.imp.get_unique_constraint::<String>("loop_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LoopSessionLoopIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<LoopSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LoopSession>("loop_sessions");
    _table.add_unique_constraint::<String>("loop_id", |row| &row.loop_id);
}

pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LoopSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LoopSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
