// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LoopSession {
    pub loop_id: String,
    pub user_id: String,
    pub objective: String,
    pub status: String,
    pub max_turns: u32,
    pub max_cost_usd: f64,
    pub current_turn: u32,
    pub total_cost_usd: f64,
    pub termination_reason: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

impl __sdk::InModule for LoopSession {
    type Module = super::RemoteModule;
}
