// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::loop_iteration_type::LoopIteration;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct LoopIterationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LoopIteration>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait LoopIterationsTableAccess {
    #[allow(non_snake_case)]
    fn loop_iterations(&self) -> LoopIterationsTableHandle<'_>;
}

impl LoopIterationsTableAccess for super::RemoteTables {
    fn loop_iterations(&self) -> LoopIterationsTableHandle<'_> {
        LoopIterationsTableHandle {
            imp: self.imp.get_table::<LoopIteration>("loop_iterations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LoopIterationInsertCallbackId(__sdk::CallbackId);
pub struct LoopIterationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LoopIterationsTableHandle<'ctx> {
    type Row = LoopIteration;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LoopIteration> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LoopIterationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopIterationInsertCallbackId {
        LoopIterationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LoopIterationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LoopIterationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoopIterationDeleteCallbackId {
        LoopIterationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LoopIterationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LoopIterationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LoopIterationsTableHandle<'ctx> {
    type UpdateCallbackId = LoopIterationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LoopIterationUpdateCallbackId {
        LoopIterationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LoopIterationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct LoopIterationIterationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LoopIteration, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LoopIterationsTableHandle<'ctx> {
    pub fn iteration_id(&self) -> LoopIterationIterationIdUnique<'ctx> {
        LoopIterationIterationIdUnique {
            imp: self.imp.get_unique_constraint::<String>("iteration_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LoopIterationIterationIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<LoopIteration> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LoopIteration>("loop_iterations");
    _table.add_unique_constraint::<String>("iteration_id", |row| &row.iteration_id);
}

pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LoopIteration>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LoopIteration>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
