// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NodeStatus {
    pub node_id: String,
    pub last_heartbeat_at: String,
    pub first_seen_at: String,
    pub last_seen_at: String,
    pub status: String,
    pub meta_json: String,
    pub capabilities_json: String,
    pub agent_version: String,
    pub tags_json: String,
    pub max_concurrency: i64,
}

impl __sdk::InModule for NodeStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NodeStatus`.
///
/// Provides typed access to columns for query building.
pub struct NodeStatusCols {
    pub node_id: __sdk::__query_builder::Col<NodeStatus, String>,
    pub last_heartbeat_at: __sdk::__query_builder::Col<NodeStatus, String>,
    pub first_seen_at: __sdk::__query_builder::Col<NodeStatus, String>,
    pub last_seen_at: __sdk::__query_builder::Col<NodeStatus, String>,
    pub status: __sdk::__query_builder::Col<NodeStatus, String>,
    pub meta_json: __sdk::__query_builder::Col<NodeStatus, String>,
    pub capabilities_json: __sdk::__query_builder::Col<NodeStatus, String>,
    pub agent_version: __sdk::__query_builder::Col<NodeStatus, String>,
    pub tags_json: __sdk::__query_builder::Col<NodeStatus, String>,
    pub max_concurrency: __sdk::__query_builder::Col<NodeStatus, i64>,
}

impl __sdk::__query_builder::HasCols for NodeStatus {
    type Cols = NodeStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NodeStatusCols {
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            last_heartbeat_at: __sdk::__query_builder::Col::new(table_name, "last_heartbeat_at"),
            first_seen_at: __sdk::__query_builder::Col::new(table_name, "first_seen_at"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            meta_json: __sdk::__query_builder::Col::new(table_name, "meta_json"),
            capabilities_json: __sdk::__query_builder::Col::new(table_name, "capabilities_json"),
            agent_version: __sdk::__query_builder::Col::new(table_name, "agent_version"),
            tags_json: __sdk::__query_builder::Col::new(table_name, "tags_json"),
            max_concurrency: __sdk::__query_builder::Col::new(table_name, "max_concurrency"),
        }
    }
}

/// Indexed column accessor struct for the table `NodeStatus`.
///
/// Provides typed access to indexed columns for query building.
pub struct NodeStatusIxCols {
    pub last_seen_at: __sdk::__query_builder::IxCol<NodeStatus, String>,
    pub node_id: __sdk::__query_builder::IxCol<NodeStatus, String>,
    pub status: __sdk::__query_builder::IxCol<NodeStatus, String>,
}

impl __sdk::__query_builder::HasIxCols for NodeStatus {
    type IxCols = NodeStatusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NodeStatusIxCols {
            last_seen_at: __sdk::__query_builder::IxCol::new(table_name, "last_seen_at"),
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NodeStatus {}
