// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NoveltyVector {
    pub vector_id: String,
    pub run_id: String,
    pub mission_id: String,
    pub turn_index: u32,
    pub new_entity: f64,
    pub new_contradiction: f64,
    pub stronger_citation: f64,
    pub new_causal_connection: f64,
    pub changed_recommendation: f64,
    pub composite_score: f64,
    pub created_at: String,
}

impl __sdk::InModule for NoveltyVector {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NoveltyVector`.
///
/// Provides typed access to columns for query building.
pub struct NoveltyVectorCols {
    pub vector_id: __sdk::__query_builder::Col<NoveltyVector, String>,
    pub run_id: __sdk::__query_builder::Col<NoveltyVector, String>,
    pub mission_id: __sdk::__query_builder::Col<NoveltyVector, String>,
    pub turn_index: __sdk::__query_builder::Col<NoveltyVector, u32>,
    pub new_entity: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub new_contradiction: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub stronger_citation: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub new_causal_connection: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub changed_recommendation: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub composite_score: __sdk::__query_builder::Col<NoveltyVector, f64>,
    pub created_at: __sdk::__query_builder::Col<NoveltyVector, String>,
}

impl __sdk::__query_builder::HasCols for NoveltyVector {
    type Cols = NoveltyVectorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NoveltyVectorCols {
            vector_id: __sdk::__query_builder::Col::new(table_name, "vector_id"),
            run_id: __sdk::__query_builder::Col::new(table_name, "run_id"),
            mission_id: __sdk::__query_builder::Col::new(table_name, "mission_id"),
            turn_index: __sdk::__query_builder::Col::new(table_name, "turn_index"),
            new_entity: __sdk::__query_builder::Col::new(table_name, "new_entity"),
            new_contradiction: __sdk::__query_builder::Col::new(table_name, "new_contradiction"),
            stronger_citation: __sdk::__query_builder::Col::new(table_name, "stronger_citation"),
            new_causal_connection: __sdk::__query_builder::Col::new(
                table_name,
                "new_causal_connection",
            ),
            changed_recommendation: __sdk::__query_builder::Col::new(
                table_name,
                "changed_recommendation",
            ),
            composite_score: __sdk::__query_builder::Col::new(table_name, "composite_score"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NoveltyVector`.
///
/// Provides typed access to indexed columns for query building.
pub struct NoveltyVectorIxCols {
    pub composite_score: __sdk::__query_builder::IxCol<NoveltyVector, f64>,
    pub mission_id: __sdk::__query_builder::IxCol<NoveltyVector, String>,
    pub run_id: __sdk::__query_builder::IxCol<NoveltyVector, String>,
    pub turn_index: __sdk::__query_builder::IxCol<NoveltyVector, u32>,
    pub vector_id: __sdk::__query_builder::IxCol<NoveltyVector, String>,
}

impl __sdk::__query_builder::HasIxCols for NoveltyVector {
    type IxCols = NoveltyVectorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NoveltyVectorIxCols {
            composite_score: __sdk::__query_builder::IxCol::new(table_name, "composite_score"),
            mission_id: __sdk::__query_builder::IxCol::new(table_name, "mission_id"),
            run_id: __sdk::__query_builder::IxCol::new(table_name, "run_id"),
            turn_index: __sdk::__query_builder::IxCol::new(table_name, "turn_index"),
            vector_id: __sdk::__query_builder::IxCol::new(table_name, "vector_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NoveltyVector {}
