// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OAuthIdentity {
    pub identity_id: String,
    pub user_id: String,
    pub provider: String,
    pub provider_user_id: String,
    pub username: String,
    pub access_token_enc: String,
    pub refresh_token_enc: Option<String>,
    pub token_expires_at: Option<String>,
    pub scopes_json: String,
    pub created_at: String,
    pub updated_at: String,
}

impl __sdk::InModule for OAuthIdentity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OAuthIdentity`.
///
/// Provides typed access to columns for query building.
pub struct OAuthIdentityCols {
    pub identity_id: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub user_id: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub provider: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub provider_user_id: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub username: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub access_token_enc: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub refresh_token_enc: __sdk::__query_builder::Col<OAuthIdentity, Option<String>>,
    pub token_expires_at: __sdk::__query_builder::Col<OAuthIdentity, Option<String>>,
    pub scopes_json: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub created_at: __sdk::__query_builder::Col<OAuthIdentity, String>,
    pub updated_at: __sdk::__query_builder::Col<OAuthIdentity, String>,
}

impl __sdk::__query_builder::HasCols for OAuthIdentity {
    type Cols = OAuthIdentityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OAuthIdentityCols {
            identity_id: __sdk::__query_builder::Col::new(table_name, "identity_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            provider_user_id: __sdk::__query_builder::Col::new(table_name, "provider_user_id"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            access_token_enc: __sdk::__query_builder::Col::new(table_name, "access_token_enc"),
            refresh_token_enc: __sdk::__query_builder::Col::new(table_name, "refresh_token_enc"),
            token_expires_at: __sdk::__query_builder::Col::new(table_name, "token_expires_at"),
            scopes_json: __sdk::__query_builder::Col::new(table_name, "scopes_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OAuthIdentity`.
///
/// Provides typed access to indexed columns for query building.
pub struct OAuthIdentityIxCols {
    pub identity_id: __sdk::__query_builder::IxCol<OAuthIdentity, String>,
    pub user_id: __sdk::__query_builder::IxCol<OAuthIdentity, String>,
}

impl __sdk::__query_builder::HasIxCols for OAuthIdentity {
    type IxCols = OAuthIdentityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OAuthIdentityIxCols {
            identity_id: __sdk::__query_builder::IxCol::new(table_name, "identity_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OAuthIdentity {}
