// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::o_auth_identity_type::OAuthIdentity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `oauth_identities`.
///
/// Obtain a handle from the [`OauthIdentitiesTableAccess::oauth_identities`] method on [`super::RemoteTables`],
/// like `ctx.db.oauth_identities()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.oauth_identities().on_insert(...)`.
pub struct OauthIdentitiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<OAuthIdentity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `oauth_identities`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OauthIdentitiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OauthIdentitiesTableHandle`], which mediates access to the table `oauth_identities`.
    fn oauth_identities(&self) -> OauthIdentitiesTableHandle<'_>;
}

impl OauthIdentitiesTableAccess for super::RemoteTables {
    fn oauth_identities(&self) -> OauthIdentitiesTableHandle<'_> {
        OauthIdentitiesTableHandle {
            imp: self.imp.get_table::<OAuthIdentity>("oauth_identities"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OauthIdentitiesInsertCallbackId(__sdk::CallbackId);
pub struct OauthIdentitiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OauthIdentitiesTableHandle<'ctx> {
    type Row = OAuthIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OAuthIdentity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OauthIdentitiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OauthIdentitiesInsertCallbackId {
        OauthIdentitiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OauthIdentitiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OauthIdentitiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OauthIdentitiesDeleteCallbackId {
        OauthIdentitiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OauthIdentitiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OauthIdentitiesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OauthIdentitiesTableHandle<'ctx> {
    type UpdateCallbackId = OauthIdentitiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OauthIdentitiesUpdateCallbackId {
        OauthIdentitiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OauthIdentitiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity_id` unique index on the table `oauth_identities`,
/// which allows point queries on the field of the same name
/// via the [`OauthIdentitiesIdentityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.oauth_identities().identity_id().find(...)`.
pub struct OauthIdentitiesIdentityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<OAuthIdentity, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OauthIdentitiesTableHandle<'ctx> {
    /// Get a handle on the `identity_id` unique index on the table `oauth_identities`.
    pub fn identity_id(&self) -> OauthIdentitiesIdentityIdUnique<'ctx> {
        OauthIdentitiesIdentityIdUnique {
            imp: self.imp.get_unique_constraint::<String>("identity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OauthIdentitiesIdentityIdUnique<'ctx> {
    /// Find the subscribed row whose `identity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<OAuthIdentity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OAuthIdentity>("oauth_identities");
    _table.add_unique_constraint::<String>("identity_id", |row| &row.identity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OAuthIdentity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OAuthIdentity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OAuthIdentity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait oauth_identitiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OAuthIdentity`.
    fn oauth_identities(&self) -> __sdk::__query_builder::Table<OAuthIdentity>;
}

impl oauth_identitiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn oauth_identities(&self) -> __sdk::__query_builder::Table<OAuthIdentity> {
        __sdk::__query_builder::Table::new("oauth_identities")
    }
}
