// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::platform_entitlement_type::PlatformEntitlement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct PlatformEntitlementsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlatformEntitlement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait PlatformEntitlementsTableAccess {
    #[allow(non_snake_case)]
    fn platform_entitlements(&self) -> PlatformEntitlementsTableHandle<'_>;
}

impl PlatformEntitlementsTableAccess for super::RemoteTables {
    fn platform_entitlements(&self) -> PlatformEntitlementsTableHandle<'_> {
        PlatformEntitlementsTableHandle {
            imp: self.imp.get_table::<PlatformEntitlement>("platform_entitlements"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlatformEntitlementInsertCallbackId(__sdk::CallbackId);
pub struct PlatformEntitlementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlatformEntitlementsTableHandle<'ctx> {
    type Row = PlatformEntitlement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlatformEntitlement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlatformEntitlementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlatformEntitlementInsertCallbackId {
        PlatformEntitlementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlatformEntitlementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlatformEntitlementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlatformEntitlementDeleteCallbackId {
        PlatformEntitlementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlatformEntitlementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlatformEntitlementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlatformEntitlementsTableHandle<'ctx> {
    type UpdateCallbackId = PlatformEntitlementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlatformEntitlementUpdateCallbackId {
        PlatformEntitlementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlatformEntitlementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct PlatformEntitlementUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlatformEntitlement, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlatformEntitlementsTableHandle<'ctx> {
    pub fn user_id(&self) -> PlatformEntitlementUserIdUnique<'ctx> {
        PlatformEntitlementUserIdUnique {
            imp: self.imp.get_unique_constraint::<String>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlatformEntitlementUserIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<PlatformEntitlement> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlatformEntitlement>("platform_entitlements");
    _table.add_unique_constraint::<String>("user_id", |row| &row.user_id);
}

pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlatformEntitlement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlatformEntitlement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
