// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProviderAccount {
    pub account_id: String,
    pub provider_id: String,
    pub node_id: String,
    pub auth_kind: String,
    pub local_handle_ref: String,
    pub status: String,
    pub display_name: Option<String>,
    pub default_model: Option<String>,
    pub rate_group: String,
    pub available_models_json: String,
    pub last_validated_at: Option<String>,
    pub last_error: Option<String>,
    pub updated_at: String,
    pub user_id: Option<String>,
}

impl __sdk::InModule for ProviderAccount {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProviderAccount`.
///
/// Provides typed access to columns for query building.
pub struct ProviderAccountCols {
    pub account_id: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub provider_id: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub node_id: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub auth_kind: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub local_handle_ref: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub status: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub display_name: __sdk::__query_builder::Col<ProviderAccount, Option<String>>,
    pub default_model: __sdk::__query_builder::Col<ProviderAccount, Option<String>>,
    pub rate_group: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub available_models_json: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub last_validated_at: __sdk::__query_builder::Col<ProviderAccount, Option<String>>,
    pub last_error: __sdk::__query_builder::Col<ProviderAccount, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<ProviderAccount, String>,
    pub user_id: __sdk::__query_builder::Col<ProviderAccount, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ProviderAccount {
    type Cols = ProviderAccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProviderAccountCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            provider_id: __sdk::__query_builder::Col::new(table_name, "provider_id"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            auth_kind: __sdk::__query_builder::Col::new(table_name, "auth_kind"),
            local_handle_ref: __sdk::__query_builder::Col::new(table_name, "local_handle_ref"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            default_model: __sdk::__query_builder::Col::new(table_name, "default_model"),
            rate_group: __sdk::__query_builder::Col::new(table_name, "rate_group"),
            available_models_json: __sdk::__query_builder::Col::new(
                table_name,
                "available_models_json",
            ),
            last_validated_at: __sdk::__query_builder::Col::new(table_name, "last_validated_at"),
            last_error: __sdk::__query_builder::Col::new(table_name, "last_error"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ProviderAccount`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProviderAccountIxCols {
    pub account_id: __sdk::__query_builder::IxCol<ProviderAccount, String>,
    pub node_id: __sdk::__query_builder::IxCol<ProviderAccount, String>,
    pub provider_id: __sdk::__query_builder::IxCol<ProviderAccount, String>,
    pub status: __sdk::__query_builder::IxCol<ProviderAccount, String>,
    pub updated_at: __sdk::__query_builder::IxCol<ProviderAccount, String>,
    pub user_id: __sdk::__query_builder::IxCol<ProviderAccount, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for ProviderAccount {
    type IxCols = ProviderAccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProviderAccountIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
            provider_id: __sdk::__query_builder::IxCol::new(table_name, "provider_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            updated_at: __sdk::__query_builder::IxCol::new(table_name, "updated_at"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProviderAccount {}
