// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rate_group_state_type::RateGroupState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub struct RateGroupStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<RateGroupState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
pub trait RateGroupStateTableAccess {
    #[allow(non_snake_case)]
    fn rate_group_state(&self) -> RateGroupStateTableHandle<'_>;
}

impl RateGroupStateTableAccess for super::RemoteTables {
    fn rate_group_state(&self) -> RateGroupStateTableHandle<'_> {
        RateGroupStateTableHandle {
            imp: self.imp.get_table::<RateGroupState>("rate_group_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RateGroupStateInsertCallbackId(__sdk::CallbackId);
pub struct RateGroupStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RateGroupStateTableHandle<'ctx> {
    type Row = RateGroupState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RateGroupState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RateGroupStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RateGroupStateInsertCallbackId {
        RateGroupStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RateGroupStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RateGroupStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RateGroupStateDeleteCallbackId {
        RateGroupStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RateGroupStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RateGroupStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RateGroupStateTableHandle<'ctx> {
    type UpdateCallbackId = RateGroupStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RateGroupStateUpdateCallbackId {
        RateGroupStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RateGroupStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

pub struct RateGroupStateGroupIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RateGroupState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RateGroupStateTableHandle<'ctx> {
    pub fn group_id(&self) -> RateGroupStateGroupIdUnique<'ctx> {
        RateGroupStateGroupIdUnique {
            imp: self.imp.get_unique_constraint::<String>("group_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RateGroupStateGroupIdUnique<'ctx> {
    pub fn find(&self, col_val: &String) -> Option<RateGroupState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RateGroupState>("rate_group_state");
    _table.add_unique_constraint::<String>("group_id", |row| &row.group_id);
}

pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RateGroupState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RateGroupState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
