// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordSpendArgs {
    pub treasury_id: String,
    pub requests: i64,
    pub tokens_in: i64,
    pub tokens_out: i64,
    pub cost_millicents: i64,
}

impl From<RecordSpendArgs> for super::Reducer {
    fn from(args: RecordSpendArgs) -> Self {
        Self::RecordSpend {
            treasury_id: args.treasury_id,
            requests: args.requests,
            tokens_in: args.tokens_in,
            tokens_out: args.tokens_out,
            cost_millicents: args.cost_millicents,
        }
    }
}

impl __sdk::InModule for RecordSpendArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_spend`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_spend {
    /// Request that the remote module invoke the reducer `record_spend` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_spend:record_spend_then`] to run a callback after the reducer completes.
    fn record_spend(
        &self,
        treasury_id: String,
        requests: i64,
        tokens_in: i64,
        tokens_out: i64,
        cost_millicents: i64,
    ) -> __sdk::Result<()> {
        self.record_spend_then(
            treasury_id,
            requests,
            tokens_in,
            tokens_out,
            cost_millicents,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_spend` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_spend_then(
        &self,
        treasury_id: String,
        requests: i64,
        tokens_in: i64,
        tokens_out: i64,
        cost_millicents: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_spend for super::RemoteReducers {
    fn record_spend_then(
        &self,
        treasury_id: String,
        requests: i64,
        tokens_in: i64,
        tokens_out: i64,
        cost_millicents: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordSpendArgs {
                treasury_id,
                requests,
                tokens_in,
                tokens_out,
                cost_millicents,
            },
            callback,
        )
    }
}
