// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordDispatchAckArgs {
    pub ack_id: String,
    pub lease_id: String,
    pub session_id: String,
    pub task_id: String,
    pub node_id: String,
    pub status: String,
    pub decided_at: String,
    pub detail: Option<String>,
}

impl From<RecordDispatchAckArgs> for super::Reducer {
    fn from(args: RecordDispatchAckArgs) -> Self {
        Self::RecordDispatchAck {
            ack_id: args.ack_id,
            lease_id: args.lease_id,
            session_id: args.session_id,
            task_id: args.task_id,
            node_id: args.node_id,
            status: args.status,
            decided_at: args.decided_at,
            detail: args.detail,
        }
    }
}

impl __sdk::InModule for RecordDispatchAckArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_dispatch_ack`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_dispatch_ack {
    /// Request that the remote module invoke the reducer `record_dispatch_ack` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_dispatch_ack:record_dispatch_ack_then`] to run a callback after the reducer completes.
    fn record_dispatch_ack(
        &self,
        ack_id: String,
        lease_id: String,
        session_id: String,
        task_id: String,
        node_id: String,
        status: String,
        decided_at: String,
        detail: Option<String>,
    ) -> __sdk::Result<()> {
        self.record_dispatch_ack_then(
            ack_id,
            lease_id,
            session_id,
            task_id,
            node_id,
            status,
            decided_at,
            detail,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_dispatch_ack` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_dispatch_ack_then(
        &self,
        ack_id: String,
        lease_id: String,
        session_id: String,
        task_id: String,
        node_id: String,
        status: String,
        decided_at: String,
        detail: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_dispatch_ack for super::RemoteReducers {
    fn record_dispatch_ack_then(
        &self,
        ack_id: String,
        lease_id: String,
        session_id: String,
        task_id: String,
        node_id: String,
        status: String,
        decided_at: String,
        detail: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordDispatchAckArgs {
                ack_id,
                lease_id,
                session_id,
                task_id,
                node_id,
                status,
                decided_at,
                detail,
            },
            callback,
        )
    }
}
