// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordInteractionArgs {
    pub user_id: u64,
    pub channel_id: u64,
    pub intent: String,
}

impl From<RecordInteractionArgs> for super::Reducer {
    fn from(args: RecordInteractionArgs) -> Self {
        Self::RecordInteraction {
            user_id: args.user_id,
            channel_id: args.channel_id,
            intent: args.intent,
        }
    }
}

impl __sdk::InModule for RecordInteractionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_interaction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_interaction {
    /// Request that the remote module invoke the reducer `record_interaction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_interaction:record_interaction_then`] to run a callback after the reducer completes.
    fn record_interaction(
        &self,
        user_id: u64,
        channel_id: u64,
        intent: String,
    ) -> __sdk::Result<()> {
        self.record_interaction_then(user_id, channel_id, intent, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_interaction` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_interaction_then(
        &self,
        user_id: u64,
        channel_id: u64,
        intent: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_interaction for super::RemoteReducers {
    fn record_interaction_then(
        &self,
        user_id: u64,
        channel_id: u64,
        intent: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordInteractionArgs {
                user_id,
                channel_id,
                intent,
            },
            callback,
        )
    }
}
