// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordProviderFailureArgs {
    pub treasury_id: String,
    pub failure_type: String,
}

impl From<RecordProviderFailureArgs> for super::Reducer {
    fn from(args: RecordProviderFailureArgs) -> Self {
        Self::RecordProviderFailure {
            treasury_id: args.treasury_id,
            failure_type: args.failure_type,
        }
    }
}

impl __sdk::InModule for RecordProviderFailureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_provider_failure`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_provider_failure {
    /// Request that the remote module invoke the reducer `record_provider_failure` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_provider_failure:record_provider_failure_then`] to run a callback after the reducer completes.
    fn record_provider_failure(
        &self,
        treasury_id: String,
        failure_type: String,
    ) -> __sdk::Result<()> {
        self.record_provider_failure_then(treasury_id, failure_type, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_provider_failure` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_provider_failure_then(
        &self,
        treasury_id: String,
        failure_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_provider_failure for super::RemoteReducers {
    fn record_provider_failure_then(
        &self,
        treasury_id: String,
        failure_type: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordProviderFailureArgs {
                treasury_id,
                failure_type,
            },
            callback,
        )
    }
}
