// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordProposalHeartbeatArgs {
    pub proposal_id: String,
    pub node_id: String,
    pub node_instance_id: String,
    pub heartbeat_at: String,
    pub detail: Option<String>,
}

impl From<RecordProposalHeartbeatArgs> for super::Reducer {
    fn from(args: RecordProposalHeartbeatArgs) -> Self {
        Self::RecordProposalHeartbeat {
            proposal_id: args.proposal_id,
            node_id: args.node_id,
            node_instance_id: args.node_instance_id,
            heartbeat_at: args.heartbeat_at,
            detail: args.detail,
        }
    }
}

impl __sdk::InModule for RecordProposalHeartbeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_proposal_heartbeat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_proposal_heartbeat {
    /// Request that the remote module invoke the reducer `record_proposal_heartbeat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_proposal_heartbeat:record_proposal_heartbeat_then`] to run a callback after the reducer completes.
    fn record_proposal_heartbeat(
        &self,
        proposal_id: String,
        node_id: String,
        node_instance_id: String,
        heartbeat_at: String,
        detail: Option<String>,
    ) -> __sdk::Result<()> {
        self.record_proposal_heartbeat_then(
            proposal_id,
            node_id,
            node_instance_id,
            heartbeat_at,
            detail,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_proposal_heartbeat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_proposal_heartbeat_then(
        &self,
        proposal_id: String,
        node_id: String,
        node_instance_id: String,
        heartbeat_at: String,
        detail: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_proposal_heartbeat for super::RemoteReducers {
    fn record_proposal_heartbeat_then(
        &self,
        proposal_id: String,
        node_id: String,
        node_instance_id: String,
        heartbeat_at: String,
        detail: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordProposalHeartbeatArgs {
                proposal_id,
                node_id,
                node_instance_id,
                heartbeat_at,
                detail,
            },
            callback,
        )
    }
}
