// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordRouteDecisionArgs {
    pub request_id: String,
    pub task_id: String,
    pub envelope_version: String,
    pub raw_text: String,
    pub source_surface: String,
    pub intent_class: String,
    pub risk_level: String,
    pub privacy_level: String,
    pub compute_class: i64,
    pub assigned_worker: String,
    pub target_tool: String,
    pub target_model: String,
    pub target_runtime: String,
    pub target_tier: String,
    pub requires_approval: bool,
    pub rationale: String,
    pub confidence: f64,
    pub gateway_transport: String,
    pub created_at: String,
}

impl From<RecordRouteDecisionArgs> for super::Reducer {
    fn from(args: RecordRouteDecisionArgs) -> Self {
        Self::RecordRouteDecision {
            request_id: args.request_id,
            task_id: args.task_id,
            envelope_version: args.envelope_version,
            raw_text: args.raw_text,
            source_surface: args.source_surface,
            intent_class: args.intent_class,
            risk_level: args.risk_level,
            privacy_level: args.privacy_level,
            compute_class: args.compute_class,
            assigned_worker: args.assigned_worker,
            target_tool: args.target_tool,
            target_model: args.target_model,
            target_runtime: args.target_runtime,
            target_tier: args.target_tier,
            requires_approval: args.requires_approval,
            rationale: args.rationale,
            confidence: args.confidence,
            gateway_transport: args.gateway_transport,
            created_at: args.created_at,
        }
    }
}

impl __sdk::InModule for RecordRouteDecisionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_route_decision`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_route_decision {
    /// Request that the remote module invoke the reducer `record_route_decision` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_route_decision:record_route_decision_then`] to run a callback after the reducer completes.
    fn record_route_decision(
        &self,
        request_id: String,
        task_id: String,
        envelope_version: String,
        raw_text: String,
        source_surface: String,
        intent_class: String,
        risk_level: String,
        privacy_level: String,
        compute_class: i64,
        assigned_worker: String,
        target_tool: String,
        target_model: String,
        target_runtime: String,
        target_tier: String,
        requires_approval: bool,
        rationale: String,
        confidence: f64,
        gateway_transport: String,
        created_at: String,
    ) -> __sdk::Result<()> {
        self.record_route_decision_then(
            request_id,
            task_id,
            envelope_version,
            raw_text,
            source_surface,
            intent_class,
            risk_level,
            privacy_level,
            compute_class,
            assigned_worker,
            target_tool,
            target_model,
            target_runtime,
            target_tier,
            requires_approval,
            rationale,
            confidence,
            gateway_transport,
            created_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_route_decision` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_route_decision_then(
        &self,
        request_id: String,
        task_id: String,
        envelope_version: String,
        raw_text: String,
        source_surface: String,
        intent_class: String,
        risk_level: String,
        privacy_level: String,
        compute_class: i64,
        assigned_worker: String,
        target_tool: String,
        target_model: String,
        target_runtime: String,
        target_tier: String,
        requires_approval: bool,
        rationale: String,
        confidence: f64,
        gateway_transport: String,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_route_decision for super::RemoteReducers {
    fn record_route_decision_then(
        &self,
        request_id: String,
        task_id: String,
        envelope_version: String,
        raw_text: String,
        source_surface: String,
        intent_class: String,
        risk_level: String,
        privacy_level: String,
        compute_class: i64,
        assigned_worker: String,
        target_tool: String,
        target_model: String,
        target_runtime: String,
        target_tier: String,
        requires_approval: bool,
        rationale: String,
        confidence: f64,
        gateway_transport: String,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordRouteDecisionArgs {
                request_id,
                task_id,
                envelope_version,
                raw_text,
                source_surface,
                intent_class,
                risk_level,
                privacy_level,
                compute_class,
                assigned_worker,
                target_tool,
                target_model,
                target_runtime,
                target_tier,
                requires_approval,
                rationale,
                confidence,
                gateway_transport,
                created_at,
            },
            callback,
        )
    }
}
