// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordLoopIterationArgs {
    pub iteration_id: String,
    pub loop_id: String,
    pub turn_number: u32,
    pub input_summary: String,
    pub output_summary: String,
    pub score: f64,
    pub run_id: Option<String>,
    pub cost_increment: f64,
}

impl From<RecordLoopIterationArgs> for super::Reducer {
    fn from(args: RecordLoopIterationArgs) -> Self {
        Self::RecordLoopIteration {
            iteration_id: args.iteration_id,
            loop_id: args.loop_id,
            turn_number: args.turn_number,
            input_summary: args.input_summary,
            output_summary: args.output_summary,
            score: args.score,
            run_id: args.run_id,
            cost_increment: args.cost_increment,
        }
    }
}

impl __sdk::InModule for RecordLoopIterationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_loop_iteration`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_loop_iteration {
    /// Request that the remote module invoke the reducer `record_loop_iteration` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_loop_iteration:record_loop_iteration_then`] to run a callback after the reducer completes.
    fn record_loop_iteration(
        &self,
        iteration_id: String,
        loop_id: String,
        turn_number: u32,
        input_summary: String,
        output_summary: String,
        score: f64,
        run_id: Option<String>,
        cost_increment: f64,
    ) -> __sdk::Result<()> {
        self.record_loop_iteration_then(
            iteration_id,
            loop_id,
            turn_number,
            input_summary,
            output_summary,
            score,
            run_id,
            cost_increment,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_loop_iteration` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_loop_iteration_then(
        &self,
        iteration_id: String,
        loop_id: String,
        turn_number: u32,
        input_summary: String,
        output_summary: String,
        score: f64,
        run_id: Option<String>,
        cost_increment: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_loop_iteration for super::RemoteReducers {
    fn record_loop_iteration_then(
        &self,
        iteration_id: String,
        loop_id: String,
        turn_number: u32,
        input_summary: String,
        output_summary: String,
        score: f64,
        run_id: Option<String>,
        cost_increment: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordLoopIterationArgs {
                iteration_id,
                loop_id,
                turn_number,
                input_summary,
                output_summary,
                score,
                run_id,
                cost_increment,
            },
            callback,
        )
    }
}
