// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterDeviceArgs {
    pub device_id: String,
    pub user_id: String,
    pub hostname: String,
    pub os: String,
    pub arch: String,
}

impl From<RegisterDeviceArgs> for super::Reducer {
    fn from(args: RegisterDeviceArgs) -> Self {
        Self::RegisterDevice {
            device_id: args.device_id,
            user_id: args.user_id,
            hostname: args.hostname,
            os: args.os,
            arch: args.arch,
        }
    }
}

impl __sdk::InModule for RegisterDeviceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait register_device {
    fn register_device(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,
    ) -> __sdk::Result<()> {
        self.register_device_then(device_id, user_id, hostname, os, arch, |_, _| {})
    }

    fn register_device_then(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_device for super::RemoteReducers {
    fn register_device_then(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterDeviceArgs {
                device_id,
                user_id,
                hostname,
                os,
                arch,
            },
            callback,
        )
    }
}
