// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterDiscordChannelArgs {
    pub channel_id: u64,
    pub name: String,
    pub purpose: String,
    pub metadata: String,
}

impl From<RegisterDiscordChannelArgs> for super::Reducer {
    fn from(args: RegisterDiscordChannelArgs) -> Self {
        Self::RegisterDiscordChannel {
            channel_id: args.channel_id,
            name: args.name,
            purpose: args.purpose,
            metadata: args.metadata,
        }
    }
}

impl __sdk::InModule for RegisterDiscordChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_discord_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_discord_channel {
    /// Request that the remote module invoke the reducer `register_discord_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_discord_channel:register_discord_channel_then`] to run a callback after the reducer completes.
    fn register_discord_channel(
        &self,
        channel_id: u64,
        name: String,
        purpose: String,
        metadata: String,
    ) -> __sdk::Result<()> {
        self.register_discord_channel_then(channel_id, name, purpose, metadata, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_discord_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_discord_channel_then(
        &self,
        channel_id: u64,
        name: String,
        purpose: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_discord_channel for super::RemoteReducers {
    fn register_discord_channel_then(
        &self,
        channel_id: u64,
        name: String,
        purpose: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterDiscordChannelArgs {
                channel_id,
                name,
                purpose,
                metadata,
            },
            callback,
        )
    }
}
