// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterDeviceArgs {
    pub device_id: String,
    pub user_id: String,
    pub hostname: String,
    pub os: String,
    pub arch: String,
}

impl From<RegisterDeviceArgs> for super::Reducer {
    fn from(args: RegisterDeviceArgs) -> Self {
        Self::RegisterDevice {
            device_id: args.device_id,
            user_id: args.user_id,
            hostname: args.hostname,
            os: args.os,
            arch: args.arch,
        }
    }
}

impl __sdk::InModule for RegisterDeviceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_device`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_device {
    /// Request that the remote module invoke the reducer `register_device` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_device:register_device_then`] to run a callback after the reducer completes.
    fn register_device(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,
    ) -> __sdk::Result<()> {
        self.register_device_then(device_id, user_id, hostname, os, arch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_device` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_device_then(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_device for super::RemoteReducers {
    fn register_device_then(
        &self,
        device_id: String,
        user_id: String,
        hostname: String,
        os: String,
        arch: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterDeviceArgs {
                device_id,
                user_id,
                hostname,
                os,
                arch,
            },
            callback,
        )
    }
}
