// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterArtifactArgs {
    pub artifact_id: String,
    pub lease_id: Option<String>,
    pub run_id: Option<String>,
    pub session_id: Option<String>,
    pub user_id: String,
    pub mission_id: String,
    pub cell_run_id: Option<String>,
    pub artifact_type: String,
    pub title: String,
    pub uri: Option<String>,
    pub path: Option<String>,
    pub content_json: String,
    pub created_at: String,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<RegisterArtifactArgs> for super::Reducer {
    fn from(args: RegisterArtifactArgs) -> Self {
        Self::RegisterArtifact {
            artifact_id: args.artifact_id,
            lease_id: args.lease_id,
            run_id: args.run_id,
            session_id: args.session_id,
            user_id: args.user_id,
            mission_id: args.mission_id,
            cell_run_id: args.cell_run_id,
            artifact_type: args.artifact_type,
            title: args.title,
            uri: args.uri,
            path: args.path,
            content_json: args.content_json,
            created_at: args.created_at,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for RegisterArtifactArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_artifact`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_artifact {
    /// Request that the remote module invoke the reducer `register_artifact` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_artifact:register_artifact_then`] to run a callback after the reducer completes.
    fn register_artifact(
        &self,
        artifact_id: String,
        lease_id: Option<String>,
        run_id: Option<String>,
        session_id: Option<String>,
        user_id: String,
        mission_id: String,
        cell_run_id: Option<String>,
        artifact_type: String,
        title: String,
        uri: Option<String>,
        path: Option<String>,
        content_json: String,
        created_at: String,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.register_artifact_then(
            artifact_id,
            lease_id,
            run_id,
            session_id,
            user_id,
            mission_id,
            cell_run_id,
            artifact_type,
            title,
            uri,
            path,
            content_json,
            created_at,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_artifact` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_artifact_then(
        &self,
        artifact_id: String,
        lease_id: Option<String>,
        run_id: Option<String>,
        session_id: Option<String>,
        user_id: String,
        mission_id: String,
        cell_run_id: Option<String>,
        artifact_type: String,
        title: String,
        uri: Option<String>,
        path: Option<String>,
        content_json: String,
        created_at: String,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_artifact for super::RemoteReducers {
    fn register_artifact_then(
        &self,
        artifact_id: String,
        lease_id: Option<String>,
        run_id: Option<String>,
        session_id: Option<String>,
        user_id: String,
        mission_id: String,
        cell_run_id: Option<String>,
        artifact_type: String,
        title: String,
        uri: Option<String>,
        path: Option<String>,
        content_json: String,
        created_at: String,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterArtifactArgs {
                artifact_id,
                lease_id,
                run_id,
                session_id,
                user_id,
                mission_id,
                cell_run_id,
                artifact_type,
                title,
                uri,
                path,
                content_json,
                created_at,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
