// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RejectProposalArgs {
    pub proposal_id: String,
}

impl From<RejectProposalArgs> for super::Reducer {
    fn from(args: RejectProposalArgs) -> Self {
        Self::RejectProposal {
            proposal_id: args.proposal_id,
        }
    }
}

impl __sdk::InModule for RejectProposalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reject_proposal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reject_proposal {
    /// Request that the remote module invoke the reducer `reject_proposal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reject_proposal:reject_proposal_then`] to run a callback after the reducer completes.
    fn reject_proposal(&self, proposal_id: String) -> __sdk::Result<()> {
        self.reject_proposal_then(proposal_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reject_proposal` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reject_proposal_then(
        &self,
        proposal_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reject_proposal for super::RemoteReducers {
    fn reject_proposal_then(
        &self,
        proposal_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RejectProposalArgs { proposal_id }, callback)
    }
}
