// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ResetTreasuryWindowArgs {
    pub treasury_id: String,
}

impl From<ResetTreasuryWindowArgs> for super::Reducer {
    fn from(args: ResetTreasuryWindowArgs) -> Self {
        Self::ResetTreasuryWindow {
            treasury_id: args.treasury_id,
        }
    }
}

impl __sdk::InModule for ResetTreasuryWindowArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reset_treasury_window`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reset_treasury_window {
    /// Request that the remote module invoke the reducer `reset_treasury_window` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reset_treasury_window:reset_treasury_window_then`] to run a callback after the reducer completes.
    fn reset_treasury_window(&self, treasury_id: String) -> __sdk::Result<()> {
        self.reset_treasury_window_then(treasury_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reset_treasury_window` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reset_treasury_window_then(
        &self,
        treasury_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reset_treasury_window for super::RemoteReducers {
    fn reset_treasury_window_then(
        &self,
        treasury_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ResetTreasuryWindowArgs { treasury_id }, callback)
    }
}
