// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RetireBeliefArgs {
    pub belief_id: String,
}

impl From<RetireBeliefArgs> for super::Reducer {
    fn from(args: RetireBeliefArgs) -> Self {
        Self::RetireBelief {
            belief_id: args.belief_id,
        }
    }
}

impl __sdk::InModule for RetireBeliefArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `retire_belief`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait retire_belief {
    /// Request that the remote module invoke the reducer `retire_belief` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`retire_belief:retire_belief_then`] to run a callback after the reducer completes.
    fn retire_belief(&self, belief_id: String) -> __sdk::Result<()> {
        self.retire_belief_then(belief_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `retire_belief` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn retire_belief_then(
        &self,
        belief_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl retire_belief for super::RemoteReducers {
    fn retire_belief_then(
        &self,
        belief_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RetireBeliefArgs { belief_id }, callback)
    }
}
