// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RunRecord {
    pub run_id: String,
    pub proposal_id: String,
    pub started_at: String,
    pub ended_at: String,
    pub status: String,
    pub chain_result_json: String,
    pub signals_json: String,
    pub artifact_index_json: String,
    pub node_id: String,
    pub replay_receipt_json: String,
    pub mode: String,
    pub model_id: String,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub tokens_total: i64,
    pub cost: f64,
    pub user_id: Option<String>,
    pub lease_id: Option<String>,
    pub session_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
    pub failure_code: Option<String>,
    pub failure_message: Option<String>,
}

impl __sdk::InModule for RunRecord {
    type Module = super::RemoteModule;
}
