// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RunFailure {
    pub failure_id: String,
    pub run_id: String,
    pub lease_id: String,
    pub session_id: String,
    pub failure_code: String,
    pub failure_message: String,
    pub failure_type: String,
    pub retryable: bool,
    pub details_json: String,
    pub created_at: String,
}

impl __sdk::InModule for RunFailure {
    type Module = super::RemoteModule;
}
