// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RunRecord {
    pub run_id: String,
    pub proposal_id: String,
    pub started_at: String,
    pub ended_at: String,
    pub status: String,
    pub chain_result_json: String,
    pub signals_json: String,
    pub artifact_index_json: String,
    pub node_id: String,
    pub replay_receipt_json: String,
    pub mode: String,
    pub model_id: String,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub tokens_total: i64,
    pub cost: f64,
    pub user_id: Option<String>,
    pub lease_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl __sdk::InModule for RunRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RunRecord`.
///
/// Provides typed access to columns for query building.
pub struct RunRecordCols {
    pub run_id: __sdk::__query_builder::Col<RunRecord, String>,
    pub proposal_id: __sdk::__query_builder::Col<RunRecord, String>,
    pub started_at: __sdk::__query_builder::Col<RunRecord, String>,
    pub ended_at: __sdk::__query_builder::Col<RunRecord, String>,
    pub status: __sdk::__query_builder::Col<RunRecord, String>,
    pub chain_result_json: __sdk::__query_builder::Col<RunRecord, String>,
    pub signals_json: __sdk::__query_builder::Col<RunRecord, String>,
    pub artifact_index_json: __sdk::__query_builder::Col<RunRecord, String>,
    pub node_id: __sdk::__query_builder::Col<RunRecord, String>,
    pub replay_receipt_json: __sdk::__query_builder::Col<RunRecord, String>,
    pub mode: __sdk::__query_builder::Col<RunRecord, String>,
    pub model_id: __sdk::__query_builder::Col<RunRecord, String>,
    pub tokens_input: __sdk::__query_builder::Col<RunRecord, i64>,
    pub tokens_output: __sdk::__query_builder::Col<RunRecord, i64>,
    pub tokens_total: __sdk::__query_builder::Col<RunRecord, i64>,
    pub cost: __sdk::__query_builder::Col<RunRecord, f64>,
    pub user_id: __sdk::__query_builder::Col<RunRecord, Option<String>>,
    pub lease_id: __sdk::__query_builder::Col<RunRecord, Option<String>>,
    pub owner_id: __sdk::__query_builder::Col<RunRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::Col<RunRecord, Option<String>>,
}

impl __sdk::__query_builder::HasCols for RunRecord {
    type Cols = RunRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RunRecordCols {
            run_id: __sdk::__query_builder::Col::new(table_name, "run_id"),
            proposal_id: __sdk::__query_builder::Col::new(table_name, "proposal_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            chain_result_json: __sdk::__query_builder::Col::new(table_name, "chain_result_json"),
            signals_json: __sdk::__query_builder::Col::new(table_name, "signals_json"),
            artifact_index_json: __sdk::__query_builder::Col::new(
                table_name,
                "artifact_index_json",
            ),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            replay_receipt_json: __sdk::__query_builder::Col::new(
                table_name,
                "replay_receipt_json",
            ),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            model_id: __sdk::__query_builder::Col::new(table_name, "model_id"),
            tokens_input: __sdk::__query_builder::Col::new(table_name, "tokens_input"),
            tokens_output: __sdk::__query_builder::Col::new(table_name, "tokens_output"),
            tokens_total: __sdk::__query_builder::Col::new(table_name, "tokens_total"),
            cost: __sdk::__query_builder::Col::new(table_name, "cost"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::Col::new(table_name, "principal_id"),
        }
    }
}

/// Indexed column accessor struct for the table `RunRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct RunRecordIxCols {
    pub ended_at: __sdk::__query_builder::IxCol<RunRecord, String>,
    pub lease_id: __sdk::__query_builder::IxCol<RunRecord, Option<String>>,
    pub model_id: __sdk::__query_builder::IxCol<RunRecord, String>,
    pub owner_id: __sdk::__query_builder::IxCol<RunRecord, Option<String>>,
    pub principal_id: __sdk::__query_builder::IxCol<RunRecord, Option<String>>,
    pub proposal_id: __sdk::__query_builder::IxCol<RunRecord, String>,
    pub run_id: __sdk::__query_builder::IxCol<RunRecord, String>,
    pub status: __sdk::__query_builder::IxCol<RunRecord, String>,
    pub user_id: __sdk::__query_builder::IxCol<RunRecord, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for RunRecord {
    type IxCols = RunRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RunRecordIxCols {
            ended_at: __sdk::__query_builder::IxCol::new(table_name, "ended_at"),
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            model_id: __sdk::__query_builder::IxCol::new(table_name, "model_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            principal_id: __sdk::__query_builder::IxCol::new(table_name, "principal_id"),
            proposal_id: __sdk::__query_builder::IxCol::new(table_name, "proposal_id"),
            run_id: __sdk::__query_builder::IxCol::new(table_name, "run_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RunRecord {}
