// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Source {
    pub source_id: String,
    pub source_kind: String,
    pub uri: String,
    pub content_hash: String,
    pub title: String,
    pub author: String,
    pub captured_at: String,
    pub published_at: String,
    pub retrieved_by: String,
    pub owner_scope: String,
    pub trust_class: String,
    pub raw_storage_ref: String,
    pub parse_status: String,
    pub supersedes_source_id: Option<String>,
    pub created_at: String,
}

impl __sdk::InModule for Source {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Source`.
///
/// Provides typed access to columns for query building.
pub struct SourceCols {
    pub source_id: __sdk::__query_builder::Col<Source, String>,
    pub source_kind: __sdk::__query_builder::Col<Source, String>,
    pub uri: __sdk::__query_builder::Col<Source, String>,
    pub content_hash: __sdk::__query_builder::Col<Source, String>,
    pub title: __sdk::__query_builder::Col<Source, String>,
    pub author: __sdk::__query_builder::Col<Source, String>,
    pub captured_at: __sdk::__query_builder::Col<Source, String>,
    pub published_at: __sdk::__query_builder::Col<Source, String>,
    pub retrieved_by: __sdk::__query_builder::Col<Source, String>,
    pub owner_scope: __sdk::__query_builder::Col<Source, String>,
    pub trust_class: __sdk::__query_builder::Col<Source, String>,
    pub raw_storage_ref: __sdk::__query_builder::Col<Source, String>,
    pub parse_status: __sdk::__query_builder::Col<Source, String>,
    pub supersedes_source_id: __sdk::__query_builder::Col<Source, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Source, String>,
}

impl __sdk::__query_builder::HasCols for Source {
    type Cols = SourceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SourceCols {
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            source_kind: __sdk::__query_builder::Col::new(table_name, "source_kind"),
            uri: __sdk::__query_builder::Col::new(table_name, "uri"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            author: __sdk::__query_builder::Col::new(table_name, "author"),
            captured_at: __sdk::__query_builder::Col::new(table_name, "captured_at"),
            published_at: __sdk::__query_builder::Col::new(table_name, "published_at"),
            retrieved_by: __sdk::__query_builder::Col::new(table_name, "retrieved_by"),
            owner_scope: __sdk::__query_builder::Col::new(table_name, "owner_scope"),
            trust_class: __sdk::__query_builder::Col::new(table_name, "trust_class"),
            raw_storage_ref: __sdk::__query_builder::Col::new(table_name, "raw_storage_ref"),
            parse_status: __sdk::__query_builder::Col::new(table_name, "parse_status"),
            supersedes_source_id: __sdk::__query_builder::Col::new(
                table_name,
                "supersedes_source_id",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Source`.
///
/// Provides typed access to indexed columns for query building.
pub struct SourceIxCols {
    pub captured_at: __sdk::__query_builder::IxCol<Source, String>,
    pub content_hash: __sdk::__query_builder::IxCol<Source, String>,
    pub owner_scope: __sdk::__query_builder::IxCol<Source, String>,
    pub parse_status: __sdk::__query_builder::IxCol<Source, String>,
    pub source_id: __sdk::__query_builder::IxCol<Source, String>,
    pub source_kind: __sdk::__query_builder::IxCol<Source, String>,
    pub uri: __sdk::__query_builder::IxCol<Source, String>,
}

impl __sdk::__query_builder::HasIxCols for Source {
    type IxCols = SourceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SourceIxCols {
            captured_at: __sdk::__query_builder::IxCol::new(table_name, "captured_at"),
            content_hash: __sdk::__query_builder::IxCol::new(table_name, "content_hash"),
            owner_scope: __sdk::__query_builder::IxCol::new(table_name, "owner_scope"),
            parse_status: __sdk::__query_builder::IxCol::new(table_name, "parse_status"),
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
            source_kind: __sdk::__query_builder::IxCol::new(table_name, "source_kind"),
            uri: __sdk::__query_builder::IxCol::new(table_name, "uri"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Source {}
