// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartLoopSessionArgs {
    pub loop_id: String,
    pub user_id: String,
    pub objective: String,
    pub max_turns: u32,
    pub max_cost_usd: f64,
}

impl From<StartLoopSessionArgs> for super::Reducer {
    fn from(args: StartLoopSessionArgs) -> Self {
        Self::StartLoopSession {
            loop_id: args.loop_id,
            user_id: args.user_id,
            objective: args.objective,
            max_turns: args.max_turns,
            max_cost_usd: args.max_cost_usd,
        }
    }
}

impl __sdk::InModule for StartLoopSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_loop_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_loop_session {
    /// Request that the remote module invoke the reducer `start_loop_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_loop_session:start_loop_session_then`] to run a callback after the reducer completes.
    fn start_loop_session(
        &self,
        loop_id: String,
        user_id: String,
        objective: String,
        max_turns: u32,
        max_cost_usd: f64,
    ) -> __sdk::Result<()> {
        self.start_loop_session_then(
            loop_id,
            user_id,
            objective,
            max_turns,
            max_cost_usd,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `start_loop_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_loop_session_then(
        &self,
        loop_id: String,
        user_id: String,
        objective: String,
        max_turns: u32,
        max_cost_usd: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_loop_session for super::RemoteReducers {
    fn start_loop_session_then(
        &self,
        loop_id: String,
        user_id: String,
        objective: String,
        max_turns: u32,
        max_cost_usd: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StartLoopSessionArgs {
                loop_id,
                user_id,
                objective,
                max_turns,
                max_cost_usd,
            },
            callback,
        )
    }
}
