// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartCellRunArgs {
    pub cell_run_id: String,
    pub mission_id: String,
    pub step_id: Option<String>,
    pub status: String,
    pub cell_id: String,
    pub cell_role: String,
    pub provider: String,
    pub model: String,
    pub rate_group: String,
    pub tool: String,
    pub started_at: String,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub tokens_total: i64,
    pub output_summary: Option<String>,
    pub user_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<StartCellRunArgs> for super::Reducer {
    fn from(args: StartCellRunArgs) -> Self {
        Self::StartCellRun {
            cell_run_id: args.cell_run_id,
            mission_id: args.mission_id,
            step_id: args.step_id,
            status: args.status,
            cell_id: args.cell_id,
            cell_role: args.cell_role,
            provider: args.provider,
            model: args.model,
            rate_group: args.rate_group,
            tool: args.tool,
            started_at: args.started_at,
            tokens_input: args.tokens_input,
            tokens_output: args.tokens_output,
            tokens_total: args.tokens_total,
            output_summary: args.output_summary,
            user_id: args.user_id,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for StartCellRunArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_cell_run`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_cell_run {
    /// Request that the remote module invoke the reducer `start_cell_run` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_cell_run:start_cell_run_then`] to run a callback after the reducer completes.
    fn start_cell_run(
        &self,
        cell_run_id: String,
        mission_id: String,
        step_id: Option<String>,
        status: String,
        cell_id: String,
        cell_role: String,
        provider: String,
        model: String,
        rate_group: String,
        tool: String,
        started_at: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        output_summary: Option<String>,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.start_cell_run_then(
            cell_run_id,
            mission_id,
            step_id,
            status,
            cell_id,
            cell_role,
            provider,
            model,
            rate_group,
            tool,
            started_at,
            tokens_input,
            tokens_output,
            tokens_total,
            output_summary,
            user_id,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `start_cell_run` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_cell_run_then(
        &self,
        cell_run_id: String,
        mission_id: String,
        step_id: Option<String>,
        status: String,
        cell_id: String,
        cell_role: String,
        provider: String,
        model: String,
        rate_group: String,
        tool: String,
        started_at: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        output_summary: Option<String>,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_cell_run for super::RemoteReducers {
    fn start_cell_run_then(
        &self,
        cell_run_id: String,
        mission_id: String,
        step_id: Option<String>,
        status: String,
        cell_id: String,
        cell_role: String,
        provider: String,
        model: String,
        rate_group: String,
        tool: String,
        started_at: String,
        tokens_input: i64,
        tokens_output: i64,
        tokens_total: i64,
        output_summary: Option<String>,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StartCellRunArgs {
                cell_run_id,
                mission_id,
                step_id,
                status,
                cell_id,
                cell_role,
                provider,
                model,
                rate_group,
                tool,
                started_at,
                tokens_input,
                tokens_output,
                tokens_total,
                output_summary,
                user_id,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
