// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TreasuryReservation {
    pub reservation_id: String,
    pub treasury_id: String,
    pub mission_id: String,
    pub reserved_requests: i64,
    pub reserved_tokens: i64,
    pub reserved_cost_millicents: i64,
    pub status: String,
    pub decision: String,
    pub created_at: String,
    pub expires_at: String,
    pub consumed_at: Option<String>,
    pub released_at: Option<String>,
    pub updated_at: String,
}

impl __sdk::InModule for TreasuryReservation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TreasuryReservation`.
///
/// Provides typed access to columns for query building.
pub struct TreasuryReservationCols {
    pub reservation_id: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub treasury_id: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub mission_id: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub reserved_requests: __sdk::__query_builder::Col<TreasuryReservation, i64>,
    pub reserved_tokens: __sdk::__query_builder::Col<TreasuryReservation, i64>,
    pub reserved_cost_millicents: __sdk::__query_builder::Col<TreasuryReservation, i64>,
    pub status: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub decision: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub created_at: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub expires_at: __sdk::__query_builder::Col<TreasuryReservation, String>,
    pub consumed_at: __sdk::__query_builder::Col<TreasuryReservation, Option<String>>,
    pub released_at: __sdk::__query_builder::Col<TreasuryReservation, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<TreasuryReservation, String>,
}

impl __sdk::__query_builder::HasCols for TreasuryReservation {
    type Cols = TreasuryReservationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TreasuryReservationCols {
            reservation_id: __sdk::__query_builder::Col::new(table_name, "reservation_id"),
            treasury_id: __sdk::__query_builder::Col::new(table_name, "treasury_id"),
            mission_id: __sdk::__query_builder::Col::new(table_name, "mission_id"),
            reserved_requests: __sdk::__query_builder::Col::new(table_name, "reserved_requests"),
            reserved_tokens: __sdk::__query_builder::Col::new(table_name, "reserved_tokens"),
            reserved_cost_millicents: __sdk::__query_builder::Col::new(
                table_name,
                "reserved_cost_millicents",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            decision: __sdk::__query_builder::Col::new(table_name, "decision"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            consumed_at: __sdk::__query_builder::Col::new(table_name, "consumed_at"),
            released_at: __sdk::__query_builder::Col::new(table_name, "released_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TreasuryReservation`.
///
/// Provides typed access to indexed columns for query building.
pub struct TreasuryReservationIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<TreasuryReservation, String>,
    pub mission_id: __sdk::__query_builder::IxCol<TreasuryReservation, String>,
    pub reservation_id: __sdk::__query_builder::IxCol<TreasuryReservation, String>,
    pub status: __sdk::__query_builder::IxCol<TreasuryReservation, String>,
    pub treasury_id: __sdk::__query_builder::IxCol<TreasuryReservation, String>,
}

impl __sdk::__query_builder::HasIxCols for TreasuryReservation {
    type IxCols = TreasuryReservationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TreasuryReservationIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            mission_id: __sdk::__query_builder::IxCol::new(table_name, "mission_id"),
            reservation_id: __sdk::__query_builder::IxCol::new(table_name, "reservation_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            treasury_id: __sdk::__query_builder::IxCol::new(table_name, "treasury_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TreasuryReservation {}
