// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Treasury {
    pub treasury_id: String,
    pub scope: String,
    pub provider: String,
    pub account_ref: String,
    pub budget_window_kind: String,
    pub max_requests: i64,
    pub max_tokens_in: i64,
    pub max_tokens_out: i64,
    pub max_cost_millicents: i64,
    pub reserve_fraction: f64,
    pub reserve_policy: String,
    pub degraded_mode_threshold: f64,
    pub health_state: String,
    pub health_score: f64,
    pub cooldown_until: Option<String>,
    pub failure_streak: u32,
    pub last_429_at: Option<String>,
    pub last_auth_failure_at: Option<String>,
    pub spend_so_far_requests: i64,
    pub spend_so_far_tokens_in: i64,
    pub spend_so_far_tokens_out: i64,
    pub spend_so_far_cost_millicents: i64,
    pub last_rebalanced_at: String,
    pub created_at: String,
    pub updated_at: String,
}

impl __sdk::InModule for Treasury {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Treasury`.
///
/// Provides typed access to columns for query building.
pub struct TreasuryCols {
    pub treasury_id: __sdk::__query_builder::Col<Treasury, String>,
    pub scope: __sdk::__query_builder::Col<Treasury, String>,
    pub provider: __sdk::__query_builder::Col<Treasury, String>,
    pub account_ref: __sdk::__query_builder::Col<Treasury, String>,
    pub budget_window_kind: __sdk::__query_builder::Col<Treasury, String>,
    pub max_requests: __sdk::__query_builder::Col<Treasury, i64>,
    pub max_tokens_in: __sdk::__query_builder::Col<Treasury, i64>,
    pub max_tokens_out: __sdk::__query_builder::Col<Treasury, i64>,
    pub max_cost_millicents: __sdk::__query_builder::Col<Treasury, i64>,
    pub reserve_fraction: __sdk::__query_builder::Col<Treasury, f64>,
    pub reserve_policy: __sdk::__query_builder::Col<Treasury, String>,
    pub degraded_mode_threshold: __sdk::__query_builder::Col<Treasury, f64>,
    pub health_state: __sdk::__query_builder::Col<Treasury, String>,
    pub health_score: __sdk::__query_builder::Col<Treasury, f64>,
    pub cooldown_until: __sdk::__query_builder::Col<Treasury, Option<String>>,
    pub failure_streak: __sdk::__query_builder::Col<Treasury, u32>,
    pub last_429_at: __sdk::__query_builder::Col<Treasury, Option<String>>,
    pub last_auth_failure_at: __sdk::__query_builder::Col<Treasury, Option<String>>,
    pub spend_so_far_requests: __sdk::__query_builder::Col<Treasury, i64>,
    pub spend_so_far_tokens_in: __sdk::__query_builder::Col<Treasury, i64>,
    pub spend_so_far_tokens_out: __sdk::__query_builder::Col<Treasury, i64>,
    pub spend_so_far_cost_millicents: __sdk::__query_builder::Col<Treasury, i64>,
    pub last_rebalanced_at: __sdk::__query_builder::Col<Treasury, String>,
    pub created_at: __sdk::__query_builder::Col<Treasury, String>,
    pub updated_at: __sdk::__query_builder::Col<Treasury, String>,
}

impl __sdk::__query_builder::HasCols for Treasury {
    type Cols = TreasuryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TreasuryCols {
            treasury_id: __sdk::__query_builder::Col::new(table_name, "treasury_id"),
            scope: __sdk::__query_builder::Col::new(table_name, "scope"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            account_ref: __sdk::__query_builder::Col::new(table_name, "account_ref"),
            budget_window_kind: __sdk::__query_builder::Col::new(table_name, "budget_window_kind"),
            max_requests: __sdk::__query_builder::Col::new(table_name, "max_requests"),
            max_tokens_in: __sdk::__query_builder::Col::new(table_name, "max_tokens_in"),
            max_tokens_out: __sdk::__query_builder::Col::new(table_name, "max_tokens_out"),
            max_cost_millicents: __sdk::__query_builder::Col::new(
                table_name,
                "max_cost_millicents",
            ),
            reserve_fraction: __sdk::__query_builder::Col::new(table_name, "reserve_fraction"),
            reserve_policy: __sdk::__query_builder::Col::new(table_name, "reserve_policy"),
            degraded_mode_threshold: __sdk::__query_builder::Col::new(
                table_name,
                "degraded_mode_threshold",
            ),
            health_state: __sdk::__query_builder::Col::new(table_name, "health_state"),
            health_score: __sdk::__query_builder::Col::new(table_name, "health_score"),
            cooldown_until: __sdk::__query_builder::Col::new(table_name, "cooldown_until"),
            failure_streak: __sdk::__query_builder::Col::new(table_name, "failure_streak"),
            last_429_at: __sdk::__query_builder::Col::new(table_name, "last_429_at"),
            last_auth_failure_at: __sdk::__query_builder::Col::new(
                table_name,
                "last_auth_failure_at",
            ),
            spend_so_far_requests: __sdk::__query_builder::Col::new(
                table_name,
                "spend_so_far_requests",
            ),
            spend_so_far_tokens_in: __sdk::__query_builder::Col::new(
                table_name,
                "spend_so_far_tokens_in",
            ),
            spend_so_far_tokens_out: __sdk::__query_builder::Col::new(
                table_name,
                "spend_so_far_tokens_out",
            ),
            spend_so_far_cost_millicents: __sdk::__query_builder::Col::new(
                table_name,
                "spend_so_far_cost_millicents",
            ),
            last_rebalanced_at: __sdk::__query_builder::Col::new(table_name, "last_rebalanced_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Treasury`.
///
/// Provides typed access to indexed columns for query building.
pub struct TreasuryIxCols {
    pub health_score: __sdk::__query_builder::IxCol<Treasury, f64>,
    pub health_state: __sdk::__query_builder::IxCol<Treasury, String>,
    pub provider: __sdk::__query_builder::IxCol<Treasury, String>,
    pub scope: __sdk::__query_builder::IxCol<Treasury, String>,
    pub treasury_id: __sdk::__query_builder::IxCol<Treasury, String>,
    pub updated_at: __sdk::__query_builder::IxCol<Treasury, String>,
}

impl __sdk::__query_builder::HasIxCols for Treasury {
    type IxCols = TreasuryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TreasuryIxCols {
            health_score: __sdk::__query_builder::IxCol::new(table_name, "health_score"),
            health_state: __sdk::__query_builder::IxCol::new(table_name, "health_state"),
            provider: __sdk::__query_builder::IxCol::new(table_name, "provider"),
            scope: __sdk::__query_builder::IxCol::new(table_name, "scope"),
            treasury_id: __sdk::__query_builder::IxCol::new(table_name, "treasury_id"),
            updated_at: __sdk::__query_builder::IxCol::new(table_name, "updated_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Treasury {}
