// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertRateGroupStateArgs {
    pub group_id: String,
    pub tier: String,
    pub limit_rpm: i64,
    pub limit_tpm: i64,
    pub current_rpm: i64,
    pub current_tpm: i64,
    pub reset_at: String,
}

impl From<UpsertRateGroupStateArgs> for super::Reducer {
    fn from(args: UpsertRateGroupStateArgs) -> Self {
        Self::UpsertRateGroupState {
            group_id: args.group_id,
            tier: args.tier,
            limit_rpm: args.limit_rpm,
            limit_tpm: args.limit_tpm,
            current_rpm: args.current_rpm,
            current_tpm: args.current_tpm,
            reset_at: args.reset_at,
        }
    }
}

impl __sdk::InModule for UpsertRateGroupStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
pub trait upsert_rate_group_state {
    fn upsert_rate_group_state(
        &self,
        group_id: String,
        tier: String,
        limit_rpm: i64,
        limit_tpm: i64,
        current_rpm: i64,
        current_tpm: i64,
        reset_at: String,
    ) -> __sdk::Result<()> {
        self.upsert_rate_group_state_then(
            group_id,
            tier,
            limit_rpm,
            limit_tpm,
            current_rpm,
            current_tpm,
            reset_at,
            |_, _| {},
        )
    }

    fn upsert_rate_group_state_then(
        &self,
        group_id: String,
        tier: String,
        limit_rpm: i64,
        limit_tpm: i64,
        current_rpm: i64,
        current_tpm: i64,
        reset_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_rate_group_state for super::RemoteReducers {
    fn upsert_rate_group_state_then(
        &self,
        group_id: String,
        tier: String,
        limit_rpm: i64,
        limit_tpm: i64,
        current_rpm: i64,
        current_tpm: i64,
        reset_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertRateGroupStateArgs {
                group_id,
                tier,
                limit_rpm,
                limit_tpm,
                current_rpm,
                current_tpm,
                reset_at,
            },
            callback,
        )
    }
}
