// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertDecayProfileArgs {
    pub decay_profile_id: String,
    pub domain: String,
    pub half_life_seconds: u64,
    pub floor_freshness: f64,
    pub verification_reset_mode: String,
    pub staleness_trigger_policy: String,
}

impl From<UpsertDecayProfileArgs> for super::Reducer {
    fn from(args: UpsertDecayProfileArgs) -> Self {
        Self::UpsertDecayProfile {
            decay_profile_id: args.decay_profile_id,
            domain: args.domain,
            half_life_seconds: args.half_life_seconds,
            floor_freshness: args.floor_freshness,
            verification_reset_mode: args.verification_reset_mode,
            staleness_trigger_policy: args.staleness_trigger_policy,
        }
    }
}

impl __sdk::InModule for UpsertDecayProfileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_decay_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_decay_profile {
    /// Request that the remote module invoke the reducer `upsert_decay_profile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_decay_profile:upsert_decay_profile_then`] to run a callback after the reducer completes.
    fn upsert_decay_profile(
        &self,
        decay_profile_id: String,
        domain: String,
        half_life_seconds: u64,
        floor_freshness: f64,
        verification_reset_mode: String,
        staleness_trigger_policy: String,
    ) -> __sdk::Result<()> {
        self.upsert_decay_profile_then(
            decay_profile_id,
            domain,
            half_life_seconds,
            floor_freshness,
            verification_reset_mode,
            staleness_trigger_policy,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_decay_profile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_decay_profile_then(
        &self,
        decay_profile_id: String,
        domain: String,
        half_life_seconds: u64,
        floor_freshness: f64,
        verification_reset_mode: String,
        staleness_trigger_policy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_decay_profile for super::RemoteReducers {
    fn upsert_decay_profile_then(
        &self,
        decay_profile_id: String,
        domain: String,
        half_life_seconds: u64,
        floor_freshness: f64,
        verification_reset_mode: String,
        staleness_trigger_policy: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertDecayProfileArgs {
                decay_profile_id,
                domain,
                half_life_seconds,
                floor_freshness,
                verification_reset_mode,
                staleness_trigger_policy,
            },
            callback,
        )
    }
}
