// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertBattlefieldArgs {
    pub battlefield_id: String,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
    pub name: String,
    pub repo_url: Option<String>,
    pub root_path: Option<String>,
    pub node_id: Option<String>,
    pub status: String,
    pub created_at: Option<String>,
    pub last_active_at: Option<String>,
}

impl From<UpsertBattlefieldArgs> for super::Reducer {
    fn from(args: UpsertBattlefieldArgs) -> Self {
        Self::UpsertBattlefield {
            battlefield_id: args.battlefield_id,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
            name: args.name,
            repo_url: args.repo_url,
            root_path: args.root_path,
            node_id: args.node_id,
            status: args.status,
            created_at: args.created_at,
            last_active_at: args.last_active_at,
        }
    }
}

impl __sdk::InModule for UpsertBattlefieldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_battlefield`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_battlefield {
    /// Request that the remote module invoke the reducer `upsert_battlefield` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_battlefield:upsert_battlefield_then`] to run a callback after the reducer completes.
    fn upsert_battlefield(
        &self,
        battlefield_id: String,
        owner_id: Option<String>,
        principal_id: Option<String>,
        name: String,
        repo_url: Option<String>,
        root_path: Option<String>,
        node_id: Option<String>,
        status: String,
        created_at: Option<String>,
        last_active_at: Option<String>,
    ) -> __sdk::Result<()> {
        self.upsert_battlefield_then(
            battlefield_id,
            owner_id,
            principal_id,
            name,
            repo_url,
            root_path,
            node_id,
            status,
            created_at,
            last_active_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_battlefield` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_battlefield_then(
        &self,
        battlefield_id: String,
        owner_id: Option<String>,
        principal_id: Option<String>,
        name: String,
        repo_url: Option<String>,
        root_path: Option<String>,
        node_id: Option<String>,
        status: String,
        created_at: Option<String>,
        last_active_at: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_battlefield for super::RemoteReducers {
    fn upsert_battlefield_then(
        &self,
        battlefield_id: String,
        owner_id: Option<String>,
        principal_id: Option<String>,
        name: String,
        repo_url: Option<String>,
        root_path: Option<String>,
        node_id: Option<String>,
        status: String,
        created_at: Option<String>,
        last_active_at: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertBattlefieldArgs {
                battlefield_id,
                owner_id,
                principal_id,
                name,
                repo_url,
                root_path,
                node_id,
                status,
                created_at,
                last_active_at,
            },
            callback,
        )
    }
}
