// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertNodeHeartbeatArgs {
    pub node_id: String,
    pub last_heartbeat_at: String,
    pub last_seen_at: String,
    pub meta_json: String,
    pub capabilities_json: String,
    pub agent_version: String,
    pub tags_json: String,
    pub max_concurrency: i64,
}

impl From<UpsertNodeHeartbeatArgs> for super::Reducer {
    fn from(args: UpsertNodeHeartbeatArgs) -> Self {
        Self::UpsertNodeHeartbeat {
            node_id: args.node_id,
            last_heartbeat_at: args.last_heartbeat_at,
            last_seen_at: args.last_seen_at,
            meta_json: args.meta_json,
            capabilities_json: args.capabilities_json,
            agent_version: args.agent_version,
            tags_json: args.tags_json,
            max_concurrency: args.max_concurrency,
        }
    }
}

impl __sdk::InModule for UpsertNodeHeartbeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_node_heartbeat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_node_heartbeat {
    /// Request that the remote module invoke the reducer `upsert_node_heartbeat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_node_heartbeat:upsert_node_heartbeat_then`] to run a callback after the reducer completes.
    fn upsert_node_heartbeat(
        &self,
        node_id: String,
        last_heartbeat_at: String,
        last_seen_at: String,
        meta_json: String,
        capabilities_json: String,
        agent_version: String,
        tags_json: String,
        max_concurrency: i64,
    ) -> __sdk::Result<()> {
        self.upsert_node_heartbeat_then(
            node_id,
            last_heartbeat_at,
            last_seen_at,
            meta_json,
            capabilities_json,
            agent_version,
            tags_json,
            max_concurrency,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_node_heartbeat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_node_heartbeat_then(
        &self,
        node_id: String,
        last_heartbeat_at: String,
        last_seen_at: String,
        meta_json: String,
        capabilities_json: String,
        agent_version: String,
        tags_json: String,
        max_concurrency: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_node_heartbeat for super::RemoteReducers {
    fn upsert_node_heartbeat_then(
        &self,
        node_id: String,
        last_heartbeat_at: String,
        last_seen_at: String,
        meta_json: String,
        capabilities_json: String,
        agent_version: String,
        tags_json: String,
        max_concurrency: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertNodeHeartbeatArgs {
                node_id,
                last_heartbeat_at,
                last_seen_at,
                meta_json,
                capabilities_json,
                agent_version,
                tags_json,
                max_concurrency,
            },
            callback,
        )
    }
}
