// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertLivenessStateArgs {
    pub key: String,
    pub last_state: String,
    pub last_changed_at: String,
}

impl From<UpsertLivenessStateArgs> for super::Reducer {
    fn from(args: UpsertLivenessStateArgs) -> Self {
        Self::UpsertLivenessState {
            key: args.key,
            last_state: args.last_state,
            last_changed_at: args.last_changed_at,
        }
    }
}

impl __sdk::InModule for UpsertLivenessStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_liveness_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_liveness_state {
    /// Request that the remote module invoke the reducer `upsert_liveness_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_liveness_state:upsert_liveness_state_then`] to run a callback after the reducer completes.
    fn upsert_liveness_state(
        &self,
        key: String,
        last_state: String,
        last_changed_at: String,
    ) -> __sdk::Result<()> {
        self.upsert_liveness_state_then(key, last_state, last_changed_at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_liveness_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_liveness_state_then(
        &self,
        key: String,
        last_state: String,
        last_changed_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_liveness_state for super::RemoteReducers {
    fn upsert_liveness_state_then(
        &self,
        key: String,
        last_state: String,
        last_changed_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertLivenessStateArgs {
                key,
                last_state,
                last_changed_at,
            },
            callback,
        )
    }
}
