// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertProviderAccountStatusArgs {
    pub account_id: String,
    pub provider_id: String,
    pub node_id: String,
    pub auth_kind: String,
    pub local_handle_ref: String,
    pub status: String,
    pub display_name: Option<String>,
    pub default_model: Option<String>,
    pub rate_group: String,
    pub available_models_json: String,
    pub last_validated_at: Option<String>,
    pub last_error: Option<String>,
    pub updated_at: String,
    pub user_id: Option<String>,
}

impl From<UpsertProviderAccountStatusArgs> for super::Reducer {
    fn from(args: UpsertProviderAccountStatusArgs) -> Self {
        Self::UpsertProviderAccountStatus {
            account_id: args.account_id,
            provider_id: args.provider_id,
            node_id: args.node_id,
            auth_kind: args.auth_kind,
            local_handle_ref: args.local_handle_ref,
            status: args.status,
            display_name: args.display_name,
            default_model: args.default_model,
            rate_group: args.rate_group,
            available_models_json: args.available_models_json,
            last_validated_at: args.last_validated_at,
            last_error: args.last_error,
            updated_at: args.updated_at,
            user_id: args.user_id,
        }
    }
}

impl __sdk::InModule for UpsertProviderAccountStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_provider_account_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_provider_account_status {
    /// Request that the remote module invoke the reducer `upsert_provider_account_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_provider_account_status:upsert_provider_account_status_then`] to run a callback after the reducer completes.
    fn upsert_provider_account_status(
        &self,
        account_id: String,
        provider_id: String,
        node_id: String,
        auth_kind: String,
        local_handle_ref: String,
        status: String,
        display_name: Option<String>,
        default_model: Option<String>,
        rate_group: String,
        available_models_json: String,
        last_validated_at: Option<String>,
        last_error: Option<String>,
        updated_at: String,
        user_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.upsert_provider_account_status_then(
            account_id,
            provider_id,
            node_id,
            auth_kind,
            local_handle_ref,
            status,
            display_name,
            default_model,
            rate_group,
            available_models_json,
            last_validated_at,
            last_error,
            updated_at,
            user_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_provider_account_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_provider_account_status_then(
        &self,
        account_id: String,
        provider_id: String,
        node_id: String,
        auth_kind: String,
        local_handle_ref: String,
        status: String,
        display_name: Option<String>,
        default_model: Option<String>,
        rate_group: String,
        available_models_json: String,
        last_validated_at: Option<String>,
        last_error: Option<String>,
        updated_at: String,
        user_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_provider_account_status for super::RemoteReducers {
    fn upsert_provider_account_status_then(
        &self,
        account_id: String,
        provider_id: String,
        node_id: String,
        auth_kind: String,
        local_handle_ref: String,
        status: String,
        display_name: Option<String>,
        default_model: Option<String>,
        rate_group: String,
        available_models_json: String,
        last_validated_at: Option<String>,
        last_error: Option<String>,
        updated_at: String,
        user_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertProviderAccountStatusArgs {
                account_id,
                provider_id,
                node_id,
                auth_kind,
                local_handle_ref,
                status,
                display_name,
                default_model,
                rate_group,
                available_models_json,
                last_validated_at,
                last_error,
                updated_at,
                user_id,
            },
            callback,
        )
    }
}
