// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WriteSessionSummaryArgs {
    pub summary_id: String,
    pub session_id: String,
    pub node_id: String,
    pub created_at: String,
    pub summary_text: String,
    pub metadata_json: String,
    pub user_id: Option<String>,
    pub owner_id: Option<String>,
    pub principal_id: Option<String>,
}

impl From<WriteSessionSummaryArgs> for super::Reducer {
    fn from(args: WriteSessionSummaryArgs) -> Self {
        Self::WriteSessionSummary {
            summary_id: args.summary_id,
            session_id: args.session_id,
            node_id: args.node_id,
            created_at: args.created_at,
            summary_text: args.summary_text,
            metadata_json: args.metadata_json,
            user_id: args.user_id,
            owner_id: args.owner_id,
            principal_id: args.principal_id,
        }
    }
}

impl __sdk::InModule for WriteSessionSummaryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `write_session_summary`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait write_session_summary {
    /// Request that the remote module invoke the reducer `write_session_summary` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`write_session_summary:write_session_summary_then`] to run a callback after the reducer completes.
    fn write_session_summary(
        &self,
        summary_id: String,
        session_id: String,
        node_id: String,
        created_at: String,
        summary_text: String,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.write_session_summary_then(
            summary_id,
            session_id,
            node_id,
            created_at,
            summary_text,
            metadata_json,
            user_id,
            owner_id,
            principal_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `write_session_summary` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn write_session_summary_then(
        &self,
        summary_id: String,
        session_id: String,
        node_id: String,
        created_at: String,
        summary_text: String,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl write_session_summary for super::RemoteReducers {
    fn write_session_summary_then(
        &self,
        summary_id: String,
        session_id: String,
        node_id: String,
        created_at: String,
        summary_text: String,
        metadata_json: String,
        user_id: Option<String>,
        owner_id: Option<String>,
        principal_id: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            WriteSessionSummaryArgs {
                summary_id,
                session_id,
                node_id,
                created_at,
                summary_text,
                metadata_json,
                user_id,
                owner_id,
                principal_id,
            },
            callback,
        )
    }
}
