use anyhow::Result;
use heiwa_paths::RuntimePaths;
use std::fs;
use std::path::Path;

pub fn write_projections(paths: &RuntimePaths) -> Result<()> {
    write_projection(
        &paths.root().join("generated/codex/config.toml"),
        concat!(
            "# Generated by Heiwa runtime.\n",
            "[heiwa]\n",
            "mode = \"concise\"\n",
            "provider_auth_owner = \"provider\"\n",
            "provider_inference_owner = \"provider\"\n",
            "session_owner = \"heiwa\"\n",
            "sandbox_owner = \"heiwa\"\n",
        ),
    )?;
    write_projection(
        &paths.root().join("generated/claude/settings.json"),
        concat!(
            "{\n",
            "  \"mode\": \"concise\",\n",
            "  \"providerAuthOwner\": \"provider\",\n",
            "  \"providerInferenceOwner\": \"provider\",\n",
            "  \"sessionOwner\": \"heiwa\",\n",
            "  \"sandboxOwner\": \"heiwa\"\n",
            "}\n"
        ),
    )?;
    write_projection(
        &paths.root().join("generated/gemini/settings.json"),
        concat!(
            "{\n",
            "  \"mode\": \"concise\",\n",
            "  \"providerAuthOwner\": \"provider\",\n",
            "  \"providerInferenceOwner\": \"provider\",\n",
            "  \"sessionOwner\": \"heiwa\",\n",
            "  \"sandboxOwner\": \"heiwa\"\n",
            "}\n"
        ),
    )?;
    write_projection(
        &paths.root().join("generated/antigravity/settings.json"),
        concat!(
            "{\n",
            "  \"mode\": \"concise\",\n",
            "  \"inherits\": \"gemini\",\n",
            "  \"providerAuthOwner\": \"provider\",\n",
            "  \"providerInferenceOwner\": \"provider\",\n",
            "  \"sessionOwner\": \"heiwa\",\n",
            "  \"sandboxOwner\": \"heiwa\"\n",
            "}\n"
        ),
    )?;
    Ok(())
}

fn write_projection(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}
