// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Task {
    pub id: u64,
    pub session_id: Option<String>,
    pub objective: String,
    pub status: String,
    pub assigned_agent: Option<String>,
}

impl __sdk::InModule for Task {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Task`.
///
/// Provides typed access to columns for query building.
pub struct TaskCols {
    pub id: __sdk::__query_builder::Col<Task, u64>,
    pub session_id: __sdk::__query_builder::Col<Task, Option<String>>,
    pub objective: __sdk::__query_builder::Col<Task, String>,
    pub status: __sdk::__query_builder::Col<Task, String>,
    pub assigned_agent: __sdk::__query_builder::Col<Task, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Task {
    type Cols = TaskCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TaskCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            objective: __sdk::__query_builder::Col::new(table_name, "objective"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            assigned_agent: __sdk::__query_builder::Col::new(table_name, "assigned_agent"),
        }
    }
}

/// Indexed column accessor struct for the table `Task`.
///
/// Provides typed access to indexed columns for query building.
pub struct TaskIxCols {
    pub id: __sdk::__query_builder::IxCol<Task, u64>,
}

impl __sdk::__query_builder::HasIxCols for Task {
    type IxCols = TaskIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TaskIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Task {}
