// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimTaskReducer from "../claim_task_reducer";
import RecordInteractionReducer from "../record_interaction_reducer";
import RecordRouteDecisionReducer from "../record_route_decision_reducer";
import RecordRunReducer from "../record_run_reducer";
import RegisterDiscordChannelReducer from "../register_discord_channel_reducer";
import SetNodeStatusReducer from "../set_node_status_reducer";
import UpsertDiscordUserReducer from "../upsert_discord_user_reducer";
import UpsertLivenessStateReducer from "../upsert_liveness_state_reducer";
import UpsertNodeHeartbeatReducer from "../upsert_node_heartbeat_reducer";

export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type RecordInteractionParams = __Infer<typeof RecordInteractionReducer>;
export type RecordRouteDecisionParams = __Infer<typeof RecordRouteDecisionReducer>;
export type RecordRunParams = __Infer<typeof RecordRunReducer>;
export type RegisterDiscordChannelParams = __Infer<typeof RegisterDiscordChannelReducer>;
export type SetNodeStatusParams = __Infer<typeof SetNodeStatusReducer>;
export type UpsertDiscordUserParams = __Infer<typeof UpsertDiscordUserReducer>;
export type UpsertLivenessStateParams = __Infer<typeof UpsertLivenessStateReducer>;
export type UpsertNodeHeartbeatParams = __Infer<typeof UpsertNodeHeartbeatReducer>;

