/// Every `#[tauri::command]` registered in `tauri::generate_handler!`
/// (`src/lib.rs`). Declaring them here makes `tauri-build` autogenerate an
/// `allow-<command>` / `deny-<command>` permission pair for each one under
/// `src-tauri/permissions/autogenerated/`; a command left out of this list
/// cannot be invoked from the webview no matter what `lib.rs` registers,
/// since no capability could ever grant a permission that does not exist.
///
/// `tests/command_manifest.rs` asserts this list and the `generate_handler!`
/// list stay identical, and `capabilities/default.json` must grant
/// `allow-<command, with underscores turned to dashes>` for each entry here
/// (verified by the tauri-build ACL validator at compile time, which fails
/// the build if a capability references a permission that does not exist).
const COMMANDS: &[&str] = &[
    "herd_command_catalog",
    "herd_pane_focus",
    "herd_pane_read",
    "herd_pane_run",
    "herd_pane_send",
    "herd_pane_split",
    "herd_panes",
    "apple_mail_scan",
    "establish_identity",
    "onboarding_state",
    "complete_workspace_setup",
    "open_resource_guide",
    "connect_api_provider",
    "verify_api_provider",
    "disconnect_api_provider",
    "operator_subscribe",
    "operator_unsubscribe",
    "api_get",
    "api_post",
    "runtime_health",
    "runtime_startup",
    "update_check",
    "update_install",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("tauri-build failed");
}
